# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Wed Jun 21 23:31:44 2017
#      by: PyQt5 UI code generator 5.2.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(795, 649)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/logo.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setDockNestingEnabled(False)
        MainWindow.setDockOptions(QtWidgets.QMainWindow.AllowTabbedDocks|QtWidgets.QMainWindow.AnimatedDocks|QtWidgets.QMainWindow.ForceTabbedDocks)
        MainWindow.setUnifiedTitleAndToolBarOnMac(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.scrollarea = QtWidgets.QScrollArea(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollarea.sizePolicy().hasHeightForWidth())
        self.scrollarea.setSizePolicy(sizePolicy)
        self.scrollarea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollarea.setFrameShadow(QtWidgets.QFrame.Plain)
        self.scrollarea.setLineWidth(0)
        self.scrollarea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollarea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollarea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.scrollarea.setWidgetResizable(True)
        self.scrollarea.setObjectName("scrollarea")
        self.scroll_area_widget_contents = QtWidgets.QWidget()
        self.scroll_area_widget_contents.setGeometry(QtCore.QRect(0, 0, 174, 864))
        self.scroll_area_widget_contents.setObjectName("scroll_area_widget_contents")
        self.formLayout_4 = QtWidgets.QFormLayout(self.scroll_area_widget_contents)
        self.formLayout_4.setObjectName("formLayout_4")
        self.mount_group = QtWidgets.QGroupBox(self.scroll_area_widget_contents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mount_group.sizePolicy().hasHeightForWidth())
        self.mount_group.setSizePolicy(sizePolicy)
        self.mount_group.setCheckable(True)
        self.mount_group.setChecked(False)
        self.mount_group.setObjectName("mount_group")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.mount_group)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontallayout_9 = QtWidgets.QHBoxLayout()
        self.horizontallayout_9.setObjectName("horizontallayout_9")
        self.telescope_name_label = QtWidgets.QLabel(self.mount_group)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.telescope_name_label.sizePolicy().hasHeightForWidth())
        self.telescope_name_label.setSizePolicy(sizePolicy)
        self.telescope_name_label.setWordWrap(True)
        self.telescope_name_label.setObjectName("telescope_name_label")
        self.horizontallayout_9.addWidget(self.telescope_name_label)
        self.scope_settings_btn = QtWidgets.QToolButton(self.mount_group)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scope_settings_btn.sizePolicy().hasHeightForWidth())
        self.scope_settings_btn.setSizePolicy(sizePolicy)
        self.scope_settings_btn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/ic_settings_white_48px.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.scope_settings_btn.setIcon(icon1)
        self.scope_settings_btn.setPopupMode(QtWidgets.QToolButton.InstantPopup)
        self.scope_settings_btn.setObjectName("scope_settings_btn")
        self.horizontallayout_9.addWidget(self.scope_settings_btn)
        self.verticalLayout_3.addLayout(self.horizontallayout_9)
        self.scope_frame = QtWidgets.QFrame(self.mount_group)
        self.scope_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scope_frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.scope_frame.setLineWidth(0)
        self.scope_frame.setObjectName("scope_frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scope_frame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.line_2 = QtWidgets.QFrame(self.scope_frame)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.gridlayout_10 = QtWidgets.QGridLayout()
        self.gridlayout_10.setObjectName("gridlayout_10")
        self.slewnorth_button = QtWidgets.QPushButton(self.scope_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.slewnorth_button.sizePolicy().hasHeightForWidth())
        self.slewnorth_button.setSizePolicy(sizePolicy)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/ic_keyboard_arrow_up_white_48px.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.slewnorth_button.setIcon(icon2)
        self.slewnorth_button.setIconSize(QtCore.QSize(36, 36))
        self.slewnorth_button.setAutoDefault(True)
        self.slewnorth_button.setObjectName("slewnorth_button")
        self.gridlayout_10.addWidget(self.slewnorth_button, 0, 1, 1, 1)
        self.slewsouthwest_button = QtWidgets.QPushButton(self.scope_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.slewsouthwest_button.sizePolicy().hasHeightForWidth())
        self.slewsouthwest_button.setSizePolicy(sizePolicy)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/ic_keyboard_arrow_downleft_white_48px.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.slewsouthwest_button.setIcon(icon3)
        self.slewsouthwest_button.setIconSize(QtCore.QSize(36, 36))
        self.slewsouthwest_button.setAutoDefault(True)
        self.slewsouthwest_button.setFlat(False)
        self.slewsouthwest_button.setObjectName("slewsouthwest_button")
        self.gridlayout_10.addWidget(self.slewsouthwest_button, 2, 0, 1, 1)
        self.sleweast_button = QtWidgets.QPushButton(self.scope_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sleweast_button.sizePolicy().hasHeightForWidth())
        self.sleweast_button.setSizePolicy(sizePolicy)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/ic_keyboard_arrow_right_white_48px.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.sleweast_button.setIcon(icon4)
        self.sleweast_button.setIconSize(QtCore.QSize(36, 36))
        self.sleweast_button.setAutoDefault(True)
        self.sleweast_button.setObjectName("sleweast_button")
        self.gridlayout_10.addWidget(self.sleweast_button, 1, 2, 1, 1)
        self.slewnorthwest_button = QtWidgets.QPushButton(self.scope_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.slewnorthwest_button.sizePolicy().hasHeightForWidth())
        self.slewnorthwest_button.setSizePolicy(sizePolicy)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/ic_keyboard_arrow_upleft_white_48px.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.slewnorthwest_button.setIcon(icon5)
        self.slewnorthwest_button.setIconSize(QtCore.QSize(36, 36))
        self.slewnorthwest_button.setAutoDefault(True)
        self.slewnorthwest_button.setFlat(False)
        self.slewnorthwest_button.setObjectName("slewnorthwest_button")
        self.gridlayout_10.addWidget(self.slewnorthwest_button, 0, 0, 1, 1)
        self.slewsoutheast_button = QtWidgets.QPushButton(self.scope_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.slewsoutheast_button.sizePolicy().hasHeightForWidth())
        self.slewsoutheast_button.setSizePolicy(sizePolicy)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/ic_keyboard_arrow_downright_white_48px.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.slewsoutheast_button.setIcon(icon6)
        self.slewsoutheast_button.setIconSize(QtCore.QSize(36, 36))
        self.slewsoutheast_button.setAutoDefault(True)
        self.slewsoutheast_button.setFlat(False)
        self.slewsoutheast_button.setObjectName("slewsoutheast_button")
        self.gridlayout_10.addWidget(self.slewsoutheast_button, 2, 2, 1, 1)
        self.slewstop_button = QtWidgets.QPushButton(self.scope_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.slewstop_button.sizePolicy().hasHeightForWidth())
        self.slewstop_button.setSizePolicy(sizePolicy)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/ic_report_white_48px.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.slewstop_button.setIcon(icon7)
        self.slewstop_button.setIconSize(QtCore.QSize(36, 36))
        self.slewstop_button.setAutoDefault(True)
        self.slewstop_button.setObjectName("slewstop_button")
        self.gridlayout_10.addWidget(self.slewstop_button, 1, 1, 1, 1)
        self.slewwest_button = QtWidgets.QPushButton(self.scope_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.slewwest_button.sizePolicy().hasHeightForWidth())
        self.slewwest_button.setSizePolicy(sizePolicy)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/ic_keyboard_arrow_left_white_48px.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.slewwest_button.setIcon(icon8)
        self.slewwest_button.setIconSize(QtCore.QSize(36, 36))
        self.slewwest_button.setAutoDefault(True)
        self.slewwest_button.setObjectName("slewwest_button")
        self.gridlayout_10.addWidget(self.slewwest_button, 1, 0, 1, 1)
        self.slewsouth_button = QtWidgets.QPushButton(self.scope_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.slewsouth_button.sizePolicy().hasHeightForWidth())
        self.slewsouth_button.setSizePolicy(sizePolicy)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icons/ic_keyboard_arrow_down_white_48px.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.slewsouth_button.setIcon(icon9)
        self.slewsouth_button.setIconSize(QtCore.QSize(36, 36))
        self.slewsouth_button.setAutoDefault(True)
        self.slewsouth_button.setObjectName("slewsouth_button")
        self.gridlayout_10.addWidget(self.slewsouth_button, 2, 1, 1, 1)
        self.slewnortheast_button = QtWidgets.QPushButton(self.scope_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.slewnortheast_button.sizePolicy().hasHeightForWidth())
        self.slewnortheast_button.setSizePolicy(sizePolicy)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/icons/ic_keyboard_arrow_upright_white_48px.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.slewnortheast_button.setIcon(icon10)
        self.slewnortheast_button.setIconSize(QtCore.QSize(36, 36))
        self.slewnortheast_button.setAutoDefault(True)
        self.slewnortheast_button.setFlat(False)
        self.slewnortheast_button.setObjectName("slewnortheast_button")
        self.gridlayout_10.addWidget(self.slewnortheast_button, 0, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridlayout_10)
        self.formlayout_2 = QtWidgets.QFormLayout()
        self.formlayout_2.setObjectName("formlayout_2")
        self.mount_trackrate_label = QtWidgets.QLabel(self.scope_frame)
        self.mount_trackrate_label.setObjectName("mount_trackrate_label")
        self.formlayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.mount_trackrate_label)
        self.mount_trackrate_spin = QtWidgets.QDoubleSpinBox(self.scope_frame)
        self.mount_trackrate_spin.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.mount_trackrate_spin.setMinimum(0.01)
        self.mount_trackrate_spin.setMaximum(1.0)
        self.mount_trackrate_spin.setSingleStep(0.01)
        self.mount_trackrate_spin.setProperty("value", 0.2)
        self.mount_trackrate_spin.setObjectName("mount_trackrate_spin")
        self.formlayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.mount_trackrate_spin)
        self.verticalLayout.addLayout(self.formlayout_2)
        self.horizontallayout_5 = QtWidgets.QHBoxLayout()
        self.horizontallayout_5.setObjectName("horizontallayout_5")
        self.object_label = QtWidgets.QLabel(self.scope_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.object_label.sizePolicy().hasHeightForWidth())
        self.object_label.setSizePolicy(sizePolicy)
        self.object_label.setObjectName("object_label")
        self.horizontallayout_5.addWidget(self.object_label)
        self.line = QtWidgets.QFrame(self.scope_frame)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontallayout_5.addWidget(self.line)
        self.verticalLayout.addLayout(self.horizontallayout_5)
        self.horizontallayout_4 = QtWidgets.QHBoxLayout()
        self.horizontallayout_4.setObjectName("horizontallayout_4")
        self.object_combobox = QtWidgets.QComboBox(self.scope_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.object_combobox.sizePolicy().hasHeightForWidth())
        self.object_combobox.setSizePolicy(sizePolicy)
        self.object_combobox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.object_combobox.setObjectName("object_combobox")
        self.horizontallayout_4.addWidget(self.object_combobox)
        self.goto_button = QtWidgets.QPushButton(self.scope_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.goto_button.sizePolicy().hasHeightForWidth())
        self.goto_button.setSizePolicy(sizePolicy)
        self.goto_button.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/icons/ic_check_white_48px.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.goto_button.setIcon(icon11)
        self.goto_button.setAutoDefault(True)
        self.goto_button.setObjectName("goto_button")
        self.horizontallayout_4.addWidget(self.goto_button)
        self.verticalLayout.addLayout(self.horizontallayout_4)
        self.verticalLayout_3.addWidget(self.scope_frame)
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.mount_group)
        self.autoguide_group = QtWidgets.QGroupBox(self.scroll_area_widget_contents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.autoguide_group.sizePolicy().hasHeightForWidth())
        self.autoguide_group.setSizePolicy(sizePolicy)
        self.autoguide_group.setCheckable(True)
        self.autoguide_group.setChecked(False)
        self.autoguide_group.setObjectName("autoguide_group")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.autoguide_group)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontallayout_10 = QtWidgets.QHBoxLayout()
        self.horizontallayout_10.setObjectName("horizontallayout_10")
        self.guider_name_label = QtWidgets.QLabel(self.autoguide_group)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.guider_name_label.sizePolicy().hasHeightForWidth())
        self.guider_name_label.setSizePolicy(sizePolicy)
        self.guider_name_label.setWordWrap(True)
        self.guider_name_label.setObjectName("guider_name_label")
        self.horizontallayout_10.addWidget(self.guider_name_label)
        self.guide_settings_btn = QtWidgets.QToolButton(self.autoguide_group)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.guide_settings_btn.sizePolicy().hasHeightForWidth())
        self.guide_settings_btn.setSizePolicy(sizePolicy)
        self.guide_settings_btn.setText("")
        self.guide_settings_btn.setIcon(icon1)
        self.guide_settings_btn.setPopupMode(QtWidgets.QToolButton.InstantPopup)
        self.guide_settings_btn.setObjectName("guide_settings_btn")
        self.horizontallayout_10.addWidget(self.guide_settings_btn)
        self.verticalLayout_2.addLayout(self.horizontallayout_10)
        self.guide_frame = QtWidgets.QFrame(self.autoguide_group)
        self.guide_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.guide_frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.guide_frame.setLineWidth(0)
        self.guide_frame.setObjectName("guide_frame")
        self.formLayout_3 = QtWidgets.QFormLayout(self.guide_frame)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setObjectName("formLayout_3")
        self.line_3 = QtWidgets.QFrame(self.guide_frame)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.line_3)
        self.guider_exposure_label = QtWidgets.QLabel(self.guide_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.guider_exposure_label.sizePolicy().hasHeightForWidth())
        self.guider_exposure_label.setSizePolicy(sizePolicy)
        self.guider_exposure_label.setObjectName("guider_exposure_label")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.guider_exposure_label)
        self.guider_exposure_spinbox = QtWidgets.QSpinBox(self.guide_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.guider_exposure_spinbox.sizePolicy().hasHeightForWidth())
        self.guider_exposure_spinbox.setSizePolicy(sizePolicy)
        self.guider_exposure_spinbox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.guider_exposure_spinbox.setObjectName("guider_exposure_spinbox")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.guider_exposure_spinbox)
        self.guider_exposure_slider = QtWidgets.QSlider(self.guide_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.guider_exposure_slider.sizePolicy().hasHeightForWidth())
        self.guider_exposure_slider.setSizePolicy(sizePolicy)
        self.guider_exposure_slider.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.guider_exposure_slider.setOrientation(QtCore.Qt.Horizontal)
        self.guider_exposure_slider.setObjectName("guider_exposure_slider")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.guider_exposure_slider)
        self.guider_gain_label = QtWidgets.QLabel(self.guide_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.guider_gain_label.sizePolicy().hasHeightForWidth())
        self.guider_gain_label.setSizePolicy(sizePolicy)
        self.guider_gain_label.setObjectName("guider_gain_label")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.guider_gain_label)
        self.guider_gain_spinbox = QtWidgets.QSpinBox(self.guide_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.guider_gain_spinbox.sizePolicy().hasHeightForWidth())
        self.guider_gain_spinbox.setSizePolicy(sizePolicy)
        self.guider_gain_spinbox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.guider_gain_spinbox.setMaximum(600)
        self.guider_gain_spinbox.setObjectName("guider_gain_spinbox")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.guider_gain_spinbox)
        self.guider_gain_slider = QtWidgets.QSlider(self.guide_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.guider_gain_slider.sizePolicy().hasHeightForWidth())
        self.guider_gain_slider.setSizePolicy(sizePolicy)
        self.guider_gain_slider.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.guider_gain_slider.setOrientation(QtCore.Qt.Horizontal)
        self.guider_gain_slider.setObjectName("guider_gain_slider")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.SpanningRole, self.guider_gain_slider)
        self.horizontallayout_7 = QtWidgets.QHBoxLayout()
        self.horizontallayout_7.setObjectName("horizontallayout_7")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontallayout_7.addItem(spacerItem)
        self.guider_loop_button = QtWidgets.QPushButton(self.guide_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.guider_loop_button.sizePolicy().hasHeightForWidth())
        self.guider_loop_button.setSizePolicy(sizePolicy)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/icons/ic_replay_white_48px.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.guider_loop_button.setIcon(icon12)
        self.guider_loop_button.setIconSize(QtCore.QSize(32, 32))
        self.guider_loop_button.setCheckable(True)
        self.guider_loop_button.setAutoDefault(True)
        self.guider_loop_button.setObjectName("guider_loop_button")
        self.horizontallayout_7.addWidget(self.guider_loop_button)
        self.guider_start_button = QtWidgets.QPushButton(self.guide_frame)
        self.guider_start_button.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.guider_start_button.sizePolicy().hasHeightForWidth())
        self.guider_start_button.setSizePolicy(sizePolicy)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/icons/ic_play_arrow_white_48px.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.guider_start_button.setIcon(icon13)
        self.guider_start_button.setIconSize(QtCore.QSize(32, 32))
        self.guider_start_button.setCheckable(True)
        self.guider_start_button.setAutoDefault(True)
        self.guider_start_button.setObjectName("guider_start_button")
        self.horizontallayout_7.addWidget(self.guider_start_button)
        self.formLayout_3.setLayout(5, QtWidgets.QFormLayout.SpanningRole, self.horizontallayout_7)
        self.verticalLayout_2.addWidget(self.guide_frame)
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.autoguide_group)
        self.camera_group = QtWidgets.QGroupBox(self.scroll_area_widget_contents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.camera_group.sizePolicy().hasHeightForWidth())
        self.camera_group.setSizePolicy(sizePolicy)
        self.camera_group.setCheckable(True)
        self.camera_group.setChecked(False)
        self.camera_group.setObjectName("camera_group")
        self.formLayout_8 = QtWidgets.QFormLayout(self.camera_group)
        self.formLayout_8.setObjectName("formLayout_8")
        self.horizontallayout_11 = QtWidgets.QHBoxLayout()
        self.horizontallayout_11.setObjectName("horizontallayout_11")
        self.camera_name_label = QtWidgets.QLabel(self.camera_group)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.camera_name_label.sizePolicy().hasHeightForWidth())
        self.camera_name_label.setSizePolicy(sizePolicy)
        self.camera_name_label.setWordWrap(True)
        self.camera_name_label.setObjectName("camera_name_label")
        self.horizontallayout_11.addWidget(self.camera_name_label)
        self.camera_settings_btn = QtWidgets.QToolButton(self.camera_group)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.camera_settings_btn.sizePolicy().hasHeightForWidth())
        self.camera_settings_btn.setSizePolicy(sizePolicy)
        self.camera_settings_btn.setText("")
        self.camera_settings_btn.setIcon(icon1)
        self.camera_settings_btn.setPopupMode(QtWidgets.QToolButton.InstantPopup)
        self.camera_settings_btn.setObjectName("camera_settings_btn")
        self.horizontallayout_11.addWidget(self.camera_settings_btn)
        self.formLayout_8.setLayout(0, QtWidgets.QFormLayout.SpanningRole, self.horizontallayout_11)
        self.camera_frame = QtWidgets.QFrame(self.camera_group)
        self.camera_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.camera_frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.camera_frame.setLineWidth(0)
        self.camera_frame.setObjectName("camera_frame")
        self.gridLayout = QtWidgets.QGridLayout(self.camera_frame)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.camera_exposure_spinbox = QtWidgets.QSpinBox(self.camera_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.camera_exposure_spinbox.sizePolicy().hasHeightForWidth())
        self.camera_exposure_spinbox.setSizePolicy(sizePolicy)
        self.camera_exposure_spinbox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.camera_exposure_spinbox.setObjectName("camera_exposure_spinbox")
        self.gridLayout.addWidget(self.camera_exposure_spinbox, 1, 1, 1, 1)
        self.camera_filter_label = QtWidgets.QLabel(self.camera_frame)
        self.camera_filter_label.setObjectName("camera_filter_label")
        self.gridLayout.addWidget(self.camera_filter_label, 6, 0, 1, 1)
        self.camera_gain_spinbox = QtWidgets.QSpinBox(self.camera_frame)
        self.camera_gain_spinbox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.camera_gain_spinbox.setObjectName("camera_gain_spinbox")
        self.gridLayout.addWidget(self.camera_gain_spinbox, 3, 1, 1, 1)
        self.camera_format_combobox = QtWidgets.QComboBox(self.camera_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.camera_format_combobox.sizePolicy().hasHeightForWidth())
        self.camera_format_combobox.setSizePolicy(sizePolicy)
        self.camera_format_combobox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.camera_format_combobox.setObjectName("camera_format_combobox")
        self.gridLayout.addWidget(self.camera_format_combobox, 7, 1, 1, 1)
        self.camera_gain_label = QtWidgets.QLabel(self.camera_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.camera_gain_label.sizePolicy().hasHeightForWidth())
        self.camera_gain_label.setSizePolicy(sizePolicy)
        self.camera_gain_label.setObjectName("camera_gain_label")
        self.gridLayout.addWidget(self.camera_gain_label, 3, 0, 1, 1)
        self.line_4 = QtWidgets.QFrame(self.camera_frame)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout.addWidget(self.line_4, 0, 0, 1, 2)
        self.camera_exposure_slider = QtWidgets.QSlider(self.camera_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.camera_exposure_slider.sizePolicy().hasHeightForWidth())
        self.camera_exposure_slider.setSizePolicy(sizePolicy)
        self.camera_exposure_slider.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.camera_exposure_slider.setOrientation(QtCore.Qt.Horizontal)
        self.camera_exposure_slider.setObjectName("camera_exposure_slider")
        self.gridLayout.addWidget(self.camera_exposure_slider, 2, 0, 1, 2)
        self.horizontallayout_8 = QtWidgets.QHBoxLayout()
        self.horizontallayout_8.setObjectName("horizontallayout_8")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontallayout_8.addItem(spacerItem1)
        self.camera_loop_button = QtWidgets.QPushButton(self.camera_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.camera_loop_button.sizePolicy().hasHeightForWidth())
        self.camera_loop_button.setSizePolicy(sizePolicy)
        self.camera_loop_button.setIcon(icon12)
        self.camera_loop_button.setIconSize(QtCore.QSize(32, 32))
        self.camera_loop_button.setCheckable(True)
        self.camera_loop_button.setAutoDefault(True)
        self.camera_loop_button.setObjectName("camera_loop_button")
        self.horizontallayout_8.addWidget(self.camera_loop_button)
        self.camera_capture_button = QtWidgets.QPushButton(self.camera_frame)
        self.camera_capture_button.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.camera_capture_button.sizePolicy().hasHeightForWidth())
        self.camera_capture_button.setSizePolicy(sizePolicy)
        self.camera_capture_button.setIcon(icon13)
        self.camera_capture_button.setIconSize(QtCore.QSize(32, 32))
        self.camera_capture_button.setCheckable(True)
        self.camera_capture_button.setAutoDefault(True)
        self.camera_capture_button.setObjectName("camera_capture_button")
        self.horizontallayout_8.addWidget(self.camera_capture_button)
        self.gridLayout.addLayout(self.horizontallayout_8, 8, 0, 1, 2)
        self.camera_filter_combobox = QtWidgets.QComboBox(self.camera_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.camera_filter_combobox.sizePolicy().hasHeightForWidth())
        self.camera_filter_combobox.setSizePolicy(sizePolicy)
        self.camera_filter_combobox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.camera_filter_combobox.setObjectName("camera_filter_combobox")
        self.gridLayout.addWidget(self.camera_filter_combobox, 6, 1, 1, 1)
        self.camera_exposure_label = QtWidgets.QLabel(self.camera_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.camera_exposure_label.sizePolicy().hasHeightForWidth())
        self.camera_exposure_label.setSizePolicy(sizePolicy)
        self.camera_exposure_label.setObjectName("camera_exposure_label")
        self.gridLayout.addWidget(self.camera_exposure_label, 1, 0, 1, 1)
        self.camera_gain_slider = QtWidgets.QSlider(self.camera_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.camera_gain_slider.sizePolicy().hasHeightForWidth())
        self.camera_gain_slider.setSizePolicy(sizePolicy)
        self.camera_gain_slider.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.camera_gain_slider.setOrientation(QtCore.Qt.Horizontal)
        self.camera_gain_slider.setObjectName("camera_gain_slider")
        self.gridLayout.addWidget(self.camera_gain_slider, 4, 0, 1, 2)
        self.camera_integration_label = QtWidgets.QLabel(self.camera_frame)
        self.camera_integration_label.setObjectName("camera_integration_label")
        self.gridLayout.addWidget(self.camera_integration_label, 5, 0, 1, 1)
        self.camera_format_label = QtWidgets.QLabel(self.camera_frame)
        self.camera_format_label.setObjectName("camera_format_label")
        self.gridLayout.addWidget(self.camera_format_label, 7, 0, 1, 1)
        self.camera_integration_spinbox = QtWidgets.QSpinBox(self.camera_frame)
        self.camera_integration_spinbox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.camera_integration_spinbox.setObjectName("camera_integration_spinbox")
        self.gridLayout.addWidget(self.camera_integration_spinbox, 5, 1, 1, 1)
        self.formLayout_8.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.camera_frame)
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.camera_group)
        self.wheel_group = QtWidgets.QGroupBox(self.scroll_area_widget_contents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wheel_group.sizePolicy().hasHeightForWidth())
        self.wheel_group.setSizePolicy(sizePolicy)
        self.wheel_group.setCheckable(True)
        self.wheel_group.setChecked(False)
        self.wheel_group.setObjectName("wheel_group")
        self.formLayout = QtWidgets.QFormLayout(self.wheel_group)
        self.formLayout.setObjectName("formLayout")
        self.horizontallayout_13 = QtWidgets.QHBoxLayout()
        self.horizontallayout_13.setObjectName("horizontallayout_13")
        self.wheel_name_label = QtWidgets.QLabel(self.wheel_group)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wheel_name_label.sizePolicy().hasHeightForWidth())
        self.wheel_name_label.setSizePolicy(sizePolicy)
        self.wheel_name_label.setWordWrap(True)
        self.wheel_name_label.setObjectName("wheel_name_label")
        self.horizontallayout_13.addWidget(self.wheel_name_label)
        self.wheel_settings_btn = QtWidgets.QToolButton(self.wheel_group)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wheel_settings_btn.sizePolicy().hasHeightForWidth())
        self.wheel_settings_btn.setSizePolicy(sizePolicy)
        self.wheel_settings_btn.setText("")
        self.wheel_settings_btn.setIcon(icon1)
        self.wheel_settings_btn.setPopupMode(QtWidgets.QToolButton.InstantPopup)
        self.wheel_settings_btn.setObjectName("wheel_settings_btn")
        self.horizontallayout_13.addWidget(self.wheel_settings_btn)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.SpanningRole, self.horizontallayout_13)
        self.wheel_frame = QtWidgets.QFrame(self.wheel_group)
        self.wheel_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.wheel_frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.wheel_frame.setLineWidth(0)
        self.wheel_frame.setObjectName("wheel_frame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.wheel_frame)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.position_label = QtWidgets.QLabel(self.wheel_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.position_label.sizePolicy().hasHeightForWidth())
        self.position_label.setSizePolicy(sizePolicy)
        self.position_label.setObjectName("position_label")
        self.gridLayout_3.addWidget(self.position_label, 1, 0, 1, 1)
        self.position_combobox = QtWidgets.QComboBox(self.wheel_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.position_combobox.sizePolicy().hasHeightForWidth())
        self.position_combobox.setSizePolicy(sizePolicy)
        self.position_combobox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.position_combobox.setEditable(True)
        self.position_combobox.setInsertPolicy(QtWidgets.QComboBox.NoInsert)
        self.position_combobox.setObjectName("position_combobox")
        self.gridLayout_3.addWidget(self.position_combobox, 1, 1, 1, 1)
        self.line_6 = QtWidgets.QFrame(self.wheel_frame)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.gridLayout_3.addWidget(self.line_6, 0, 0, 1, 2)
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.wheel_frame)
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.SpanningRole, self.wheel_group)
        self.focuser_group = QtWidgets.QGroupBox(self.scroll_area_widget_contents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.focuser_group.sizePolicy().hasHeightForWidth())
        self.focuser_group.setSizePolicy(sizePolicy)
        self.focuser_group.setCheckable(True)
        self.focuser_group.setChecked(False)
        self.focuser_group.setObjectName("focuser_group")
        self.formLayout_9 = QtWidgets.QFormLayout(self.focuser_group)
        self.formLayout_9.setObjectName("formLayout_9")
        self.horizontallayout_12 = QtWidgets.QHBoxLayout()
        self.horizontallayout_12.setObjectName("horizontallayout_12")
        self.focuser_name_label = QtWidgets.QLabel(self.focuser_group)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.focuser_name_label.sizePolicy().hasHeightForWidth())
        self.focuser_name_label.setSizePolicy(sizePolicy)
        self.focuser_name_label.setWordWrap(True)
        self.focuser_name_label.setObjectName("focuser_name_label")
        self.horizontallayout_12.addWidget(self.focuser_name_label)
        self.focuser_settings_btn = QtWidgets.QToolButton(self.focuser_group)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.focuser_settings_btn.sizePolicy().hasHeightForWidth())
        self.focuser_settings_btn.setSizePolicy(sizePolicy)
        self.focuser_settings_btn.setText("")
        self.focuser_settings_btn.setIcon(icon1)
        self.focuser_settings_btn.setPopupMode(QtWidgets.QToolButton.InstantPopup)
        self.focuser_settings_btn.setObjectName("focuser_settings_btn")
        self.horizontallayout_12.addWidget(self.focuser_settings_btn)
        self.formLayout_9.setLayout(0, QtWidgets.QFormLayout.SpanningRole, self.horizontallayout_12)
        self.focuser_frame = QtWidgets.QFrame(self.focuser_group)
        self.focuser_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.focuser_frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.focuser_frame.setLineWidth(0)
        self.focuser_frame.setObjectName("focuser_frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.focuser_frame)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.focuser_position_spinbox = QtWidgets.QSpinBox(self.focuser_frame)
        self.focuser_position_spinbox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.focuser_position_spinbox.setObjectName("focuser_position_spinbox")
        self.gridLayout_2.addWidget(self.focuser_position_spinbox, 1, 1, 1, 1)
        self.focuser_position_label = QtWidgets.QLabel(self.focuser_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.focuser_position_label.sizePolicy().hasHeightForWidth())
        self.focuser_position_label.setSizePolicy(sizePolicy)
        self.focuser_position_label.setObjectName("focuser_position_label")
        self.gridLayout_2.addWidget(self.focuser_position_label, 1, 0, 1, 1)
        self.line_5 = QtWidgets.QFrame(self.focuser_frame)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.gridLayout_2.addWidget(self.line_5, 0, 0, 1, 2)
        self.temp_checkbox = QtWidgets.QCheckBox(self.focuser_frame)
        self.temp_checkbox.setObjectName("temp_checkbox")
        self.gridLayout_2.addWidget(self.temp_checkbox, 2, 0, 1, 2)
        self.formLayout_9.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.focuser_frame)
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.SpanningRole, self.focuser_group)
        self.scrollarea.setWidget(self.scroll_area_widget_contents)
        self.horizontalLayout_2.addWidget(self.scrollarea)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 795, 18))
        self.menubar.setObjectName("menubar")
        self.file_menu = QtWidgets.QMenu(self.menubar)
        self.file_menu.setObjectName("file_menu")
        self.import_menu = QtWidgets.QMenu(self.file_menu)
        self.import_menu.setObjectName("import_menu")
        self.menuExport = QtWidgets.QMenu(self.file_menu)
        self.menuExport.setObjectName("menuExport")
        self.menu_edit = QtWidgets.QMenu(self.menubar)
        self.menu_edit.setObjectName("menu_edit")
        self.menu_equipment = QtWidgets.QMenu(self.menu_edit)
        self.menu_equipment.setObjectName("menu_equipment")
        self.help_menu = QtWidgets.QMenu(self.menubar)
        self.help_menu.setObjectName("help_menu")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        MainWindow.setMenuBar(self.menubar)
        self.schedule_dockwidget = QtWidgets.QDockWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.schedule_dockwidget.sizePolicy().hasHeightForWidth())
        self.schedule_dockwidget.setSizePolicy(sizePolicy)
        self.schedule_dockwidget.setFeatures(QtWidgets.QDockWidget.DockWidgetFloatable|QtWidgets.QDockWidget.DockWidgetMovable)
        self.schedule_dockwidget.setAllowedAreas(QtCore.Qt.LeftDockWidgetArea|QtCore.Qt.RightDockWidgetArea)
        self.schedule_dockwidget.setObjectName("schedule_dockwidget")
        self.dockwidget_contents = QtWidgets.QWidget()
        self.dockwidget_contents.setObjectName("dockwidget_contents")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.dockwidget_contents)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, -1)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.schedule_table = QtWidgets.QTableWidget(self.dockwidget_contents)
        self.schedule_table.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.schedule_table.setObjectName("schedule_table")
        self.schedule_table.setColumnCount(6)
        self.schedule_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.schedule_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.schedule_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.schedule_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.schedule_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.schedule_table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.schedule_table.setHorizontalHeaderItem(5, item)
        self.schedule_table.horizontalHeader().setCascadingSectionResizes(True)
        self.schedule_table.verticalHeader().setCascadingSectionResizes(True)
        self.verticalLayout_7.addWidget(self.schedule_table)
        self.horizontallayout = QtWidgets.QHBoxLayout()
        self.horizontallayout.setContentsMargins(9, -1, 9, -1)
        self.horizontallayout.setObjectName("horizontallayout")
        self.addrow_button = QtWidgets.QPushButton(self.dockwidget_contents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addrow_button.sizePolicy().hasHeightForWidth())
        self.addrow_button.setSizePolicy(sizePolicy)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/icons/ic_add_white_48px.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addrow_button.setIcon(icon14)
        self.addrow_button.setAutoDefault(True)
        self.addrow_button.setObjectName("addrow_button")
        self.horizontallayout.addWidget(self.addrow_button)
        self.removerow_button = QtWidgets.QPushButton(self.dockwidget_contents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.removerow_button.sizePolicy().hasHeightForWidth())
        self.removerow_button.setSizePolicy(sizePolicy)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/icons/ic_remove_white_48px.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.removerow_button.setIcon(icon15)
        self.removerow_button.setAutoDefault(True)
        self.removerow_button.setObjectName("removerow_button")
        self.horizontallayout.addWidget(self.removerow_button)
        self.line_7 = QtWidgets.QFrame(self.dockwidget_contents)
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.horizontallayout.addWidget(self.line_7)
        self.schedule_date_label = QtWidgets.QLabel(self.dockwidget_contents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.schedule_date_label.sizePolicy().hasHeightForWidth())
        self.schedule_date_label.setSizePolicy(sizePolicy)
        self.schedule_date_label.setObjectName("schedule_date_label")
        self.horizontallayout.addWidget(self.schedule_date_label)
        self.schedule_dateedit = QtWidgets.QDateEdit(self.dockwidget_contents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.schedule_dateedit.sizePolicy().hasHeightForWidth())
        self.schedule_dateedit.setSizePolicy(sizePolicy)
        self.schedule_dateedit.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.schedule_dateedit.setCurrentSection(QtWidgets.QDateTimeEdit.DaySection)
        self.schedule_dateedit.setCalendarPopup(False)
        self.schedule_dateedit.setCurrentSectionIndex(2)
        self.schedule_dateedit.setObjectName("schedule_dateedit")
        self.horizontallayout.addWidget(self.schedule_dateedit)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontallayout.addItem(spacerItem2)
        self.changes_label = QtWidgets.QLabel(self.dockwidget_contents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.changes_label.sizePolicy().hasHeightForWidth())
        self.changes_label.setSizePolicy(sizePolicy)
        self.changes_label.setAlignment(QtCore.Qt.AlignCenter)
        self.changes_label.setObjectName("changes_label")
        self.horizontallayout.addWidget(self.changes_label)
        self.verticalLayout_7.addLayout(self.horizontallayout)
        self.schedule_dockwidget.setWidget(self.dockwidget_contents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.schedule_dockwidget)
        self.camera_dockwidget = QtWidgets.QDockWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.camera_dockwidget.sizePolicy().hasHeightForWidth())
        self.camera_dockwidget.setSizePolicy(sizePolicy)
        self.camera_dockwidget.setFeatures(QtWidgets.QDockWidget.DockWidgetFloatable|QtWidgets.QDockWidget.DockWidgetMovable)
        self.camera_dockwidget.setAllowedAreas(QtCore.Qt.LeftDockWidgetArea|QtCore.Qt.RightDockWidgetArea)
        self.camera_dockwidget.setObjectName("camera_dockwidget")
        self.dockwidgetcontents_2 = QtWidgets.QWidget()
        self.dockwidgetcontents_2.setObjectName("dockwidgetcontents_2")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.dockwidgetcontents_2)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, -1)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.camera_scrollarea = QtWidgets.QScrollArea(self.dockwidgetcontents_2)
        self.camera_scrollarea.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.camera_scrollarea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.camera_scrollarea.setFrameShadow(QtWidgets.QFrame.Plain)
        self.camera_scrollarea.setLineWidth(0)
        self.camera_scrollarea.setWidgetResizable(True)
        self.camera_scrollarea.setAlignment(QtCore.Qt.AlignCenter)
        self.camera_scrollarea.setObjectName("camera_scrollarea")
        self.camera_scrollarea_contents = QtWidgets.QWidget()
        self.camera_scrollarea_contents.setGeometry(QtCore.QRect(0, 0, 605, 52))
        self.camera_scrollarea_contents.setObjectName("camera_scrollarea_contents")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.camera_scrollarea_contents)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.camera_preview_label = QtWidgets.QLabel(self.camera_scrollarea_contents)
        self.camera_preview_label.setText("")
        self.camera_preview_label.setAlignment(QtCore.Qt.AlignCenter)
        self.camera_preview_label.setObjectName("camera_preview_label")
        self.verticalLayout_4.addWidget(self.camera_preview_label)
        self.camera_scrollarea.setWidget(self.camera_scrollarea_contents)
        self.verticalLayout_9.addWidget(self.camera_scrollarea)
        self.horizontallayout_3 = QtWidgets.QHBoxLayout()
        self.horizontallayout_3.setContentsMargins(9, -1, 9, -1)
        self.horizontallayout_3.setObjectName("horizontallayout_3")
        self.camera_zoom_label = QtWidgets.QLabel(self.dockwidgetcontents_2)
        self.camera_zoom_label.setObjectName("camera_zoom_label")
        self.horizontallayout_3.addWidget(self.camera_zoom_label)
        self.camera_zoom_slider = QtWidgets.QSlider(self.dockwidgetcontents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.camera_zoom_slider.sizePolicy().hasHeightForWidth())
        self.camera_zoom_slider.setSizePolicy(sizePolicy)
        self.camera_zoom_slider.setMinimum(20)
        self.camera_zoom_slider.setMaximum(200)
        self.camera_zoom_slider.setProperty("value", 100)
        self.camera_zoom_slider.setOrientation(QtCore.Qt.Horizontal)
        self.camera_zoom_slider.setObjectName("camera_zoom_slider")
        self.horizontallayout_3.addWidget(self.camera_zoom_slider)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontallayout_3.addItem(spacerItem3)
        self.verticalLayout_9.addLayout(self.horizontallayout_3)
        self.camera_dockwidget.setWidget(self.dockwidgetcontents_2)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.camera_dockwidget)
        self.autoguide_dockwidget = QtWidgets.QDockWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.autoguide_dockwidget.sizePolicy().hasHeightForWidth())
        self.autoguide_dockwidget.setSizePolicy(sizePolicy)
        self.autoguide_dockwidget.setFeatures(QtWidgets.QDockWidget.DockWidgetFloatable|QtWidgets.QDockWidget.DockWidgetMovable)
        self.autoguide_dockwidget.setAllowedAreas(QtCore.Qt.LeftDockWidgetArea|QtCore.Qt.RightDockWidgetArea)
        self.autoguide_dockwidget.setObjectName("autoguide_dockwidget")
        self.dockwidgetcontents_3 = QtWidgets.QWidget()
        self.dockwidgetcontents_3.setObjectName("dockwidgetcontents_3")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.dockwidgetcontents_3)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, -1)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.guider_scrollarea = QtWidgets.QScrollArea(self.dockwidgetcontents_3)
        self.guider_scrollarea.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.guider_scrollarea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.guider_scrollarea.setFrameShadow(QtWidgets.QFrame.Plain)
        self.guider_scrollarea.setLineWidth(0)
        self.guider_scrollarea.setWidgetResizable(True)
        self.guider_scrollarea.setAlignment(QtCore.Qt.AlignCenter)
        self.guider_scrollarea.setObjectName("guider_scrollarea")
        self.scrollareawidgetcontents_3 = QtWidgets.QWidget()
        self.scrollareawidgetcontents_3.setGeometry(QtCore.QRect(0, 0, 605, 52))
        self.scrollareawidgetcontents_3.setObjectName("scrollareawidgetcontents_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.scrollareawidgetcontents_3)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.guide_preview_label = QtWidgets.QLabel(self.scrollareawidgetcontents_3)
        self.guide_preview_label.setText("")
        self.guide_preview_label.setAlignment(QtCore.Qt.AlignCenter)
        self.guide_preview_label.setObjectName("guide_preview_label")
        self.verticalLayout_6.addWidget(self.guide_preview_label)
        self.guider_scrollarea.setWidget(self.scrollareawidgetcontents_3)
        self.verticalLayout_10.addWidget(self.guider_scrollarea)
        self.horizontallayout_6 = QtWidgets.QHBoxLayout()
        self.horizontallayout_6.setContentsMargins(9, -1, 9, -1)
        self.horizontallayout_6.setObjectName("horizontallayout_6")
        self.camera_zoom_label_2 = QtWidgets.QLabel(self.dockwidgetcontents_3)
        self.camera_zoom_label_2.setObjectName("camera_zoom_label_2")
        self.horizontallayout_6.addWidget(self.camera_zoom_label_2)
        self.camera_zoom_slider_2 = QtWidgets.QSlider(self.dockwidgetcontents_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.camera_zoom_slider_2.sizePolicy().hasHeightForWidth())
        self.camera_zoom_slider_2.setSizePolicy(sizePolicy)
        self.camera_zoom_slider_2.setMinimum(20)
        self.camera_zoom_slider_2.setMaximum(200)
        self.camera_zoom_slider_2.setProperty("value", 100)
        self.camera_zoom_slider_2.setOrientation(QtCore.Qt.Horizontal)
        self.camera_zoom_slider_2.setObjectName("camera_zoom_slider_2")
        self.horizontallayout_6.addWidget(self.camera_zoom_slider_2)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontallayout_6.addItem(spacerItem4)
        self.verticalLayout_10.addLayout(self.horizontallayout_6)
        self.autoguide_dockwidget.setWidget(self.dockwidgetcontents_3)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.autoguide_dockwidget)
        self.filters_dockwidget = QtWidgets.QDockWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filters_dockwidget.sizePolicy().hasHeightForWidth())
        self.filters_dockwidget.setSizePolicy(sizePolicy)
        self.filters_dockwidget.setFeatures(QtWidgets.QDockWidget.DockWidgetFloatable|QtWidgets.QDockWidget.DockWidgetMovable)
        self.filters_dockwidget.setAllowedAreas(QtCore.Qt.LeftDockWidgetArea|QtCore.Qt.RightDockWidgetArea)
        self.filters_dockwidget.setObjectName("filters_dockwidget")
        self.filters_dockwidgetcontents = QtWidgets.QWidget()
        self.filters_dockwidgetcontents.setObjectName("filters_dockwidgetcontents")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.filters_dockwidgetcontents)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, -1)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.filter_table = QtWidgets.QTableWidget(self.filters_dockwidgetcontents)
        self.filter_table.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.filter_table.setLineWidth(0)
        self.filter_table.setObjectName("filter_table")
        self.filter_table.setColumnCount(5)
        self.filter_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.filter_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.filter_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.filter_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.filter_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.filter_table.setHorizontalHeaderItem(4, item)
        self.verticalLayout_5.addWidget(self.filter_table)
        self.horizontallayout_14 = QtWidgets.QHBoxLayout()
        self.horizontallayout_14.setContentsMargins(9, -1, 9, -1)
        self.horizontallayout_14.setObjectName("horizontallayout_14")
        self.addrow_button_2 = QtWidgets.QPushButton(self.filters_dockwidgetcontents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addrow_button_2.sizePolicy().hasHeightForWidth())
        self.addrow_button_2.setSizePolicy(sizePolicy)
        self.addrow_button_2.setIcon(icon14)
        self.addrow_button_2.setAutoDefault(True)
        self.addrow_button_2.setObjectName("addrow_button_2")
        self.horizontallayout_14.addWidget(self.addrow_button_2)
        self.removerow_button_2 = QtWidgets.QPushButton(self.filters_dockwidgetcontents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.removerow_button_2.sizePolicy().hasHeightForWidth())
        self.removerow_button_2.setSizePolicy(sizePolicy)
        self.removerow_button_2.setIcon(icon15)
        self.removerow_button_2.setAutoDefault(True)
        self.removerow_button_2.setObjectName("removerow_button_2")
        self.horizontallayout_14.addWidget(self.removerow_button_2)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontallayout_14.addItem(spacerItem5)
        self.changes_label_2 = QtWidgets.QLabel(self.filters_dockwidgetcontents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.changes_label_2.sizePolicy().hasHeightForWidth())
        self.changes_label_2.setSizePolicy(sizePolicy)
        self.changes_label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.changes_label_2.setObjectName("changes_label_2")
        self.horizontallayout_14.addWidget(self.changes_label_2)
        self.verticalLayout_5.addLayout(self.horizontallayout_14)
        self.filters_dockwidget.setWidget(self.filters_dockwidgetcontents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.filters_dockwidget)
        self.exit_action = QtWidgets.QAction(MainWindow)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(":/icons/ic_power_settings_new_white_48px.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exit_action.setIcon(icon16)
        self.exit_action.setObjectName("exit_action")
        self.filters_action = QtWidgets.QAction(MainWindow)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(":/icons/ic_tonality_white_48px.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.filters_action.setIcon(icon17)
        self.filters_action.setObjectName("filters_action")
        self.location_action = QtWidgets.QAction(MainWindow)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(":/icons/ic_location_on_white_48px.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.location_action.setIcon(icon18)
        self.location_action.setObjectName("location_action")
        self.targets_action = QtWidgets.QAction(MainWindow)
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap(":/icons/ic_center_focus_strong_white_48px.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.targets_action.setIcon(icon19)
        self.targets_action.setObjectName("targets_action")
        self.action_undo = QtWidgets.QAction(MainWindow)
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap(":/icons/ic_undo_white_48px.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_undo.setIcon(icon20)
        self.action_undo.setObjectName("action_undo")
        self.action_redo = QtWidgets.QAction(MainWindow)
        icon21 = QtGui.QIcon()
        icon21.addPixmap(QtGui.QPixmap(":/icons/ic_redo_white_48px.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_redo.setIcon(icon21)
        self.action_redo.setObjectName("action_redo")
        self.action_about = QtWidgets.QAction(MainWindow)
        icon22 = QtGui.QIcon()
        icon22.addPixmap(QtGui.QPixmap(":/icons/ic_info_white_48px.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_about.setIcon(icon22)
        self.action_about.setObjectName("action_about")
        self.telescope_action = QtWidgets.QAction(MainWindow)
        self.telescope_action.setCheckable(True)
        self.telescope_action.setObjectName("telescope_action")
        self.guide_action = QtWidgets.QAction(MainWindow)
        self.guide_action.setCheckable(True)
        self.guide_action.setObjectName("guide_action")
        self.camera_action = QtWidgets.QAction(MainWindow)
        self.camera_action.setCheckable(True)
        self.camera_action.setObjectName("camera_action")
        self.focuser_action = QtWidgets.QAction(MainWindow)
        self.focuser_action.setCheckable(True)
        self.focuser_action.setObjectName("focuser_action")
        self.wheel_action = QtWidgets.QAction(MainWindow)
        self.wheel_action.setCheckable(True)
        self.wheel_action.setObjectName("wheel_action")
        self.importschedule_action = QtWidgets.QAction(MainWindow)
        self.importschedule_action.setObjectName("importschedule_action")
        self.importfilters_action = QtWidgets.QAction(MainWindow)
        self.importfilters_action.setObjectName("importfilters_action")
        self.actionSave_Location = QtWidgets.QAction(MainWindow)
        icon23 = QtGui.QIcon()
        icon23.addPixmap(QtGui.QPixmap(":/icons/ic_folder_white_48px.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave_Location.setIcon(icon23)
        self.actionSave_Location.setObjectName("actionSave_Location")
        self.action_closewindow = QtWidgets.QAction(MainWindow)
        icon24 = QtGui.QIcon()
        icon24.addPixmap(QtGui.QPixmap(":/icons/ic_close_white_48px.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_closewindow.setIcon(icon24)
        self.action_closewindow.setObjectName("action_closewindow")
        self.actionFilters = QtWidgets.QAction(MainWindow)
        self.actionFilters.setObjectName("actionFilters")
        self.actionSchedule = QtWidgets.QAction(MainWindow)
        self.actionSchedule.setObjectName("actionSchedule")
        self.import_menu.addAction(self.importfilters_action)
        self.import_menu.addAction(self.importschedule_action)
        self.menuExport.addAction(self.actionFilters)
        self.menuExport.addAction(self.actionSchedule)
        self.file_menu.addAction(self.import_menu.menuAction())
        self.file_menu.addAction(self.menuExport.menuAction())
        self.file_menu.addSeparator()
        self.file_menu.addAction(self.action_closewindow)
        self.file_menu.addAction(self.exit_action)
        self.menu_equipment.addAction(self.telescope_action)
        self.menu_equipment.addAction(self.guide_action)
        self.menu_equipment.addAction(self.camera_action)
        self.menu_equipment.addAction(self.wheel_action)
        self.menu_equipment.addAction(self.focuser_action)
        self.menu_edit.addAction(self.menu_equipment.menuAction())
        self.menu_edit.addAction(self.filters_action)
        self.menu_edit.addAction(self.location_action)
        self.menu_edit.addAction(self.actionSave_Location)
        self.help_menu.addAction(self.action_about)
        self.menuView.addAction(self.targets_action)
        self.menubar.addAction(self.file_menu.menuAction())
        self.menubar.addAction(self.menu_edit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.help_menu.menuAction())

        self.retranslateUi(MainWindow)
        self.guider_exposure_slider.valueChanged['int'].connect(self.guider_exposure_spinbox.setValue)
        self.guider_gain_slider.valueChanged['int'].connect(self.guider_gain_spinbox.setValue)
        self.camera_gain_slider.valueChanged['int'].connect(self.camera_gain_spinbox.setValue)
        self.camera_exposure_slider.valueChanged['int'].connect(self.camera_exposure_spinbox.setValue)
        self.guider_exposure_spinbox.valueChanged['int'].connect(self.guider_exposure_slider.setValue)
        self.camera_gain_spinbox.valueChanged['int'].connect(self.camera_gain_slider.setValue)
        self.guider_gain_spinbox.valueChanged['int'].connect(self.guider_gain_slider.setValue)
        self.camera_exposure_spinbox.valueChanged['int'].connect(self.camera_exposure_slider.setValue)
        self.camera_capture_button.clicked.connect(self.camera_dockwidget.raise_)
        self.camera_loop_button.clicked.connect(self.camera_dockwidget.raise_)
        self.guider_start_button.clicked.connect(self.autoguide_dockwidget.raise_)
        self.guider_loop_button.clicked.connect(self.autoguide_dockwidget.raise_)
        self.guider_exposure_spinbox.valueChanged['int'].connect(self.autoguide_dockwidget.raise_)
        self.guider_gain_spinbox.valueChanged['int'].connect(self.autoguide_dockwidget.raise_)
        self.camera_exposure_spinbox.valueChanged['int'].connect(self.camera_dockwidget.raise_)
        self.camera_gain_spinbox.valueChanged['int'].connect(self.camera_dockwidget.raise_)
        self.guider_loop_button.toggled['bool'].connect(self.guider_start_button.setEnabled)
        self.camera_loop_button.toggled['bool'].connect(self.camera_capture_button.setEnabled)
        self.mount_group.toggled['bool'].connect(self.telescope_action.setChecked)
        self.autoguide_group.toggled['bool'].connect(self.guide_action.setChecked)
        self.camera_group.toggled['bool'].connect(self.camera_action.setChecked)
        self.focuser_group.toggled['bool'].connect(self.focuser_action.setChecked)
        self.wheel_group.toggled['bool'].connect(self.wheel_action.setChecked)
        self.telescope_action.toggled['bool'].connect(self.mount_group.setChecked)
        self.guide_action.toggled['bool'].connect(self.autoguide_group.setChecked)
        self.wheel_action.toggled['bool'].connect(self.wheel_group.setChecked)
        self.camera_action.toggled['bool'].connect(self.camera_group.setChecked)
        self.focuser_action.toggled['bool'].connect(self.focuser_group.setChecked)
        self.guider_loop_button.toggled['bool'].connect(self.guide_settings_btn.setDisabled)
        self.camera_loop_button.toggled['bool'].connect(self.camera_settings_btn.setDisabled)
        self.filters_action.triggered.connect(self.filters_dockwidget.raise_)
        self.camera_action.toggled['bool'].connect(self.camera_dockwidget.raise_)
        self.action_closewindow.triggered.connect(MainWindow.close)
        self.camera_capture_button.toggled['bool'].connect(self.camera_loop_button.setDisabled)
        self.guider_start_button.toggled['bool'].connect(self.guider_loop_button.setDisabled)
        self.camera_capture_button.toggled['bool'].connect(self.camera_filter_combobox.setDisabled)
        self.camera_capture_button.toggled['bool'].connect(self.camera_filter_label.setDisabled)
        self.camera_capture_button.toggled['bool'].connect(self.camera_format_label.setDisabled)
        self.camera_capture_button.toggled['bool'].connect(self.camera_format_combobox.setDisabled)
        self.wheel_group.toggled['bool'].connect(self.camera_filter_label.setHidden)
        self.wheel_group.toggled['bool'].connect(self.camera_filter_combobox.setHidden)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.mount_group, self.scrollarea)
        MainWindow.setTabOrder(self.scrollarea, self.scope_settings_btn)
        MainWindow.setTabOrder(self.scope_settings_btn, self.slewnorthwest_button)
        MainWindow.setTabOrder(self.slewnorthwest_button, self.slewnorth_button)
        MainWindow.setTabOrder(self.slewnorth_button, self.slewnortheast_button)
        MainWindow.setTabOrder(self.slewnortheast_button, self.slewwest_button)
        MainWindow.setTabOrder(self.slewwest_button, self.slewstop_button)
        MainWindow.setTabOrder(self.slewstop_button, self.sleweast_button)
        MainWindow.setTabOrder(self.sleweast_button, self.slewsouthwest_button)
        MainWindow.setTabOrder(self.slewsouthwest_button, self.slewsouth_button)
        MainWindow.setTabOrder(self.slewsouth_button, self.slewsoutheast_button)
        MainWindow.setTabOrder(self.slewsoutheast_button, self.mount_trackrate_spin)
        MainWindow.setTabOrder(self.mount_trackrate_spin, self.object_combobox)
        MainWindow.setTabOrder(self.object_combobox, self.goto_button)
        MainWindow.setTabOrder(self.goto_button, self.autoguide_group)
        MainWindow.setTabOrder(self.autoguide_group, self.guide_settings_btn)
        MainWindow.setTabOrder(self.guide_settings_btn, self.guider_exposure_spinbox)
        MainWindow.setTabOrder(self.guider_exposure_spinbox, self.guider_exposure_slider)
        MainWindow.setTabOrder(self.guider_exposure_slider, self.guider_gain_spinbox)
        MainWindow.setTabOrder(self.guider_gain_spinbox, self.guider_gain_slider)
        MainWindow.setTabOrder(self.guider_gain_slider, self.guider_loop_button)
        MainWindow.setTabOrder(self.guider_loop_button, self.guider_start_button)
        MainWindow.setTabOrder(self.guider_start_button, self.camera_group)
        MainWindow.setTabOrder(self.camera_group, self.camera_settings_btn)
        MainWindow.setTabOrder(self.camera_settings_btn, self.camera_exposure_spinbox)
        MainWindow.setTabOrder(self.camera_exposure_spinbox, self.camera_exposure_slider)
        MainWindow.setTabOrder(self.camera_exposure_slider, self.camera_gain_spinbox)
        MainWindow.setTabOrder(self.camera_gain_spinbox, self.camera_gain_slider)
        MainWindow.setTabOrder(self.camera_gain_slider, self.camera_integration_spinbox)
        MainWindow.setTabOrder(self.camera_integration_spinbox, self.camera_format_combobox)
        MainWindow.setTabOrder(self.camera_format_combobox, self.camera_loop_button)
        MainWindow.setTabOrder(self.camera_loop_button, self.camera_capture_button)
        MainWindow.setTabOrder(self.camera_capture_button, self.focuser_group)
        MainWindow.setTabOrder(self.focuser_group, self.focuser_settings_btn)
        MainWindow.setTabOrder(self.focuser_settings_btn, self.focuser_position_spinbox)
        MainWindow.setTabOrder(self.focuser_position_spinbox, self.temp_checkbox)
        MainWindow.setTabOrder(self.temp_checkbox, self.wheel_settings_btn)
        MainWindow.setTabOrder(self.wheel_settings_btn, self.position_combobox)
        MainWindow.setTabOrder(self.position_combobox, self.schedule_table)
        MainWindow.setTabOrder(self.schedule_table, self.addrow_button)
        MainWindow.setTabOrder(self.addrow_button, self.removerow_button)
        MainWindow.setTabOrder(self.removerow_button, self.camera_scrollarea)
        MainWindow.setTabOrder(self.camera_scrollarea, self.camera_zoom_slider)
        MainWindow.setTabOrder(self.camera_zoom_slider, self.guider_scrollarea)
        MainWindow.setTabOrder(self.guider_scrollarea, self.camera_zoom_slider_2)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Solar System Sequencer"))
        self.mount_group.setTitle(_translate("MainWindow", "Telescope"))
        self.telescope_name_label.setText(_translate("MainWindow", "Not Connected"))
        self.slewnorth_button.setToolTip(_translate("MainWindow", "Slew the mount north"))
        self.slewsouthwest_button.setToolTip(_translate("MainWindow", "Slew the mount west"))
        self.sleweast_button.setToolTip(_translate("MainWindow", "Slew the mount east"))
        self.slewnorthwest_button.setToolTip(_translate("MainWindow", "Slew the mount north"))
        self.slewsoutheast_button.setToolTip(_translate("MainWindow", "Slew the mount south"))
        self.slewstop_button.setToolTip(_translate("MainWindow", "Slew the mount west"))
        self.slewwest_button.setToolTip(_translate("MainWindow", "Slew the mount west"))
        self.slewsouth_button.setToolTip(_translate("MainWindow", "Slew the mount south"))
        self.slewnortheast_button.setToolTip(_translate("MainWindow", "Slew the mount east"))
        self.mount_trackrate_label.setText(_translate("MainWindow", "Rate"))
        self.mount_trackrate_spin.setPrefix(_translate("MainWindow", "~"))
        self.mount_trackrate_spin.setSuffix(_translate("MainWindow", "°/s"))
        self.object_label.setText(_translate("MainWindow", "Target"))
        self.goto_button.setToolTip(_translate("MainWindow", "Go to target"))
        self.autoguide_group.setTitle(_translate("MainWindow", "Autoguide"))
        self.guider_name_label.setText(_translate("MainWindow", "Not Connected"))
        self.guider_exposure_label.setText(_translate("MainWindow", "Exposure"))
        self.guider_exposure_spinbox.setSuffix(_translate("MainWindow", "ms"))
        self.guider_gain_label.setText(_translate("MainWindow", "Gain"))
        self.guider_gain_spinbox.setSuffix(_translate("MainWindow", "e/adu"))
        self.camera_group.setTitle(_translate("MainWindow", "Camera"))
        self.camera_name_label.setText(_translate("MainWindow", "Not Connected"))
        self.camera_exposure_spinbox.setSuffix(_translate("MainWindow", "ms"))
        self.camera_filter_label.setText(_translate("MainWindow", "Filter"))
        self.camera_gain_spinbox.setSuffix(_translate("MainWindow", "e/adu"))
        self.camera_gain_label.setText(_translate("MainWindow", "Gain"))
        self.camera_exposure_label.setText(_translate("MainWindow", "Exposure"))
        self.camera_integration_label.setText(_translate("MainWindow", "Integration"))
        self.camera_format_label.setText(_translate("MainWindow", "Format"))
        self.camera_integration_spinbox.setSuffix(_translate("MainWindow", "s"))
        self.wheel_group.setTitle(_translate("MainWindow", "Filter Wheel"))
        self.wheel_name_label.setText(_translate("MainWindow", "Not Connected"))
        self.position_label.setText(_translate("MainWindow", "Position"))
        self.focuser_group.setTitle(_translate("MainWindow", "Focuser"))
        self.focuser_name_label.setText(_translate("MainWindow", "Not Connected"))
        self.focuser_position_label.setText(_translate("MainWindow", "Position"))
        self.temp_checkbox.setText(_translate("MainWindow", "Temp Comp"))
        self.file_menu.setTitle(_translate("MainWindow", "File"))
        self.import_menu.setTitle(_translate("MainWindow", "Import"))
        self.menuExport.setTitle(_translate("MainWindow", "Export"))
        self.menu_edit.setTitle(_translate("MainWindow", "Edit"))
        self.menu_equipment.setTitle(_translate("MainWindow", "Equipment"))
        self.help_menu.setTitle(_translate("MainWindow", "Help"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.schedule_dockwidget.setWindowTitle(_translate("MainWindow", "Schedule"))
        item = self.schedule_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Time"))
        item.setToolTip(_translate("MainWindow", "Time to initiate the event."))
        item = self.schedule_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Target"))
        item.setToolTip(_translate("MainWindow", "The target to aim at."))
        item = self.schedule_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Filter"))
        item.setToolTip(_translate("MainWindow", "The filter to use"))
        item = self.schedule_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Exposure"))
        item.setToolTip(_translate("MainWindow", "How long to expose 1 frame"))
        item = self.schedule_table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Gain"))
        item.setToolTip(_translate("MainWindow", "The amount of gain to apply to an exposure"))
        item = self.schedule_table.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Integration"))
        item.setToolTip(_translate("MainWindow", "How long to capture frames per file"))
        self.addrow_button.setToolTip(_translate("MainWindow", "Add row"))
        self.removerow_button.setToolTip(_translate("MainWindow", "Remove row"))
        self.schedule_date_label.setText(_translate("MainWindow", "Date"))
        self.schedule_dateedit.setDisplayFormat(_translate("MainWindow", "yyyy/MM/dd"))
        self.changes_label.setText(_translate("MainWindow", "Changes are saved automatically"))
        self.camera_dockwidget.setWindowTitle(_translate("MainWindow", "Camera"))
        self.camera_zoom_label.setText(_translate("MainWindow", "Zoom"))
        self.autoguide_dockwidget.setWindowTitle(_translate("MainWindow", "Autoguide"))
        self.camera_zoom_label_2.setText(_translate("MainWindow", "Zoom"))
        self.filters_dockwidget.setWindowTitle(_translate("MainWindow", "Filters"))
        self.filter_table.setSortingEnabled(False)
        item = self.filter_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Name"))
        item.setToolTip(_translate("MainWindow", "The name of the filter"))
        item = self.filter_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Brand"))
        item = self.filter_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Wheel Position"))
        item.setToolTip(_translate("MainWindow", "The position the filter lies in the filter wheel"))
        item = self.filter_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Lower Cutoff"))
        item = self.filter_table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Upper Cutoff"))
        self.addrow_button_2.setToolTip(_translate("MainWindow", "Add row"))
        self.removerow_button_2.setToolTip(_translate("MainWindow", "Remove row"))
        self.changes_label_2.setText(_translate("MainWindow", "Changes are saved automatically"))
        self.exit_action.setText(_translate("MainWindow", "Exit"))
        self.exit_action.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.filters_action.setText(_translate("MainWindow", "Filters"))
        self.filters_action.setShortcut(_translate("MainWindow", "Ctrl+F"))
        self.location_action.setText(_translate("MainWindow", "Location"))
        self.location_action.setShortcut(_translate("MainWindow", "Ctrl+L"))
        self.targets_action.setText(_translate("MainWindow", "Targets"))
        self.targets_action.setShortcut(_translate("MainWindow", "Ctrl+T"))
        self.action_undo.setText(_translate("MainWindow", "Undo"))
        self.action_undo.setShortcut(_translate("MainWindow", "Ctrl+Z"))
        self.action_redo.setText(_translate("MainWindow", "Redo"))
        self.action_redo.setShortcut(_translate("MainWindow", "Ctrl+Y"))
        self.action_about.setText(_translate("MainWindow", "About"))
        self.telescope_action.setText(_translate("MainWindow", "Telescope"))
        self.guide_action.setText(_translate("MainWindow", "Autoguide"))
        self.camera_action.setText(_translate("MainWindow", "Camera"))
        self.focuser_action.setText(_translate("MainWindow", "Focuser"))
        self.wheel_action.setText(_translate("MainWindow", "Filter Wheel"))
        self.importschedule_action.setText(_translate("MainWindow", "Schedule"))
        self.importfilters_action.setText(_translate("MainWindow", "Filters"))
        self.actionSave_Location.setText(_translate("MainWindow", "Save Location"))
        self.action_closewindow.setText(_translate("MainWindow", "Close Window"))
        self.action_closewindow.setShortcut(_translate("MainWindow", "Ctrl+Alt+Q"))
        self.actionFilters.setText(_translate("MainWindow", "Filters"))
        self.actionSchedule.setText(_translate("MainWindow", "Schedule"))

import res_rc
