# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'zwosettings.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ZWOSettings(object):
    def setupUi(self, ZWOSettings):
        ZWOSettings.setObjectName("ZWOSettings")
        ZWOSettings.resize(244, 172)
        ZWOSettings.setFrameShape(QtWidgets.QFrame.StyledPanel)
        ZWOSettings.setFrameShadow(QtWidgets.QFrame.Raised)
        self.horizontalLayout = QtWidgets.QHBoxLayout(ZWOSettings)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.spinbox_formlayout = QtWidgets.QFormLayout()
        self.spinbox_formlayout.setObjectName("spinbox_formlayout")
        self.temperature_label = QtWidgets.QLabel(ZWOSettings)
        self.temperature_label.setObjectName("temperature_label")
        self.spinbox_formlayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.temperature_label)
        self.temperature_spinbox = QtWidgets.QSpinBox(ZWOSettings)
        self.temperature_spinbox.setObjectName("temperature_spinbox")
        self.spinbox_formlayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.temperature_spinbox)
        self.brightness_label = QtWidgets.QLabel(ZWOSettings)
        self.brightness_label.setObjectName("brightness_label")
        self.spinbox_formlayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.brightness_label)
        self.brightness_spinbox = QtWidgets.QSpinBox(ZWOSettings)
        self.brightness_spinbox.setObjectName("brightness_spinbox")
        self.spinbox_formlayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.brightness_spinbox)
        self.gamma_label = QtWidgets.QLabel(ZWOSettings)
        self.gamma_label.setObjectName("gamma_label")
        self.spinbox_formlayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.gamma_label)
        self.gamma_spinbox = QtWidgets.QSpinBox(ZWOSettings)
        self.gamma_spinbox.setObjectName("gamma_spinbox")
        self.spinbox_formlayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.gamma_spinbox)
        self.red_label = QtWidgets.QLabel(ZWOSettings)
        self.red_label.setObjectName("red_label")
        self.spinbox_formlayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.red_label)
        self.red_spinbox = QtWidgets.QSpinBox(ZWOSettings)
        self.red_spinbox.setObjectName("red_spinbox")
        self.spinbox_formlayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.red_spinbox)
        self.blue_label = QtWidgets.QLabel(ZWOSettings)
        self.blue_label.setObjectName("blue_label")
        self.spinbox_formlayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.blue_label)
        self.blue_spinbox = QtWidgets.QSpinBox(ZWOSettings)
        self.blue_spinbox.setObjectName("blue_spinbox")
        self.spinbox_formlayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.blue_spinbox)
        self.usb_label = QtWidgets.QLabel(ZWOSettings)
        self.usb_label.setObjectName("usb_label")
        self.spinbox_formlayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.usb_label)
        self.usb_spinbox = QtWidgets.QSpinBox(ZWOSettings)
        self.usb_spinbox.setObjectName("usb_spinbox")
        self.spinbox_formlayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.usb_spinbox)
        self.horizontalLayout.addLayout(self.spinbox_formlayout)
        self.line = QtWidgets.QFrame(ZWOSettings)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.checkbox_formlayout = QtWidgets.QFormLayout()
        self.checkbox_formlayout.setObjectName("checkbox_formlayout")
        self.highspeed_checkbox = QtWidgets.QCheckBox(ZWOSettings)
        self.highspeed_checkbox.setObjectName("highspeed_checkbox")
        self.checkbox_formlayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.highspeed_checkbox)
        self.hardwarebin_checkbox = QtWidgets.QCheckBox(ZWOSettings)
        self.hardwarebin_checkbox.setObjectName("hardwarebin_checkbox")
        self.checkbox_formlayout.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.hardwarebin_checkbox)
        self.monobin_checkbox = QtWidgets.QCheckBox(ZWOSettings)
        self.monobin_checkbox.setObjectName("monobin_checkbox")
        self.checkbox_formlayout.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.monobin_checkbox)
        self.horizontalflip_checkbox = QtWidgets.QCheckBox(ZWOSettings)
        self.horizontalflip_checkbox.setObjectName("horizontalflip_checkbox")
        self.checkbox_formlayout.setWidget(3, QtWidgets.QFormLayout.SpanningRole, self.horizontalflip_checkbox)
        self.verticalflip_checkbox = QtWidgets.QCheckBox(ZWOSettings)
        self.verticalflip_checkbox.setObjectName("verticalflip_checkbox")
        self.checkbox_formlayout.setWidget(4, QtWidgets.QFormLayout.SpanningRole, self.verticalflip_checkbox)
        self.horizontalLayout.addLayout(self.checkbox_formlayout)

        self.retranslateUi(ZWOSettings)
        QtCore.QMetaObject.connectSlotsByName(ZWOSettings)

    def retranslateUi(self, ZWOSettings):
        _translate = QtCore.QCoreApplication.translate
        ZWOSettings.setWindowTitle(_translate("ZWOSettings", "Frame"))
        self.temperature_label.setText(_translate("ZWOSettings", "Temperature"))
        self.brightness_label.setText(_translate("ZWOSettings", "Brightness"))
        self.gamma_label.setText(_translate("ZWOSettings", "Gamma"))
        self.red_label.setText(_translate("ZWOSettings", "Red"))
        self.blue_label.setText(_translate("ZWOSettings", "Blue"))
        self.usb_label.setText(_translate("ZWOSettings", "USB Bandwidth"))
        self.highspeed_checkbox.setText(_translate("ZWOSettings", "High Speed"))
        self.hardwarebin_checkbox.setText(_translate("ZWOSettings", "Hardware Bin"))
        self.monobin_checkbox.setText(_translate("ZWOSettings", "Mono Bin"))
        self.horizontalflip_checkbox.setText(_translate("ZWOSettings", "Horizontal Flip"))
        self.verticalflip_checkbox.setText(_translate("ZWOSettings", "Vertical Flip"))

