# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'mainwindow.ui'
##
## Created by: Qt User Interface Compiler version 5.15.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import (QCoreApplication, QDate, QDateTime, QMetaObject,
    QObject, QPoint, QRect, QSize, QTime, QUrl, Qt)
from PySide2.QtGui import (QBrush, QColor, QConicalGradient, QCursor, QFont,
    QFontDatabase, QIcon, QKeySequence, QLinearGradient, QPalette, QPainter,
    QPixmap, QRadialGradient)
from PySide2.QtWidgets import *

import res_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(788, 936)
        icon = QIcon()
        icon.addFile(u":/icons/logo.svg", QSize(), QIcon.Normal, QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setDockNestingEnabled(True)
        MainWindow.setDockOptions(QMainWindow.AllowNestedDocks|QMainWindow.AllowTabbedDocks|QMainWindow.AnimatedDocks)
        MainWindow.setUnifiedTitleAndToolBarOnMac(True)
        self.filters_action = QAction(MainWindow)
        self.filters_action.setObjectName(u"filters_action")
        icon1 = QIcon()
        icon1.addFile(u":/icons/ic_tonality_white_48px.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.filters_action.setIcon(icon1)
        self.location_action = QAction(MainWindow)
        self.location_action.setObjectName(u"location_action")
        icon2 = QIcon()
        icon2.addFile(u":/icons/ic_location_on_white_48px.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.location_action.setIcon(icon2)
        self.targets_action = QAction(MainWindow)
        self.targets_action.setObjectName(u"targets_action")
        icon3 = QIcon()
        icon3.addFile(u":/icons/ic_center_focus_strong_white_48px.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.targets_action.setIcon(icon3)
        self.action_undo = QAction(MainWindow)
        self.action_undo.setObjectName(u"action_undo")
        icon4 = QIcon()
        icon4.addFile(u":/icons/ic_undo_white_48px.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.action_undo.setIcon(icon4)
        self.action_redo = QAction(MainWindow)
        self.action_redo.setObjectName(u"action_redo")
        icon5 = QIcon()
        icon5.addFile(u":/icons/ic_redo_white_48px.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.action_redo.setIcon(icon5)
        self.action_about = QAction(MainWindow)
        self.action_about.setObjectName(u"action_about")
        icon6 = QIcon()
        icon6.addFile(u":/icons/ic_info_white_48px.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.action_about.setIcon(icon6)
        self.telescope_action = QAction(MainWindow)
        self.telescope_action.setObjectName(u"telescope_action")
        self.telescope_action.setCheckable(True)
        self.guider_action = QAction(MainWindow)
        self.guider_action.setObjectName(u"guider_action")
        self.guider_action.setCheckable(True)
        self.camera_action = QAction(MainWindow)
        self.camera_action.setObjectName(u"camera_action")
        self.camera_action.setCheckable(True)
        self.focuser_action = QAction(MainWindow)
        self.focuser_action.setObjectName(u"focuser_action")
        self.focuser_action.setCheckable(True)
        self.wheel_action = QAction(MainWindow)
        self.wheel_action.setObjectName(u"wheel_action")
        self.wheel_action.setCheckable(True)
        self.importschedule_action = QAction(MainWindow)
        self.importschedule_action.setObjectName(u"importschedule_action")
        self.importfilters_action = QAction(MainWindow)
        self.importfilters_action.setObjectName(u"importfilters_action")
        self.savelocation_action = QAction(MainWindow)
        self.savelocation_action.setObjectName(u"savelocation_action")
        icon7 = QIcon()
        icon7.addFile(u":/icons/ic_folder_white_48px.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.savelocation_action.setIcon(icon7)
        self.action_exit = QAction(MainWindow)
        self.action_exit.setObjectName(u"action_exit")
        icon8 = QIcon()
        icon8.addFile(u":/icons/ic_close_white_48px.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.action_exit.setIcon(icon8)
        self.actionFilters = QAction(MainWindow)
        self.actionFilters.setObjectName(u"actionFilters")
        self.actionSchedule = QAction(MainWindow)
        self.actionSchedule.setObjectName(u"actionSchedule")
        self.ascomcamerasettings_action = QAction(MainWindow)
        self.ascomcamerasettings_action.setObjectName(u"ascomcamerasettings_action")
        icon9 = QIcon()
        icon9.addFile(u":/icons/ic_settings_white_48px.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.ascomcamerasettings_action.setIcon(icon9)
        self.ascomguidersettings_action = QAction(MainWindow)
        self.ascomguidersettings_action.setObjectName(u"ascomguidersettings_action")
        self.ascomguidersettings_action.setIcon(icon9)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.horizontalLayout_2 = QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.scrollarea = QScrollArea(self.centralwidget)
        self.scrollarea.setObjectName(u"scrollarea")
        sizePolicy1 = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Expanding)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.scrollarea.sizePolicy().hasHeightForWidth())
        self.scrollarea.setSizePolicy(sizePolicy1)
        self.scrollarea.setFrameShape(QFrame.NoFrame)
        self.scrollarea.setFrameShadow(QFrame.Plain)
        self.scrollarea.setLineWidth(0)
        self.scrollarea.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOn)
        self.scrollarea.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.scrollarea.setSizeAdjustPolicy(QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.scrollarea.setWidgetResizable(True)
        self.scroll_area_widget_contents = QWidget()
        self.scroll_area_widget_contents.setObjectName(u"scroll_area_widget_contents")
        self.scroll_area_widget_contents.setGeometry(QRect(0, 0, 256, 1077))
        self.formLayout_4 = QFormLayout(self.scroll_area_widget_contents)
        self.formLayout_4.setObjectName(u"formLayout_4")
        self.mount_group = QGroupBox(self.scroll_area_widget_contents)
        self.mount_group.setObjectName(u"mount_group")
        self.mount_group.setEnabled(False)
        sizePolicy2 = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Fixed)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.mount_group.sizePolicy().hasHeightForWidth())
        self.mount_group.setSizePolicy(sizePolicy2)
        self.mount_group.setCheckable(False)
        self.mount_group.setChecked(False)
        self.verticalLayout_3 = QVBoxLayout(self.mount_group)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.scope_frame = QFrame(self.mount_group)
        self.scope_frame.setObjectName(u"scope_frame")
        self.scope_frame.setFrameShape(QFrame.NoFrame)
        self.scope_frame.setFrameShadow(QFrame.Plain)
        self.scope_frame.setLineWidth(0)
        self.verticalLayout = QVBoxLayout(self.scope_frame)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.gridlayout_10 = QGridLayout()
        self.gridlayout_10.setObjectName(u"gridlayout_10")
        self.slewnorth_button = QPushButton(self.scope_frame)
        self.slewnorth_button.setObjectName(u"slewnorth_button")
        sizePolicy3 = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Fixed)
        sizePolicy3.setHorizontalStretch(0)
        sizePolicy3.setVerticalStretch(0)
        sizePolicy3.setHeightForWidth(self.slewnorth_button.sizePolicy().hasHeightForWidth())
        self.slewnorth_button.setSizePolicy(sizePolicy3)
        icon10 = QIcon()
        icon10.addFile(u":/icons/ic_keyboard_arrow_up_white_48px.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.slewnorth_button.setIcon(icon10)
        self.slewnorth_button.setIconSize(QSize(36, 36))
        self.slewnorth_button.setAutoDefault(True)

        self.gridlayout_10.addWidget(self.slewnorth_button, 0, 1, 1, 1)

        self.slewsouthwest_button = QPushButton(self.scope_frame)
        self.slewsouthwest_button.setObjectName(u"slewsouthwest_button")
        sizePolicy3.setHeightForWidth(self.slewsouthwest_button.sizePolicy().hasHeightForWidth())
        self.slewsouthwest_button.setSizePolicy(sizePolicy3)
        icon11 = QIcon()
        icon11.addFile(u":/icons/ic_keyboard_arrow_downleft_white_48px.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.slewsouthwest_button.setIcon(icon11)
        self.slewsouthwest_button.setIconSize(QSize(36, 36))
        self.slewsouthwest_button.setAutoDefault(True)
        self.slewsouthwest_button.setFlat(False)

        self.gridlayout_10.addWidget(self.slewsouthwest_button, 2, 0, 1, 1)

        self.sleweast_button = QPushButton(self.scope_frame)
        self.sleweast_button.setObjectName(u"sleweast_button")
        sizePolicy3.setHeightForWidth(self.sleweast_button.sizePolicy().hasHeightForWidth())
        self.sleweast_button.setSizePolicy(sizePolicy3)
        icon12 = QIcon()
        icon12.addFile(u":/icons/ic_keyboard_arrow_right_white_48px.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.sleweast_button.setIcon(icon12)
        self.sleweast_button.setIconSize(QSize(36, 36))
        self.sleweast_button.setAutoDefault(True)

        self.gridlayout_10.addWidget(self.sleweast_button, 1, 2, 1, 1)

        self.slewnorthwest_button = QPushButton(self.scope_frame)
        self.slewnorthwest_button.setObjectName(u"slewnorthwest_button")
        sizePolicy3.setHeightForWidth(self.slewnorthwest_button.sizePolicy().hasHeightForWidth())
        self.slewnorthwest_button.setSizePolicy(sizePolicy3)
        icon13 = QIcon()
        icon13.addFile(u":/icons/ic_keyboard_arrow_upleft_white_48px.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.slewnorthwest_button.setIcon(icon13)
        self.slewnorthwest_button.setIconSize(QSize(36, 36))
        self.slewnorthwest_button.setAutoDefault(True)
        self.slewnorthwest_button.setFlat(False)

        self.gridlayout_10.addWidget(self.slewnorthwest_button, 0, 0, 1, 1)

        self.slewsoutheast_button = QPushButton(self.scope_frame)
        self.slewsoutheast_button.setObjectName(u"slewsoutheast_button")
        sizePolicy3.setHeightForWidth(self.slewsoutheast_button.sizePolicy().hasHeightForWidth())
        self.slewsoutheast_button.setSizePolicy(sizePolicy3)
        icon14 = QIcon()
        icon14.addFile(u":/icons/ic_keyboard_arrow_downright_white_48px.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.slewsoutheast_button.setIcon(icon14)
        self.slewsoutheast_button.setIconSize(QSize(36, 36))
        self.slewsoutheast_button.setAutoDefault(True)
        self.slewsoutheast_button.setFlat(False)

        self.gridlayout_10.addWidget(self.slewsoutheast_button, 2, 2, 1, 1)

        self.slewstop_button = QPushButton(self.scope_frame)
        self.slewstop_button.setObjectName(u"slewstop_button")
        sizePolicy3.setHeightForWidth(self.slewstop_button.sizePolicy().hasHeightForWidth())
        self.slewstop_button.setSizePolicy(sizePolicy3)
        icon15 = QIcon()
        icon15.addFile(u":/icons/ic_report_white_48px.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.slewstop_button.setIcon(icon15)
        self.slewstop_button.setIconSize(QSize(36, 36))
        self.slewstop_button.setAutoDefault(True)

        self.gridlayout_10.addWidget(self.slewstop_button, 1, 1, 1, 1)

        self.slewwest_button = QPushButton(self.scope_frame)
        self.slewwest_button.setObjectName(u"slewwest_button")
        sizePolicy3.setHeightForWidth(self.slewwest_button.sizePolicy().hasHeightForWidth())
        self.slewwest_button.setSizePolicy(sizePolicy3)
        icon16 = QIcon()
        icon16.addFile(u":/icons/ic_keyboard_arrow_left_white_48px.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.slewwest_button.setIcon(icon16)
        self.slewwest_button.setIconSize(QSize(36, 36))
        self.slewwest_button.setAutoDefault(True)

        self.gridlayout_10.addWidget(self.slewwest_button, 1, 0, 1, 1)

        self.slewsouth_button = QPushButton(self.scope_frame)
        self.slewsouth_button.setObjectName(u"slewsouth_button")
        sizePolicy3.setHeightForWidth(self.slewsouth_button.sizePolicy().hasHeightForWidth())
        self.slewsouth_button.setSizePolicy(sizePolicy3)
        icon17 = QIcon()
        icon17.addFile(u":/icons/ic_keyboard_arrow_down_white_48px.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.slewsouth_button.setIcon(icon17)
        self.slewsouth_button.setIconSize(QSize(36, 36))
        self.slewsouth_button.setAutoDefault(True)

        self.gridlayout_10.addWidget(self.slewsouth_button, 2, 1, 1, 1)

        self.slewnortheast_button = QPushButton(self.scope_frame)
        self.slewnortheast_button.setObjectName(u"slewnortheast_button")
        sizePolicy3.setHeightForWidth(self.slewnortheast_button.sizePolicy().hasHeightForWidth())
        self.slewnortheast_button.setSizePolicy(sizePolicy3)
        icon18 = QIcon()
        icon18.addFile(u":/icons/ic_keyboard_arrow_upright_white_48px.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.slewnortheast_button.setIcon(icon18)
        self.slewnortheast_button.setIconSize(QSize(36, 36))
        self.slewnortheast_button.setAutoDefault(True)
        self.slewnortheast_button.setFlat(False)

        self.gridlayout_10.addWidget(self.slewnortheast_button, 0, 2, 1, 1)


        self.verticalLayout.addLayout(self.gridlayout_10)

        self.formlayout_2 = QFormLayout()
        self.formlayout_2.setObjectName(u"formlayout_2")
        self.mount_trackrate_label = QLabel(self.scope_frame)
        self.mount_trackrate_label.setObjectName(u"mount_trackrate_label")

        self.formlayout_2.setWidget(0, QFormLayout.LabelRole, self.mount_trackrate_label)

        self.mount_trackrate_spin = QDoubleSpinBox(self.scope_frame)
        self.mount_trackrate_spin.setObjectName(u"mount_trackrate_spin")
        self.mount_trackrate_spin.setFocusPolicy(Qt.StrongFocus)
        self.mount_trackrate_spin.setMinimum(0.010000000000000)
        self.mount_trackrate_spin.setMaximum(1.000000000000000)
        self.mount_trackrate_spin.setSingleStep(0.010000000000000)
        self.mount_trackrate_spin.setValue(0.200000000000000)

        self.formlayout_2.setWidget(0, QFormLayout.FieldRole, self.mount_trackrate_spin)


        self.verticalLayout.addLayout(self.formlayout_2)

        self.horizontallayout_5 = QHBoxLayout()
        self.horizontallayout_5.setObjectName(u"horizontallayout_5")
        self.object_label = QLabel(self.scope_frame)
        self.object_label.setObjectName(u"object_label")
        sizePolicy.setHeightForWidth(self.object_label.sizePolicy().hasHeightForWidth())
        self.object_label.setSizePolicy(sizePolicy)

        self.horizontallayout_5.addWidget(self.object_label)

        self.line = QFrame(self.scope_frame)
        self.line.setObjectName(u"line")
        self.line.setFrameShape(QFrame.HLine)
        self.line.setFrameShadow(QFrame.Sunken)

        self.horizontallayout_5.addWidget(self.line)


        self.verticalLayout.addLayout(self.horizontallayout_5)

        self.horizontallayout_4 = QHBoxLayout()
        self.horizontallayout_4.setObjectName(u"horizontallayout_4")
        self.object_combobox = QComboBox(self.scope_frame)
        self.object_combobox.setObjectName(u"object_combobox")
        sizePolicy4 = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Preferred)
        sizePolicy4.setHorizontalStretch(0)
        sizePolicy4.setVerticalStretch(0)
        sizePolicy4.setHeightForWidth(self.object_combobox.sizePolicy().hasHeightForWidth())
        self.object_combobox.setSizePolicy(sizePolicy4)
        self.object_combobox.setFocusPolicy(Qt.StrongFocus)

        self.horizontallayout_4.addWidget(self.object_combobox)

        self.goto_button = QPushButton(self.scope_frame)
        self.goto_button.setObjectName(u"goto_button")
        sizePolicy.setHeightForWidth(self.goto_button.sizePolicy().hasHeightForWidth())
        self.goto_button.setSizePolicy(sizePolicy)
        icon19 = QIcon()
        icon19.addFile(u":/icons/ic_check_white_48px.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.goto_button.setIcon(icon19)
        self.goto_button.setAutoDefault(True)

        self.horizontallayout_4.addWidget(self.goto_button)


        self.verticalLayout.addLayout(self.horizontallayout_4)


        self.verticalLayout_3.addWidget(self.scope_frame)


        self.formLayout_4.setWidget(0, QFormLayout.SpanningRole, self.mount_group)

        self.guider_group = QGroupBox(self.scroll_area_widget_contents)
        self.guider_group.setObjectName(u"guider_group")
        self.guider_group.setEnabled(False)
        sizePolicy2.setHeightForWidth(self.guider_group.sizePolicy().hasHeightForWidth())
        self.guider_group.setSizePolicy(sizePolicy2)
        self.guider_group.setCheckable(False)
        self.guider_group.setChecked(False)
        self.verticalLayout_2 = QVBoxLayout(self.guider_group)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.guide_frame = QFrame(self.guider_group)
        self.guide_frame.setObjectName(u"guide_frame")
        self.guide_frame.setFrameShape(QFrame.NoFrame)
        self.guide_frame.setFrameShadow(QFrame.Plain)
        self.guide_frame.setLineWidth(0)
        self.formLayout_3 = QFormLayout(self.guide_frame)
        self.formLayout_3.setObjectName(u"formLayout_3")
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.guider_exposure_label = QLabel(self.guide_frame)
        self.guider_exposure_label.setObjectName(u"guider_exposure_label")
        sizePolicy.setHeightForWidth(self.guider_exposure_label.sizePolicy().hasHeightForWidth())
        self.guider_exposure_label.setSizePolicy(sizePolicy)

        self.formLayout_3.setWidget(0, QFormLayout.LabelRole, self.guider_exposure_label)

        self.guider_exposure_spinbox = QSpinBox(self.guide_frame)
        self.guider_exposure_spinbox.setObjectName(u"guider_exposure_spinbox")
        sizePolicy5 = QSizePolicy(QSizePolicy.MinimumExpanding, QSizePolicy.Fixed)
        sizePolicy5.setHorizontalStretch(0)
        sizePolicy5.setVerticalStretch(0)
        sizePolicy5.setHeightForWidth(self.guider_exposure_spinbox.sizePolicy().hasHeightForWidth())
        self.guider_exposure_spinbox.setSizePolicy(sizePolicy5)
        self.guider_exposure_spinbox.setFocusPolicy(Qt.StrongFocus)

        self.formLayout_3.setWidget(0, QFormLayout.FieldRole, self.guider_exposure_spinbox)

        self.guider_exposure_slider = QSlider(self.guide_frame)
        self.guider_exposure_slider.setObjectName(u"guider_exposure_slider")
        sizePolicy3.setHeightForWidth(self.guider_exposure_slider.sizePolicy().hasHeightForWidth())
        self.guider_exposure_slider.setSizePolicy(sizePolicy3)
        self.guider_exposure_slider.setFocusPolicy(Qt.StrongFocus)
        self.guider_exposure_slider.setOrientation(Qt.Horizontal)

        self.formLayout_3.setWidget(1, QFormLayout.SpanningRole, self.guider_exposure_slider)

        self.guider_gain_label = QLabel(self.guide_frame)
        self.guider_gain_label.setObjectName(u"guider_gain_label")
        sizePolicy.setHeightForWidth(self.guider_gain_label.sizePolicy().hasHeightForWidth())
        self.guider_gain_label.setSizePolicy(sizePolicy)

        self.formLayout_3.setWidget(2, QFormLayout.LabelRole, self.guider_gain_label)

        self.guider_gain_spinbox = QSpinBox(self.guide_frame)
        self.guider_gain_spinbox.setObjectName(u"guider_gain_spinbox")
        sizePolicy5.setHeightForWidth(self.guider_gain_spinbox.sizePolicy().hasHeightForWidth())
        self.guider_gain_spinbox.setSizePolicy(sizePolicy5)
        self.guider_gain_spinbox.setFocusPolicy(Qt.StrongFocus)
        self.guider_gain_spinbox.setMaximum(600)

        self.formLayout_3.setWidget(2, QFormLayout.FieldRole, self.guider_gain_spinbox)

        self.guider_gain_slider = QSlider(self.guide_frame)
        self.guider_gain_slider.setObjectName(u"guider_gain_slider")
        sizePolicy3.setHeightForWidth(self.guider_gain_slider.sizePolicy().hasHeightForWidth())
        self.guider_gain_slider.setSizePolicy(sizePolicy3)
        self.guider_gain_slider.setFocusPolicy(Qt.StrongFocus)
        self.guider_gain_slider.setOrientation(Qt.Horizontal)

        self.formLayout_3.setWidget(3, QFormLayout.SpanningRole, self.guider_gain_slider)

        self.horizontallayout_7 = QHBoxLayout()
        self.horizontallayout_7.setObjectName(u"horizontallayout_7")
        self.guider_spacer = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)

        self.horizontallayout_7.addItem(self.guider_spacer)

        self.guider_loop_button = QPushButton(self.guide_frame)
        self.guider_loop_button.setObjectName(u"guider_loop_button")
        sizePolicy6 = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy6.setHorizontalStretch(0)
        sizePolicy6.setVerticalStretch(0)
        sizePolicy6.setHeightForWidth(self.guider_loop_button.sizePolicy().hasHeightForWidth())
        self.guider_loop_button.setSizePolicy(sizePolicy6)
        icon20 = QIcon()
        icon20.addFile(u":/icons/ic_replay_white_48px.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.guider_loop_button.setIcon(icon20)
        self.guider_loop_button.setIconSize(QSize(32, 32))
        self.guider_loop_button.setCheckable(True)
        self.guider_loop_button.setAutoDefault(True)

        self.horizontallayout_7.addWidget(self.guider_loop_button)

        self.guider_start_button = QPushButton(self.guide_frame)
        self.guider_start_button.setObjectName(u"guider_start_button")
        self.guider_start_button.setEnabled(False)
        sizePolicy6.setHeightForWidth(self.guider_start_button.sizePolicy().hasHeightForWidth())
        self.guider_start_button.setSizePolicy(sizePolicy6)
        icon21 = QIcon()
        icon21.addFile(u":/icons/ic_play_arrow_white_48px.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.guider_start_button.setIcon(icon21)
        self.guider_start_button.setIconSize(QSize(32, 32))
        self.guider_start_button.setCheckable(True)
        self.guider_start_button.setAutoDefault(True)

        self.horizontallayout_7.addWidget(self.guider_start_button)


        self.formLayout_3.setLayout(4, QFormLayout.SpanningRole, self.horizontallayout_7)


        self.verticalLayout_2.addWidget(self.guide_frame)


        self.formLayout_4.setWidget(1, QFormLayout.SpanningRole, self.guider_group)

        self.camera_group = QGroupBox(self.scroll_area_widget_contents)
        self.camera_group.setObjectName(u"camera_group")
        self.camera_group.setEnabled(False)
        sizePolicy2.setHeightForWidth(self.camera_group.sizePolicy().hasHeightForWidth())
        self.camera_group.setSizePolicy(sizePolicy2)
        self.camera_group.setCheckable(False)
        self.camera_group.setChecked(False)
        self.formLayout_8 = QFormLayout(self.camera_group)
        self.formLayout_8.setObjectName(u"formLayout_8")
        self.camera_frame = QFrame(self.camera_group)
        self.camera_frame.setObjectName(u"camera_frame")
        self.camera_frame.setFrameShape(QFrame.NoFrame)
        self.camera_frame.setFrameShadow(QFrame.Plain)
        self.camera_frame.setLineWidth(0)
        self.gridLayout = QGridLayout(self.camera_frame)
        self.gridLayout.setObjectName(u"gridLayout")
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.camera_exposure_slider = QSlider(self.camera_frame)
        self.camera_exposure_slider.setObjectName(u"camera_exposure_slider")
        sizePolicy3.setHeightForWidth(self.camera_exposure_slider.sizePolicy().hasHeightForWidth())
        self.camera_exposure_slider.setSizePolicy(sizePolicy3)
        self.camera_exposure_slider.setFocusPolicy(Qt.StrongFocus)
        self.camera_exposure_slider.setOrientation(Qt.Horizontal)

        self.gridLayout.addWidget(self.camera_exposure_slider, 1, 0, 1, 2)

        self.camera_filter_combobox = QComboBox(self.camera_frame)
        self.camera_filter_combobox.setObjectName(u"camera_filter_combobox")
        sizePolicy3.setHeightForWidth(self.camera_filter_combobox.sizePolicy().hasHeightForWidth())
        self.camera_filter_combobox.setSizePolicy(sizePolicy3)
        self.camera_filter_combobox.setFocusPolicy(Qt.StrongFocus)

        self.gridLayout.addWidget(self.camera_filter_combobox, 5, 1, 1, 1)

        self.camera_gain_spinbox = QSpinBox(self.camera_frame)
        self.camera_gain_spinbox.setObjectName(u"camera_gain_spinbox")
        self.camera_gain_spinbox.setFocusPolicy(Qt.StrongFocus)

        self.gridLayout.addWidget(self.camera_gain_spinbox, 2, 1, 1, 1)

        self.camera_format_combobox = QComboBox(self.camera_frame)
        self.camera_format_combobox.setObjectName(u"camera_format_combobox")
        sizePolicy3.setHeightForWidth(self.camera_format_combobox.sizePolicy().hasHeightForWidth())
        self.camera_format_combobox.setSizePolicy(sizePolicy3)
        self.camera_format_combobox.setFocusPolicy(Qt.StrongFocus)

        self.gridLayout.addWidget(self.camera_format_combobox, 6, 1, 1, 1)

        self.camera_integration_spinbox = QSpinBox(self.camera_frame)
        self.camera_integration_spinbox.setObjectName(u"camera_integration_spinbox")
        self.camera_integration_spinbox.setEnabled(False)
        self.camera_integration_spinbox.setFocusPolicy(Qt.StrongFocus)

        self.gridLayout.addWidget(self.camera_integration_spinbox, 4, 1, 1, 1)

        self.camera_gain_slider = QSlider(self.camera_frame)
        self.camera_gain_slider.setObjectName(u"camera_gain_slider")
        sizePolicy3.setHeightForWidth(self.camera_gain_slider.sizePolicy().hasHeightForWidth())
        self.camera_gain_slider.setSizePolicy(sizePolicy3)
        self.camera_gain_slider.setFocusPolicy(Qt.StrongFocus)
        self.camera_gain_slider.setOrientation(Qt.Horizontal)

        self.gridLayout.addWidget(self.camera_gain_slider, 3, 0, 1, 2)

        self.camera_exposure_label = QLabel(self.camera_frame)
        self.camera_exposure_label.setObjectName(u"camera_exposure_label")
        sizePolicy.setHeightForWidth(self.camera_exposure_label.sizePolicy().hasHeightForWidth())
        self.camera_exposure_label.setSizePolicy(sizePolicy)

        self.gridLayout.addWidget(self.camera_exposure_label, 0, 0, 1, 1)

        self.camera_gain_label = QLabel(self.camera_frame)
        self.camera_gain_label.setObjectName(u"camera_gain_label")
        sizePolicy.setHeightForWidth(self.camera_gain_label.sizePolicy().hasHeightForWidth())
        self.camera_gain_label.setSizePolicy(sizePolicy)

        self.gridLayout.addWidget(self.camera_gain_label, 2, 0, 1, 1)

        self.camera_format_label = QLabel(self.camera_frame)
        self.camera_format_label.setObjectName(u"camera_format_label")

        self.gridLayout.addWidget(self.camera_format_label, 6, 0, 1, 1)

        self.camera_exposure_spinbox = QSpinBox(self.camera_frame)
        self.camera_exposure_spinbox.setObjectName(u"camera_exposure_spinbox")
        sizePolicy3.setHeightForWidth(self.camera_exposure_spinbox.sizePolicy().hasHeightForWidth())
        self.camera_exposure_spinbox.setSizePolicy(sizePolicy3)
        self.camera_exposure_spinbox.setFocusPolicy(Qt.StrongFocus)

        self.gridLayout.addWidget(self.camera_exposure_spinbox, 0, 1, 1, 1)

        self.horizontallayout_8 = QHBoxLayout()
        self.horizontallayout_8.setObjectName(u"horizontallayout_8")
        self.horizontalSpacer_2 = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)

        self.horizontallayout_8.addItem(self.horizontalSpacer_2)

        self.camera_loop_button = QPushButton(self.camera_frame)
        self.camera_loop_button.setObjectName(u"camera_loop_button")
        sizePolicy6.setHeightForWidth(self.camera_loop_button.sizePolicy().hasHeightForWidth())
        self.camera_loop_button.setSizePolicy(sizePolicy6)
        self.camera_loop_button.setIcon(icon20)
        self.camera_loop_button.setIconSize(QSize(32, 32))
        self.camera_loop_button.setCheckable(True)
        self.camera_loop_button.setAutoDefault(True)

        self.horizontallayout_8.addWidget(self.camera_loop_button)

        self.camera_capture_button = QPushButton(self.camera_frame)
        self.camera_capture_button.setObjectName(u"camera_capture_button")
        self.camera_capture_button.setEnabled(False)
        sizePolicy6.setHeightForWidth(self.camera_capture_button.sizePolicy().hasHeightForWidth())
        self.camera_capture_button.setSizePolicy(sizePolicy6)
        self.camera_capture_button.setIcon(icon21)
        self.camera_capture_button.setIconSize(QSize(32, 32))
        self.camera_capture_button.setCheckable(True)
        self.camera_capture_button.setAutoDefault(True)

        self.horizontallayout_8.addWidget(self.camera_capture_button)


        self.gridLayout.addLayout(self.horizontallayout_8, 7, 0, 1, 2)

        self.camera_filter_label = QLabel(self.camera_frame)
        self.camera_filter_label.setObjectName(u"camera_filter_label")

        self.gridLayout.addWidget(self.camera_filter_label, 5, 0, 1, 1)

        self.camera_integration_checkbox = QCheckBox(self.camera_frame)
        self.camera_integration_checkbox.setObjectName(u"camera_integration_checkbox")

        self.gridLayout.addWidget(self.camera_integration_checkbox, 4, 0, 1, 1)


        self.formLayout_8.setWidget(1, QFormLayout.SpanningRole, self.camera_frame)


        self.formLayout_4.setWidget(2, QFormLayout.SpanningRole, self.camera_group)

        self.wheel_group = QGroupBox(self.scroll_area_widget_contents)
        self.wheel_group.setObjectName(u"wheel_group")
        self.wheel_group.setEnabled(False)
        sizePolicy2.setHeightForWidth(self.wheel_group.sizePolicy().hasHeightForWidth())
        self.wheel_group.setSizePolicy(sizePolicy2)
        self.wheel_group.setCheckable(False)
        self.wheel_group.setChecked(False)
        self.formLayout = QFormLayout(self.wheel_group)
        self.formLayout.setObjectName(u"formLayout")
        self.wheel_frame = QFrame(self.wheel_group)
        self.wheel_frame.setObjectName(u"wheel_frame")
        self.wheel_frame.setFrameShape(QFrame.NoFrame)
        self.wheel_frame.setFrameShadow(QFrame.Plain)
        self.wheel_frame.setLineWidth(0)
        self.gridLayout_3 = QGridLayout(self.wheel_frame)
        self.gridLayout_3.setObjectName(u"gridLayout_3")
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.position_combobox = QComboBox(self.wheel_frame)
        self.position_combobox.setObjectName(u"position_combobox")
        sizePolicy4.setHeightForWidth(self.position_combobox.sizePolicy().hasHeightForWidth())
        self.position_combobox.setSizePolicy(sizePolicy4)
        self.position_combobox.setFocusPolicy(Qt.StrongFocus)
        self.position_combobox.setEditable(True)
        self.position_combobox.setInsertPolicy(QComboBox.NoInsert)

        self.gridLayout_3.addWidget(self.position_combobox, 0, 1, 1, 1)

        self.position_label = QLabel(self.wheel_frame)
        self.position_label.setObjectName(u"position_label")
        sizePolicy.setHeightForWidth(self.position_label.sizePolicy().hasHeightForWidth())
        self.position_label.setSizePolicy(sizePolicy)

        self.gridLayout_3.addWidget(self.position_label, 0, 0, 1, 1)


        self.formLayout.setWidget(1, QFormLayout.SpanningRole, self.wheel_frame)


        self.formLayout_4.setWidget(3, QFormLayout.SpanningRole, self.wheel_group)

        self.focuser_group = QGroupBox(self.scroll_area_widget_contents)
        self.focuser_group.setObjectName(u"focuser_group")
        self.focuser_group.setEnabled(False)
        sizePolicy2.setHeightForWidth(self.focuser_group.sizePolicy().hasHeightForWidth())
        self.focuser_group.setSizePolicy(sizePolicy2)
        self.focuser_group.setCheckable(False)
        self.focuser_group.setChecked(False)
        self.formLayout_9 = QFormLayout(self.focuser_group)
        self.formLayout_9.setObjectName(u"formLayout_9")
        self.focuser_frame = QFrame(self.focuser_group)
        self.focuser_frame.setObjectName(u"focuser_frame")
        self.focuser_frame.setFrameShape(QFrame.NoFrame)
        self.focuser_frame.setFrameShadow(QFrame.Plain)
        self.focuser_frame.setLineWidth(0)
        self.gridLayout_2 = QGridLayout(self.focuser_frame)
        self.gridLayout_2.setObjectName(u"gridLayout_2")
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.temp_checkbox = QCheckBox(self.focuser_frame)
        self.temp_checkbox.setObjectName(u"temp_checkbox")

        self.gridLayout_2.addWidget(self.temp_checkbox, 1, 0, 1, 2)

        self.focuser_position_label = QLabel(self.focuser_frame)
        self.focuser_position_label.setObjectName(u"focuser_position_label")
        sizePolicy.setHeightForWidth(self.focuser_position_label.sizePolicy().hasHeightForWidth())
        self.focuser_position_label.setSizePolicy(sizePolicy)

        self.gridLayout_2.addWidget(self.focuser_position_label, 0, 0, 1, 1)

        self.focuser_position_spinbox = QSpinBox(self.focuser_frame)
        self.focuser_position_spinbox.setObjectName(u"focuser_position_spinbox")
        self.focuser_position_spinbox.setFocusPolicy(Qt.StrongFocus)

        self.gridLayout_2.addWidget(self.focuser_position_spinbox, 0, 1, 1, 1)


        self.formLayout_9.setWidget(1, QFormLayout.SpanningRole, self.focuser_frame)


        self.formLayout_4.setWidget(4, QFormLayout.SpanningRole, self.focuser_group)

        self.scrollarea.setWidget(self.scroll_area_widget_contents)

        self.horizontalLayout_2.addWidget(self.scrollarea)

        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 788, 29))
        self.file_menu = QMenu(self.menubar)
        self.file_menu.setObjectName(u"file_menu")
        self.import_menu = QMenu(self.file_menu)
        self.import_menu.setObjectName(u"import_menu")
        self.menuExport = QMenu(self.file_menu)
        self.menuExport.setObjectName(u"menuExport")
        self.menu_edit = QMenu(self.menubar)
        self.menu_edit.setObjectName(u"menu_edit")
        self.menu_equipment = QMenu(self.menu_edit)
        self.menu_equipment.setObjectName(u"menu_equipment")
        self.help_menu = QMenu(self.menubar)
        self.help_menu.setObjectName(u"help_menu")
        MainWindow.setMenuBar(self.menubar)
        self.schedule_dockwidget = QDockWidget(MainWindow)
        self.schedule_dockwidget.setObjectName(u"schedule_dockwidget")
        sizePolicy7 = QSizePolicy(QSizePolicy.MinimumExpanding, QSizePolicy.Preferred)
        sizePolicy7.setHorizontalStretch(0)
        sizePolicy7.setVerticalStretch(0)
        sizePolicy7.setHeightForWidth(self.schedule_dockwidget.sizePolicy().hasHeightForWidth())
        self.schedule_dockwidget.setSizePolicy(sizePolicy7)
        self.schedule_dockwidget.setFeatures(QDockWidget.DockWidgetFloatable|QDockWidget.DockWidgetMovable)
        self.schedule_dockwidget.setAllowedAreas(Qt.LeftDockWidgetArea|Qt.RightDockWidgetArea)
        self.dockwidget_contents = QWidget()
        self.dockwidget_contents.setObjectName(u"dockwidget_contents")
        self.verticalLayout_7 = QVBoxLayout(self.dockwidget_contents)
        self.verticalLayout_7.setObjectName(u"verticalLayout_7")
        self.verticalLayout_7.setContentsMargins(0, 0, 0, -1)
        self.schedule_table = QTableWidget(self.dockwidget_contents)
        if (self.schedule_table.columnCount() < 6):
            self.schedule_table.setColumnCount(6)
        __qtablewidgetitem = QTableWidgetItem()
        self.schedule_table.setHorizontalHeaderItem(0, __qtablewidgetitem)
        __qtablewidgetitem1 = QTableWidgetItem()
        self.schedule_table.setHorizontalHeaderItem(1, __qtablewidgetitem1)
        __qtablewidgetitem2 = QTableWidgetItem()
        self.schedule_table.setHorizontalHeaderItem(2, __qtablewidgetitem2)
        __qtablewidgetitem3 = QTableWidgetItem()
        self.schedule_table.setHorizontalHeaderItem(3, __qtablewidgetitem3)
        __qtablewidgetitem4 = QTableWidgetItem()
        self.schedule_table.setHorizontalHeaderItem(4, __qtablewidgetitem4)
        __qtablewidgetitem5 = QTableWidgetItem()
        self.schedule_table.setHorizontalHeaderItem(5, __qtablewidgetitem5)
        self.schedule_table.setObjectName(u"schedule_table")
        self.schedule_table.setFrameShape(QFrame.NoFrame)
        self.schedule_table.horizontalHeader().setCascadingSectionResizes(True)
        self.schedule_table.verticalHeader().setCascadingSectionResizes(True)

        self.verticalLayout_7.addWidget(self.schedule_table)

        self.horizontallayout = QHBoxLayout()
        self.horizontallayout.setObjectName(u"horizontallayout")
        self.horizontallayout.setContentsMargins(9, -1, 9, -1)
        self.addrow_button = QPushButton(self.dockwidget_contents)
        self.addrow_button.setObjectName(u"addrow_button")
        sizePolicy.setHeightForWidth(self.addrow_button.sizePolicy().hasHeightForWidth())
        self.addrow_button.setSizePolicy(sizePolicy)
        icon22 = QIcon()
        icon22.addFile(u":/icons/ic_add_white_48px.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.addrow_button.setIcon(icon22)
        self.addrow_button.setAutoDefault(True)

        self.horizontallayout.addWidget(self.addrow_button)

        self.removerow_button = QPushButton(self.dockwidget_contents)
        self.removerow_button.setObjectName(u"removerow_button")
        sizePolicy.setHeightForWidth(self.removerow_button.sizePolicy().hasHeightForWidth())
        self.removerow_button.setSizePolicy(sizePolicy)
        icon23 = QIcon()
        icon23.addFile(u":/icons/ic_remove_white_48px.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.removerow_button.setIcon(icon23)
        self.removerow_button.setAutoDefault(True)

        self.horizontallayout.addWidget(self.removerow_button)

        self.line_7 = QFrame(self.dockwidget_contents)
        self.line_7.setObjectName(u"line_7")
        self.line_7.setFrameShape(QFrame.VLine)
        self.line_7.setFrameShadow(QFrame.Sunken)

        self.horizontallayout.addWidget(self.line_7)

        self.schedule_date_label = QLabel(self.dockwidget_contents)
        self.schedule_date_label.setObjectName(u"schedule_date_label")
        sizePolicy.setHeightForWidth(self.schedule_date_label.sizePolicy().hasHeightForWidth())
        self.schedule_date_label.setSizePolicy(sizePolicy)

        self.horizontallayout.addWidget(self.schedule_date_label)

        self.schedule_dateedit = QDateEdit(self.dockwidget_contents)
        self.schedule_dateedit.setObjectName(u"schedule_dateedit")
        sizePolicy6.setHeightForWidth(self.schedule_dateedit.sizePolicy().hasHeightForWidth())
        self.schedule_dateedit.setSizePolicy(sizePolicy6)
        self.schedule_dateedit.setFocusPolicy(Qt.StrongFocus)
        self.schedule_dateedit.setCurrentSection(QDateTimeEdit.DaySection)
        self.schedule_dateedit.setCalendarPopup(False)
        self.schedule_dateedit.setCurrentSectionIndex(2)
        self.schedule_dateedit.setTimeSpec(Qt.UTC)

        self.horizontallayout.addWidget(self.schedule_dateedit)

        self.horizontalspacer_3 = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)

        self.horizontallayout.addItem(self.horizontalspacer_3)

        self.changes_label = QLabel(self.dockwidget_contents)
        self.changes_label.setObjectName(u"changes_label")
        sizePolicy.setHeightForWidth(self.changes_label.sizePolicy().hasHeightForWidth())
        self.changes_label.setSizePolicy(sizePolicy)
        self.changes_label.setAlignment(Qt.AlignCenter)

        self.horizontallayout.addWidget(self.changes_label, 0, Qt.AlignRight)


        self.verticalLayout_7.addLayout(self.horizontallayout)

        self.schedule_dockwidget.setWidget(self.dockwidget_contents)
        MainWindow.addDockWidget(Qt.RightDockWidgetArea, self.schedule_dockwidget)
        self.camera_dockwidget = QDockWidget(MainWindow)
        self.camera_dockwidget.setObjectName(u"camera_dockwidget")
        sizePolicy7.setHeightForWidth(self.camera_dockwidget.sizePolicy().hasHeightForWidth())
        self.camera_dockwidget.setSizePolicy(sizePolicy7)
        self.camera_dockwidget.setFeatures(QDockWidget.DockWidgetFloatable|QDockWidget.DockWidgetMovable)
        self.camera_dockwidget.setAllowedAreas(Qt.LeftDockWidgetArea|Qt.RightDockWidgetArea)
        self.dockwidgetcontents_2 = QWidget()
        self.dockwidgetcontents_2.setObjectName(u"dockwidgetcontents_2")
        self.verticalLayout_9 = QVBoxLayout(self.dockwidgetcontents_2)
        self.verticalLayout_9.setObjectName(u"verticalLayout_9")
        self.verticalLayout_9.setContentsMargins(0, 0, 0, -1)
        self.camera_scrollarea = QScrollArea(self.dockwidgetcontents_2)
        self.camera_scrollarea.setObjectName(u"camera_scrollarea")
        self.camera_scrollarea.setLayoutDirection(Qt.LeftToRight)
        self.camera_scrollarea.setFrameShape(QFrame.NoFrame)
        self.camera_scrollarea.setFrameShadow(QFrame.Plain)
        self.camera_scrollarea.setLineWidth(0)
        self.camera_scrollarea.setWidgetResizable(True)
        self.camera_scrollarea.setAlignment(Qt.AlignCenter)
        self.camera_scrollarea_contents = QWidget()
        self.camera_scrollarea_contents.setObjectName(u"camera_scrollarea_contents")
        self.camera_scrollarea_contents.setGeometry(QRect(0, 0, 510, 102))
        self.verticalLayout_4 = QVBoxLayout(self.camera_scrollarea_contents)
        self.verticalLayout_4.setObjectName(u"verticalLayout_4")
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.camera_preview_label = QLabel(self.camera_scrollarea_contents)
        self.camera_preview_label.setObjectName(u"camera_preview_label")
        self.camera_preview_label.setAlignment(Qt.AlignCenter)

        self.verticalLayout_4.addWidget(self.camera_preview_label, 0, Qt.AlignHCenter|Qt.AlignVCenter)

        self.camera_scrollarea.setWidget(self.camera_scrollarea_contents)

        self.verticalLayout_9.addWidget(self.camera_scrollarea)

        self.gridLayout_6 = QGridLayout()
        self.gridLayout_6.setObjectName(u"gridLayout_6")
        self.camera_zoom_label = QLabel(self.dockwidgetcontents_2)
        self.camera_zoom_label.setObjectName(u"camera_zoom_label")
        sizePolicy.setHeightForWidth(self.camera_zoom_label.sizePolicy().hasHeightForWidth())
        self.camera_zoom_label.setSizePolicy(sizePolicy)

        self.gridLayout_6.addWidget(self.camera_zoom_label, 0, 0, 1, 1)

        self.camera_zoom_spinbox = QSpinBox(self.dockwidgetcontents_2)
        self.camera_zoom_spinbox.setObjectName(u"camera_zoom_spinbox")
        self.camera_zoom_spinbox.setMinimum(20)
        self.camera_zoom_spinbox.setMaximum(300)
        self.camera_zoom_spinbox.setValue(100)

        self.gridLayout_6.addWidget(self.camera_zoom_spinbox, 0, 1, 1, 1)

        self.camera_zoom_slider = QSlider(self.dockwidgetcontents_2)
        self.camera_zoom_slider.setObjectName(u"camera_zoom_slider")
        sizePolicy2.setHeightForWidth(self.camera_zoom_slider.sizePolicy().hasHeightForWidth())
        self.camera_zoom_slider.setSizePolicy(sizePolicy2)
        self.camera_zoom_slider.setMinimum(20)
        self.camera_zoom_slider.setMaximum(300)
        self.camera_zoom_slider.setValue(100)
        self.camera_zoom_slider.setOrientation(Qt.Horizontal)

        self.gridLayout_6.addWidget(self.camera_zoom_slider, 1, 0, 1, 2)

        self.camera_spacer = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)

        self.gridLayout_6.addItem(self.camera_spacer, 0, 2, 2, 1)


        self.verticalLayout_9.addLayout(self.gridLayout_6)

        self.camera_dockwidget.setWidget(self.dockwidgetcontents_2)
        MainWindow.addDockWidget(Qt.RightDockWidgetArea, self.camera_dockwidget)
        self.guider_dockwidget = QDockWidget(MainWindow)
        self.guider_dockwidget.setObjectName(u"guider_dockwidget")
        sizePolicy7.setHeightForWidth(self.guider_dockwidget.sizePolicy().hasHeightForWidth())
        self.guider_dockwidget.setSizePolicy(sizePolicy7)
        self.guider_dockwidget.setFeatures(QDockWidget.DockWidgetFloatable|QDockWidget.DockWidgetMovable)
        self.guider_dockwidget.setAllowedAreas(Qt.LeftDockWidgetArea|Qt.RightDockWidgetArea)
        self.dockwidgetcontents_3 = QWidget()
        self.dockwidgetcontents_3.setObjectName(u"dockwidgetcontents_3")
        self.verticalLayout_10 = QVBoxLayout(self.dockwidgetcontents_3)
        self.verticalLayout_10.setObjectName(u"verticalLayout_10")
        self.verticalLayout_10.setContentsMargins(0, 0, 0, -1)
        self.guider_scrollarea = QScrollArea(self.dockwidgetcontents_3)
        self.guider_scrollarea.setObjectName(u"guider_scrollarea")
        self.guider_scrollarea.setLayoutDirection(Qt.LeftToRight)
        self.guider_scrollarea.setFrameShape(QFrame.NoFrame)
        self.guider_scrollarea.setFrameShadow(QFrame.Plain)
        self.guider_scrollarea.setLineWidth(0)
        self.guider_scrollarea.setWidgetResizable(True)
        self.guider_scrollarea.setAlignment(Qt.AlignCenter)
        self.guiderscrollareawidgetcontents = QWidget()
        self.guiderscrollareawidgetcontents.setObjectName(u"guiderscrollareawidgetcontents")
        self.guiderscrollareawidgetcontents.setGeometry(QRect(0, 0, 510, 102))
        self.verticalLayout_6 = QVBoxLayout(self.guiderscrollareawidgetcontents)
        self.verticalLayout_6.setObjectName(u"verticalLayout_6")
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.guider_preview_label = QLabel(self.guiderscrollareawidgetcontents)
        self.guider_preview_label.setObjectName(u"guider_preview_label")
        self.guider_preview_label.setAlignment(Qt.AlignCenter)

        self.verticalLayout_6.addWidget(self.guider_preview_label, 0, Qt.AlignHCenter|Qt.AlignVCenter)

        self.guider_scrollarea.setWidget(self.guiderscrollareawidgetcontents)

        self.verticalLayout_10.addWidget(self.guider_scrollarea)

        self.guider_gridlayout = QGridLayout()
        self.guider_gridlayout.setObjectName(u"guider_gridlayout")
        self.guiderzoom_label = QLabel(self.dockwidgetcontents_3)
        self.guiderzoom_label.setObjectName(u"guiderzoom_label")
        sizePolicy.setHeightForWidth(self.guiderzoom_label.sizePolicy().hasHeightForWidth())
        self.guiderzoom_label.setSizePolicy(sizePolicy)

        self.guider_gridlayout.addWidget(self.guiderzoom_label, 0, 0, 1, 1)

        self.guiderzoom_spinbox = QSpinBox(self.dockwidgetcontents_3)
        self.guiderzoom_spinbox.setObjectName(u"guiderzoom_spinbox")
        self.guiderzoom_spinbox.setMinimum(20)
        self.guiderzoom_spinbox.setMaximum(300)
        self.guiderzoom_spinbox.setValue(100)

        self.guider_gridlayout.addWidget(self.guiderzoom_spinbox, 0, 1, 1, 1)

        self.guiderzoom_slider = QSlider(self.dockwidgetcontents_3)
        self.guiderzoom_slider.setObjectName(u"guiderzoom_slider")
        sizePolicy2.setHeightForWidth(self.guiderzoom_slider.sizePolicy().hasHeightForWidth())
        self.guiderzoom_slider.setSizePolicy(sizePolicy2)
        self.guiderzoom_slider.setMinimum(20)
        self.guiderzoom_slider.setMaximum(300)
        self.guiderzoom_slider.setValue(100)
        self.guiderzoom_slider.setOrientation(Qt.Horizontal)

        self.guider_gridlayout.addWidget(self.guiderzoom_slider, 1, 0, 1, 2)

        self.guiderzoom_line = QFrame(self.dockwidgetcontents_3)
        self.guiderzoom_line.setObjectName(u"guiderzoom_line")
        self.guiderzoom_line.setFrameShape(QFrame.VLine)
        self.guiderzoom_line.setFrameShadow(QFrame.Sunken)

        self.guider_gridlayout.addWidget(self.guiderzoom_line, 0, 2, 2, 1)

        self.guidersetref_button = QPushButton(self.dockwidgetcontents_3)
        self.guidersetref_button.setObjectName(u"guidersetref_button")
        self.guidersetref_button.setEnabled(False)
        sizePolicy8 = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy8.setHorizontalStretch(0)
        sizePolicy8.setVerticalStretch(0)
        sizePolicy8.setHeightForWidth(self.guidersetref_button.sizePolicy().hasHeightForWidth())
        self.guidersetref_button.setSizePolicy(sizePolicy8)
        icon24 = QIcon()
        icon24.addFile(u":/icons/target.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.guidersetref_button.setIcon(icon24)
        self.guidersetref_button.setIconSize(QSize(24, 24))
        self.guidersetref_button.setAutoDefault(True)

        self.guider_gridlayout.addWidget(self.guidersetref_button, 0, 3, 2, 1)

        self.guiderzoom_spacer = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)

        self.guider_gridlayout.addItem(self.guiderzoom_spacer, 0, 4, 2, 1)


        self.verticalLayout_10.addLayout(self.guider_gridlayout)

        self.guider_dockwidget.setWidget(self.dockwidgetcontents_3)
        MainWindow.addDockWidget(Qt.RightDockWidgetArea, self.guider_dockwidget)
        self.filters_dockwidget = QDockWidget(MainWindow)
        self.filters_dockwidget.setObjectName(u"filters_dockwidget")
        sizePolicy7.setHeightForWidth(self.filters_dockwidget.sizePolicy().hasHeightForWidth())
        self.filters_dockwidget.setSizePolicy(sizePolicy7)
        self.filters_dockwidget.setFeatures(QDockWidget.DockWidgetFloatable|QDockWidget.DockWidgetMovable)
        self.filters_dockwidget.setAllowedAreas(Qt.LeftDockWidgetArea|Qt.RightDockWidgetArea)
        self.filters_dockwidgetcontents = QWidget()
        self.filters_dockwidgetcontents.setObjectName(u"filters_dockwidgetcontents")
        self.verticalLayout_5 = QVBoxLayout(self.filters_dockwidgetcontents)
        self.verticalLayout_5.setObjectName(u"verticalLayout_5")
        self.verticalLayout_5.setContentsMargins(0, 0, 0, -1)
        self.filter_table = QTableWidget(self.filters_dockwidgetcontents)
        if (self.filter_table.columnCount() < 5):
            self.filter_table.setColumnCount(5)
        __qtablewidgetitem6 = QTableWidgetItem()
        self.filter_table.setHorizontalHeaderItem(0, __qtablewidgetitem6)
        __qtablewidgetitem7 = QTableWidgetItem()
        self.filter_table.setHorizontalHeaderItem(1, __qtablewidgetitem7)
        __qtablewidgetitem8 = QTableWidgetItem()
        self.filter_table.setHorizontalHeaderItem(2, __qtablewidgetitem8)
        __qtablewidgetitem9 = QTableWidgetItem()
        self.filter_table.setHorizontalHeaderItem(3, __qtablewidgetitem9)
        __qtablewidgetitem10 = QTableWidgetItem()
        self.filter_table.setHorizontalHeaderItem(4, __qtablewidgetitem10)
        self.filter_table.setObjectName(u"filter_table")
        self.filter_table.setFrameShape(QFrame.NoFrame)
        self.filter_table.setLineWidth(0)
        self.filter_table.setSortingEnabled(False)

        self.verticalLayout_5.addWidget(self.filter_table)

        self.horizontallayout_14 = QHBoxLayout()
        self.horizontallayout_14.setObjectName(u"horizontallayout_14")
        self.horizontallayout_14.setContentsMargins(9, -1, 9, -1)
        self.addrow_button_2 = QPushButton(self.filters_dockwidgetcontents)
        self.addrow_button_2.setObjectName(u"addrow_button_2")
        sizePolicy.setHeightForWidth(self.addrow_button_2.sizePolicy().hasHeightForWidth())
        self.addrow_button_2.setSizePolicy(sizePolicy)
        self.addrow_button_2.setIcon(icon22)
        self.addrow_button_2.setAutoDefault(True)

        self.horizontallayout_14.addWidget(self.addrow_button_2)

        self.removerow_button_2 = QPushButton(self.filters_dockwidgetcontents)
        self.removerow_button_2.setObjectName(u"removerow_button_2")
        sizePolicy.setHeightForWidth(self.removerow_button_2.sizePolicy().hasHeightForWidth())
        self.removerow_button_2.setSizePolicy(sizePolicy)
        self.removerow_button_2.setIcon(icon23)
        self.removerow_button_2.setAutoDefault(True)

        self.horizontallayout_14.addWidget(self.removerow_button_2)

        self.horizontalSpacer_4 = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)

        self.horizontallayout_14.addItem(self.horizontalSpacer_4)

        self.changes_label_2 = QLabel(self.filters_dockwidgetcontents)
        self.changes_label_2.setObjectName(u"changes_label_2")
        sizePolicy.setHeightForWidth(self.changes_label_2.sizePolicy().hasHeightForWidth())
        self.changes_label_2.setSizePolicy(sizePolicy)
        self.changes_label_2.setAlignment(Qt.AlignCenter)

        self.horizontallayout_14.addWidget(self.changes_label_2, 0, Qt.AlignRight)


        self.verticalLayout_5.addLayout(self.horizontallayout_14)

        self.filters_dockwidget.setWidget(self.filters_dockwidgetcontents)
        MainWindow.addDockWidget(Qt.RightDockWidgetArea, self.filters_dockwidget)
        self.settings_dockwidget = QDockWidget(MainWindow)
        self.settings_dockwidget.setObjectName(u"settings_dockwidget")
        self.settings_dockwidget.setFeatures(QDockWidget.DockWidgetFloatable|QDockWidget.DockWidgetMovable)
        self.settings_dockwidget.setAllowedAreas(Qt.LeftDockWidgetArea|Qt.RightDockWidgetArea)
        self.dockWidgetContents = QWidget()
        self.dockWidgetContents.setObjectName(u"dockWidgetContents")
        self.verticalLayout_8 = QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout_8.setObjectName(u"verticalLayout_8")
        self.scrollArea = QScrollArea(self.dockWidgetContents)
        self.scrollArea.setObjectName(u"scrollArea")
        self.scrollArea.setFrameShape(QFrame.NoFrame)
        self.scrollArea.setFrameShadow(QFrame.Plain)
        self.scrollArea.setWidgetResizable(True)
        self.scrollAreaWidgetContents = QWidget()
        self.scrollAreaWidgetContents.setObjectName(u"scrollAreaWidgetContents")
        self.scrollAreaWidgetContents.setGeometry(QRect(0, -67, 471, 382))
        self.verticalLayout_11 = QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_11.setObjectName(u"verticalLayout_11")
        self.groupBox_2 = QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.formLayout_2 = QFormLayout(self.groupBox_2)
        self.formLayout_2.setObjectName(u"formLayout_2")
        self.focuser_checkbox = QCheckBox(self.groupBox_2)
        self.focuser_checkbox.setObjectName(u"focuser_checkbox")

        self.formLayout_2.setWidget(4, QFormLayout.LabelRole, self.focuser_checkbox)

        self.filter_wheel_checkbox = QCheckBox(self.groupBox_2)
        self.filter_wheel_checkbox.setObjectName(u"filter_wheel_checkbox")

        self.formLayout_2.setWidget(3, QFormLayout.LabelRole, self.filter_wheel_checkbox)

        self.camera_checkbox = QCheckBox(self.groupBox_2)
        self.camera_checkbox.setObjectName(u"camera_checkbox")

        self.formLayout_2.setWidget(2, QFormLayout.LabelRole, self.camera_checkbox)

        self.guider_checkbox = QCheckBox(self.groupBox_2)
        self.guider_checkbox.setObjectName(u"guider_checkbox")

        self.formLayout_2.setWidget(1, QFormLayout.LabelRole, self.guider_checkbox)

        self.telescope_checkbox = QCheckBox(self.groupBox_2)
        self.telescope_checkbox.setObjectName(u"telescope_checkbox")

        self.formLayout_2.setWidget(0, QFormLayout.LabelRole, self.telescope_checkbox)

        self.horizontallayout_9 = QHBoxLayout()
        self.horizontallayout_9.setObjectName(u"horizontallayout_9")
        self.telescope_name_label = QLabel(self.groupBox_2)
        self.telescope_name_label.setObjectName(u"telescope_name_label")
        sizePolicy7.setHeightForWidth(self.telescope_name_label.sizePolicy().hasHeightForWidth())
        self.telescope_name_label.setSizePolicy(sizePolicy7)
        self.telescope_name_label.setWordWrap(True)

        self.horizontallayout_9.addWidget(self.telescope_name_label)

        self.scope_settings_btn = QToolButton(self.groupBox_2)
        self.scope_settings_btn.setObjectName(u"scope_settings_btn")
        self.scope_settings_btn.setEnabled(False)
        sizePolicy.setHeightForWidth(self.scope_settings_btn.sizePolicy().hasHeightForWidth())
        self.scope_settings_btn.setSizePolicy(sizePolicy)
        self.scope_settings_btn.setIcon(icon9)
        self.scope_settings_btn.setPopupMode(QToolButton.InstantPopup)

        self.horizontallayout_9.addWidget(self.scope_settings_btn)


        self.formLayout_2.setLayout(0, QFormLayout.FieldRole, self.horizontallayout_9)

        self.horizontallayout_10 = QHBoxLayout()
        self.horizontallayout_10.setObjectName(u"horizontallayout_10")
        self.guider_name_label = QLabel(self.groupBox_2)
        self.guider_name_label.setObjectName(u"guider_name_label")
        sizePolicy7.setHeightForWidth(self.guider_name_label.sizePolicy().hasHeightForWidth())
        self.guider_name_label.setSizePolicy(sizePolicy7)
        self.guider_name_label.setWordWrap(True)

        self.horizontallayout_10.addWidget(self.guider_name_label)

        self.guider_settings_btn = QToolButton(self.groupBox_2)
        self.guider_settings_btn.setObjectName(u"guider_settings_btn")
        self.guider_settings_btn.setEnabled(False)
        sizePolicy.setHeightForWidth(self.guider_settings_btn.sizePolicy().hasHeightForWidth())
        self.guider_settings_btn.setSizePolicy(sizePolicy)
        self.guider_settings_btn.setIcon(icon9)
        self.guider_settings_btn.setPopupMode(QToolButton.InstantPopup)

        self.horizontallayout_10.addWidget(self.guider_settings_btn)


        self.formLayout_2.setLayout(1, QFormLayout.FieldRole, self.horizontallayout_10)

        self.horizontallayout_11 = QHBoxLayout()
        self.horizontallayout_11.setObjectName(u"horizontallayout_11")
        self.camera_name_label = QLabel(self.groupBox_2)
        self.camera_name_label.setObjectName(u"camera_name_label")
        sizePolicy7.setHeightForWidth(self.camera_name_label.sizePolicy().hasHeightForWidth())
        self.camera_name_label.setSizePolicy(sizePolicy7)
        self.camera_name_label.setWordWrap(True)

        self.horizontallayout_11.addWidget(self.camera_name_label)

        self.camera_settings_btn = QToolButton(self.groupBox_2)
        self.camera_settings_btn.setObjectName(u"camera_settings_btn")
        self.camera_settings_btn.setEnabled(False)
        sizePolicy.setHeightForWidth(self.camera_settings_btn.sizePolicy().hasHeightForWidth())
        self.camera_settings_btn.setSizePolicy(sizePolicy)
        self.camera_settings_btn.setIcon(icon9)
        self.camera_settings_btn.setPopupMode(QToolButton.InstantPopup)

        self.horizontallayout_11.addWidget(self.camera_settings_btn)


        self.formLayout_2.setLayout(2, QFormLayout.FieldRole, self.horizontallayout_11)

        self.horizontallayout_13 = QHBoxLayout()
        self.horizontallayout_13.setObjectName(u"horizontallayout_13")
        self.wheel_name_label = QLabel(self.groupBox_2)
        self.wheel_name_label.setObjectName(u"wheel_name_label")
        sizePolicy7.setHeightForWidth(self.wheel_name_label.sizePolicy().hasHeightForWidth())
        self.wheel_name_label.setSizePolicy(sizePolicy7)
        self.wheel_name_label.setWordWrap(True)

        self.horizontallayout_13.addWidget(self.wheel_name_label)

        self.wheel_settings_btn = QToolButton(self.groupBox_2)
        self.wheel_settings_btn.setObjectName(u"wheel_settings_btn")
        self.wheel_settings_btn.setEnabled(False)
        sizePolicy.setHeightForWidth(self.wheel_settings_btn.sizePolicy().hasHeightForWidth())
        self.wheel_settings_btn.setSizePolicy(sizePolicy)
        self.wheel_settings_btn.setIcon(icon9)
        self.wheel_settings_btn.setPopupMode(QToolButton.InstantPopup)

        self.horizontallayout_13.addWidget(self.wheel_settings_btn)


        self.formLayout_2.setLayout(3, QFormLayout.FieldRole, self.horizontallayout_13)

        self.horizontallayout_12 = QHBoxLayout()
        self.horizontallayout_12.setObjectName(u"horizontallayout_12")
        self.focuser_name_label = QLabel(self.groupBox_2)
        self.focuser_name_label.setObjectName(u"focuser_name_label")
        sizePolicy7.setHeightForWidth(self.focuser_name_label.sizePolicy().hasHeightForWidth())
        self.focuser_name_label.setSizePolicy(sizePolicy7)
        self.focuser_name_label.setWordWrap(True)

        self.horizontallayout_12.addWidget(self.focuser_name_label)

        self.focuser_settings_btn = QToolButton(self.groupBox_2)
        self.focuser_settings_btn.setObjectName(u"focuser_settings_btn")
        self.focuser_settings_btn.setEnabled(False)
        sizePolicy.setHeightForWidth(self.focuser_settings_btn.sizePolicy().hasHeightForWidth())
        self.focuser_settings_btn.setSizePolicy(sizePolicy)
        self.focuser_settings_btn.setIcon(icon9)
        self.focuser_settings_btn.setPopupMode(QToolButton.InstantPopup)

        self.horizontallayout_12.addWidget(self.focuser_settings_btn)


        self.formLayout_2.setLayout(4, QFormLayout.FieldRole, self.horizontallayout_12)


        self.verticalLayout_11.addWidget(self.groupBox_2)

        self.groupBox = QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox.setObjectName(u"groupBox")
        self.gridLayout_5 = QGridLayout(self.groupBox)
        self.gridLayout_5.setObjectName(u"gridLayout_5")
        self.lat_m_spin = QSpinBox(self.groupBox)
        self.lat_m_spin.setObjectName(u"lat_m_spin")
        self.lat_m_spin.setFrame(True)
        self.lat_m_spin.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.lat_m_spin.setKeyboardTracking(False)
        self.lat_m_spin.setProperty("showGroupSeparator", False)
        self.lat_m_spin.setMaximum(59)

        self.gridLayout_5.addWidget(self.lat_m_spin, 0, 2, 1, 1)

        self.long_s_spin = QSpinBox(self.groupBox)
        self.long_s_spin.setObjectName(u"long_s_spin")
        self.long_s_spin.setFrame(True)
        self.long_s_spin.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.long_s_spin.setKeyboardTracking(False)
        self.long_s_spin.setProperty("showGroupSeparator", False)
        self.long_s_spin.setMaximum(59)

        self.gridLayout_5.addWidget(self.long_s_spin, 1, 3, 1, 1)

        self.long_d_spin = QSpinBox(self.groupBox)
        self.long_d_spin.setObjectName(u"long_d_spin")
        self.long_d_spin.setFrame(True)
        self.long_d_spin.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.long_d_spin.setKeyboardTracking(False)
        self.long_d_spin.setProperty("showGroupSeparator", False)
        self.long_d_spin.setMinimum(-179)
        self.long_d_spin.setMaximum(179)

        self.gridLayout_5.addWidget(self.long_d_spin, 1, 1, 1, 1)

        self.lat_s_spin = QSpinBox(self.groupBox)
        self.lat_s_spin.setObjectName(u"lat_s_spin")
        self.lat_s_spin.setFrame(True)
        self.lat_s_spin.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.lat_s_spin.setKeyboardTracking(False)
        self.lat_s_spin.setProperty("showGroupSeparator", False)
        self.lat_s_spin.setMaximum(59)

        self.gridLayout_5.addWidget(self.lat_s_spin, 0, 3, 1, 1)

        self.long_label = QLabel(self.groupBox)
        self.long_label.setObjectName(u"long_label")

        self.gridLayout_5.addWidget(self.long_label, 1, 0, 1, 1)

        self.long_m_spin = QSpinBox(self.groupBox)
        self.long_m_spin.setObjectName(u"long_m_spin")
        self.long_m_spin.setFrame(True)
        self.long_m_spin.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.long_m_spin.setKeyboardTracking(False)
        self.long_m_spin.setProperty("showGroupSeparator", False)
        self.long_m_spin.setMaximum(59)

        self.gridLayout_5.addWidget(self.long_m_spin, 1, 2, 1, 1)

        self.lat_d_spin = QSpinBox(self.groupBox)
        self.lat_d_spin.setObjectName(u"lat_d_spin")
        self.lat_d_spin.setFrame(True)
        self.lat_d_spin.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.lat_d_spin.setKeyboardTracking(False)
        self.lat_d_spin.setProperty("showGroupSeparator", False)
        self.lat_d_spin.setMinimum(-89)
        self.lat_d_spin.setMaximum(89)

        self.gridLayout_5.addWidget(self.lat_d_spin, 0, 1, 1, 1)

        self.lat_label = QLabel(self.groupBox)
        self.lat_label.setObjectName(u"lat_label")

        self.gridLayout_5.addWidget(self.lat_label, 0, 0, 1, 1)


        self.verticalLayout_11.addWidget(self.groupBox)

        self.verticalSpacer = QSpacerItem(20, 40, QSizePolicy.Minimum, QSizePolicy.Expanding)

        self.verticalLayout_11.addItem(self.verticalSpacer)

        self.scrollArea.setWidget(self.scrollAreaWidgetContents)

        self.verticalLayout_8.addWidget(self.scrollArea)

        self.settings_dockwidget.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(Qt.RightDockWidgetArea, self.settings_dockwidget)
        QWidget.setTabOrder(self.mount_group, self.scrollarea)
        QWidget.setTabOrder(self.scrollarea, self.scope_settings_btn)
        QWidget.setTabOrder(self.scope_settings_btn, self.slewnorthwest_button)
        QWidget.setTabOrder(self.slewnorthwest_button, self.slewnorth_button)
        QWidget.setTabOrder(self.slewnorth_button, self.slewnortheast_button)
        QWidget.setTabOrder(self.slewnortheast_button, self.slewwest_button)
        QWidget.setTabOrder(self.slewwest_button, self.slewstop_button)
        QWidget.setTabOrder(self.slewstop_button, self.sleweast_button)
        QWidget.setTabOrder(self.sleweast_button, self.slewsouthwest_button)
        QWidget.setTabOrder(self.slewsouthwest_button, self.slewsouth_button)
        QWidget.setTabOrder(self.slewsouth_button, self.slewsoutheast_button)
        QWidget.setTabOrder(self.slewsoutheast_button, self.mount_trackrate_spin)
        QWidget.setTabOrder(self.mount_trackrate_spin, self.object_combobox)
        QWidget.setTabOrder(self.object_combobox, self.goto_button)
        QWidget.setTabOrder(self.goto_button, self.guider_group)
        QWidget.setTabOrder(self.guider_group, self.guider_settings_btn)
        QWidget.setTabOrder(self.guider_settings_btn, self.guider_exposure_spinbox)
        QWidget.setTabOrder(self.guider_exposure_spinbox, self.guider_exposure_slider)
        QWidget.setTabOrder(self.guider_exposure_slider, self.guider_gain_spinbox)
        QWidget.setTabOrder(self.guider_gain_spinbox, self.guider_gain_slider)
        QWidget.setTabOrder(self.guider_gain_slider, self.guider_loop_button)
        QWidget.setTabOrder(self.guider_loop_button, self.guider_start_button)
        QWidget.setTabOrder(self.guider_start_button, self.camera_group)
        QWidget.setTabOrder(self.camera_group, self.camera_settings_btn)
        QWidget.setTabOrder(self.camera_settings_btn, self.camera_exposure_spinbox)
        QWidget.setTabOrder(self.camera_exposure_spinbox, self.camera_exposure_slider)
        QWidget.setTabOrder(self.camera_exposure_slider, self.camera_gain_spinbox)
        QWidget.setTabOrder(self.camera_gain_spinbox, self.camera_gain_slider)
        QWidget.setTabOrder(self.camera_gain_slider, self.camera_integration_spinbox)
        QWidget.setTabOrder(self.camera_integration_spinbox, self.camera_format_combobox)
        QWidget.setTabOrder(self.camera_format_combobox, self.camera_loop_button)
        QWidget.setTabOrder(self.camera_loop_button, self.camera_capture_button)
        QWidget.setTabOrder(self.camera_capture_button, self.focuser_group)
        QWidget.setTabOrder(self.focuser_group, self.focuser_settings_btn)
        QWidget.setTabOrder(self.focuser_settings_btn, self.focuser_position_spinbox)
        QWidget.setTabOrder(self.focuser_position_spinbox, self.temp_checkbox)
        QWidget.setTabOrder(self.temp_checkbox, self.wheel_settings_btn)
        QWidget.setTabOrder(self.wheel_settings_btn, self.position_combobox)
        QWidget.setTabOrder(self.position_combobox, self.schedule_table)
        QWidget.setTabOrder(self.schedule_table, self.addrow_button)
        QWidget.setTabOrder(self.addrow_button, self.removerow_button)
        QWidget.setTabOrder(self.removerow_button, self.camera_scrollarea)
        QWidget.setTabOrder(self.camera_scrollarea, self.guider_scrollarea)

        self.menubar.addAction(self.file_menu.menuAction())
        self.menubar.addAction(self.menu_edit.menuAction())
        self.menubar.addAction(self.help_menu.menuAction())
        self.file_menu.addAction(self.import_menu.menuAction())
        self.file_menu.addAction(self.menuExport.menuAction())
        self.file_menu.addSeparator()
        self.file_menu.addAction(self.action_exit)
        self.import_menu.addAction(self.importfilters_action)
        self.import_menu.addAction(self.importschedule_action)
        self.menuExport.addAction(self.actionFilters)
        self.menuExport.addAction(self.actionSchedule)
        self.menu_edit.addAction(self.menu_equipment.menuAction())
        self.menu_edit.addAction(self.filters_action)
        self.menu_edit.addAction(self.location_action)
        self.menu_equipment.addAction(self.telescope_action)
        self.menu_equipment.addAction(self.guider_action)
        self.menu_equipment.addAction(self.camera_action)
        self.menu_equipment.addAction(self.wheel_action)
        self.menu_equipment.addAction(self.focuser_action)
        self.help_menu.addAction(self.action_about)

        self.retranslateUi(MainWindow)
        self.guider_exposure_slider.valueChanged.connect(self.guider_exposure_spinbox.setValue)
        self.guider_gain_slider.valueChanged.connect(self.guider_gain_spinbox.setValue)
        self.camera_gain_slider.valueChanged.connect(self.camera_gain_spinbox.setValue)
        self.camera_exposure_slider.valueChanged.connect(self.camera_exposure_spinbox.setValue)
        self.guider_exposure_spinbox.valueChanged.connect(self.guider_exposure_slider.setValue)
        self.camera_gain_spinbox.valueChanged.connect(self.camera_gain_slider.setValue)
        self.guider_gain_spinbox.valueChanged.connect(self.guider_gain_slider.setValue)
        self.camera_exposure_spinbox.valueChanged.connect(self.camera_exposure_slider.setValue)
        self.camera_capture_button.clicked.connect(self.camera_dockwidget.raise_)
        self.camera_loop_button.clicked.connect(self.camera_dockwidget.raise_)
        self.guider_start_button.clicked.connect(self.guider_dockwidget.raise_)
        self.guider_loop_button.clicked.connect(self.guider_dockwidget.raise_)
        self.guider_exposure_spinbox.valueChanged.connect(self.guider_dockwidget.raise_)
        self.guider_gain_spinbox.valueChanged.connect(self.guider_dockwidget.raise_)
        self.camera_exposure_spinbox.valueChanged.connect(self.camera_dockwidget.raise_)
        self.camera_gain_spinbox.valueChanged.connect(self.camera_dockwidget.raise_)
        self.guider_loop_button.toggled.connect(self.guider_start_button.setEnabled)
        self.camera_loop_button.toggled.connect(self.camera_capture_button.setEnabled)
        self.telescope_checkbox.toggled.connect(self.telescope_action.setChecked)
        self.guider_group.toggled.connect(self.guider_action.setChecked)
        self.camera_group.toggled.connect(self.camera_action.setChecked)
        self.focuser_checkbox.toggled.connect(self.focuser_action.setChecked)
        self.filter_wheel_checkbox.toggled.connect(self.wheel_action.setChecked)
        self.telescope_action.toggled.connect(self.mount_group.setEnabled)
        self.guider_action.toggled.connect(self.guider_group.setEnabled)
        self.filter_wheel_checkbox.toggled.connect(self.wheel_group.setEnabled)
        self.camera_action.toggled.connect(self.camera_group.setChecked)
        self.focuser_action.toggled.connect(self.focuser_group.setEnabled)
        self.filters_action.triggered.connect(self.filters_dockwidget.raise_)
        self.action_exit.triggered.connect(MainWindow.close)
        self.camera_capture_button.toggled.connect(self.camera_loop_button.setDisabled)
        self.guider_start_button.toggled.connect(self.guider_loop_button.setDisabled)
        self.camera_capture_button.toggled.connect(self.camera_filter_combobox.setDisabled)
        self.camera_capture_button.toggled.connect(self.camera_filter_label.setDisabled)
        self.camera_capture_button.toggled.connect(self.camera_format_label.setDisabled)
        self.camera_capture_button.toggled.connect(self.camera_format_combobox.setDisabled)
        self.filter_wheel_checkbox.toggled.connect(self.camera_filter_label.setHidden)
        self.filter_wheel_checkbox.toggled.connect(self.camera_filter_combobox.setHidden)
        self.camera_integration_checkbox.toggled.connect(self.camera_integration_spinbox.setEnabled)
        self.camera_zoom_slider.valueChanged.connect(self.camera_zoom_spinbox.setValue)
        self.camera_zoom_spinbox.valueChanged.connect(self.camera_zoom_slider.setValue)
        self.guiderzoom_slider.valueChanged.connect(self.guiderzoom_spinbox.setValue)
        self.guiderzoom_spinbox.valueChanged.connect(self.guiderzoom_slider.setValue)
        self.telescope_checkbox.toggled.connect(self.scope_settings_btn.setEnabled)
        self.guider_checkbox.toggled.connect(self.guider_settings_btn.setEnabled)
        self.camera_checkbox.toggled.connect(self.camera_settings_btn.setEnabled)
        self.filter_wheel_checkbox.toggled.connect(self.wheel_settings_btn.setEnabled)
        self.focuser_checkbox.toggled.connect(self.focuser_settings_btn.setEnabled)
        self.telescope_checkbox.toggled.connect(self.mount_group.setEnabled)
        self.guider_checkbox.toggled.connect(self.guider_group.setEnabled)
        self.camera_checkbox.toggled.connect(self.camera_group.setEnabled)
        self.filter_wheel_checkbox.toggled.connect(self.wheel_group.setEnabled)
        self.focuser_checkbox.toggled.connect(self.focuser_group.setEnabled)
        self.telescope_action.toggled.connect(self.telescope_checkbox.setChecked)
        self.guider_checkbox.toggled.connect(self.guider_action.setChecked)
        self.guider_action.toggled.connect(self.guider_checkbox.setChecked)
        self.camera_checkbox.toggled.connect(self.camera_action.setChecked)
        self.camera_action.toggled.connect(self.camera_checkbox.setChecked)
        self.wheel_action.toggled.connect(self.filter_wheel_checkbox.setChecked)
        self.focuser_action.toggled.connect(self.focuser_checkbox.setChecked)

        self.guidersetref_button.setDefault(False)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Ecliptic", None))
        self.filters_action.setText(QCoreApplication.translate("MainWindow", u"Filters", None))
#if QT_CONFIG(shortcut)
        self.filters_action.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+F", None))
#endif // QT_CONFIG(shortcut)
        self.location_action.setText(QCoreApplication.translate("MainWindow", u"Location", None))
#if QT_CONFIG(shortcut)
        self.location_action.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+L", None))
#endif // QT_CONFIG(shortcut)
        self.targets_action.setText(QCoreApplication.translate("MainWindow", u"Targets", None))
#if QT_CONFIG(shortcut)
        self.targets_action.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+T", None))
#endif // QT_CONFIG(shortcut)
        self.action_undo.setText(QCoreApplication.translate("MainWindow", u"Undo", None))
#if QT_CONFIG(shortcut)
        self.action_undo.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Z", None))
#endif // QT_CONFIG(shortcut)
        self.action_redo.setText(QCoreApplication.translate("MainWindow", u"Redo", None))
#if QT_CONFIG(shortcut)
        self.action_redo.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Y", None))
#endif // QT_CONFIG(shortcut)
        self.action_about.setText(QCoreApplication.translate("MainWindow", u"About", None))
        self.telescope_action.setText(QCoreApplication.translate("MainWindow", u"Telescope", None))
        self.guider_action.setText(QCoreApplication.translate("MainWindow", u"Guider", None))
        self.camera_action.setText(QCoreApplication.translate("MainWindow", u"Camera", None))
        self.focuser_action.setText(QCoreApplication.translate("MainWindow", u"Focuser", None))
        self.wheel_action.setText(QCoreApplication.translate("MainWindow", u"Filter Wheel", None))
        self.importschedule_action.setText(QCoreApplication.translate("MainWindow", u"Schedule", None))
        self.importfilters_action.setText(QCoreApplication.translate("MainWindow", u"Filters", None))
        self.savelocation_action.setText(QCoreApplication.translate("MainWindow", u"Save Location", None))
        self.action_exit.setText(QCoreApplication.translate("MainWindow", u"Exit", None))
#if QT_CONFIG(shortcut)
        self.action_exit.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Q", None))
#endif // QT_CONFIG(shortcut)
        self.actionFilters.setText(QCoreApplication.translate("MainWindow", u"Filters", None))
        self.actionSchedule.setText(QCoreApplication.translate("MainWindow", u"Schedule", None))
        self.ascomcamerasettings_action.setText(QCoreApplication.translate("MainWindow", u"ASCOM Settings", None))
        self.ascomguidersettings_action.setText(QCoreApplication.translate("MainWindow", u"ASCOM Settings", None))
        self.mount_group.setTitle(QCoreApplication.translate("MainWindow", u"Telescope", None))
#if QT_CONFIG(tooltip)
        self.slewnorth_button.setToolTip(QCoreApplication.translate("MainWindow", u"Slew the mount north", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.slewsouthwest_button.setToolTip(QCoreApplication.translate("MainWindow", u"Slew the mount west", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.sleweast_button.setToolTip(QCoreApplication.translate("MainWindow", u"Slew the mount east", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.slewnorthwest_button.setToolTip(QCoreApplication.translate("MainWindow", u"Slew the mount north", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.slewsoutheast_button.setToolTip(QCoreApplication.translate("MainWindow", u"Slew the mount south", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.slewstop_button.setToolTip(QCoreApplication.translate("MainWindow", u"Slew the mount west", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.slewwest_button.setToolTip(QCoreApplication.translate("MainWindow", u"Slew the mount west", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.slewsouth_button.setToolTip(QCoreApplication.translate("MainWindow", u"Slew the mount south", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.slewnortheast_button.setToolTip(QCoreApplication.translate("MainWindow", u"Slew the mount east", None))
#endif // QT_CONFIG(tooltip)
        self.mount_trackrate_label.setText(QCoreApplication.translate("MainWindow", u"Rate", None))
        self.mount_trackrate_spin.setPrefix(QCoreApplication.translate("MainWindow", u"~", None))
        self.mount_trackrate_spin.setSuffix(QCoreApplication.translate("MainWindow", u"\u00b0/s", None))
        self.object_label.setText(QCoreApplication.translate("MainWindow", u"Target", None))
#if QT_CONFIG(tooltip)
        self.goto_button.setToolTip(QCoreApplication.translate("MainWindow", u"Go to target", None))
#endif // QT_CONFIG(tooltip)
        self.goto_button.setText("")
        self.guider_group.setTitle(QCoreApplication.translate("MainWindow", u"Guider", None))
        self.guider_exposure_label.setText(QCoreApplication.translate("MainWindow", u"Exposure", None))
        self.guider_exposure_spinbox.setSuffix(QCoreApplication.translate("MainWindow", u"ms", None))
        self.guider_gain_label.setText(QCoreApplication.translate("MainWindow", u"Gain", None))
        self.guider_gain_spinbox.setSuffix(QCoreApplication.translate("MainWindow", u"e/adu", None))
        self.camera_group.setTitle(QCoreApplication.translate("MainWindow", u"Camera", None))
        self.camera_gain_spinbox.setSuffix(QCoreApplication.translate("MainWindow", u"e/adu", None))
        self.camera_integration_spinbox.setSuffix(QCoreApplication.translate("MainWindow", u"s", None))
        self.camera_exposure_label.setText(QCoreApplication.translate("MainWindow", u"Exposure", None))
        self.camera_gain_label.setText(QCoreApplication.translate("MainWindow", u"Gain", None))
        self.camera_format_label.setText(QCoreApplication.translate("MainWindow", u"Format", None))
        self.camera_exposure_spinbox.setSuffix(QCoreApplication.translate("MainWindow", u"ms", None))
        self.camera_filter_label.setText(QCoreApplication.translate("MainWindow", u"Filter", None))
        self.camera_integration_checkbox.setText(QCoreApplication.translate("MainWindow", u"Integration", None))
        self.wheel_group.setTitle(QCoreApplication.translate("MainWindow", u"Filter Wheel", None))
        self.position_label.setText(QCoreApplication.translate("MainWindow", u"Position", None))
        self.focuser_group.setTitle(QCoreApplication.translate("MainWindow", u"Focuser", None))
        self.temp_checkbox.setText(QCoreApplication.translate("MainWindow", u"Temp Comp", None))
        self.focuser_position_label.setText(QCoreApplication.translate("MainWindow", u"Position", None))
        self.file_menu.setTitle(QCoreApplication.translate("MainWindow", u"File", None))
        self.import_menu.setTitle(QCoreApplication.translate("MainWindow", u"Import", None))
        self.menuExport.setTitle(QCoreApplication.translate("MainWindow", u"Export", None))
        self.menu_edit.setTitle(QCoreApplication.translate("MainWindow", u"Edit", None))
        self.menu_equipment.setTitle(QCoreApplication.translate("MainWindow", u"Equipment", None))
        self.help_menu.setTitle(QCoreApplication.translate("MainWindow", u"Help", None))
        self.schedule_dockwidget.setWindowTitle(QCoreApplication.translate("MainWindow", u"Schedule", None))
        ___qtablewidgetitem = self.schedule_table.horizontalHeaderItem(0)
        ___qtablewidgetitem.setText(QCoreApplication.translate("MainWindow", u"Time", None));
#if QT_CONFIG(tooltip)
        ___qtablewidgetitem.setToolTip(QCoreApplication.translate("MainWindow", u"Time to initiate the event.", None));
#endif // QT_CONFIG(tooltip)
        ___qtablewidgetitem1 = self.schedule_table.horizontalHeaderItem(1)
        ___qtablewidgetitem1.setText(QCoreApplication.translate("MainWindow", u"Target", None));
#if QT_CONFIG(tooltip)
        ___qtablewidgetitem1.setToolTip(QCoreApplication.translate("MainWindow", u"The target to aim at.", None));
#endif // QT_CONFIG(tooltip)
        ___qtablewidgetitem2 = self.schedule_table.horizontalHeaderItem(2)
        ___qtablewidgetitem2.setText(QCoreApplication.translate("MainWindow", u"Filter", None));
#if QT_CONFIG(tooltip)
        ___qtablewidgetitem2.setToolTip(QCoreApplication.translate("MainWindow", u"The filter to use", None));
#endif // QT_CONFIG(tooltip)
        ___qtablewidgetitem3 = self.schedule_table.horizontalHeaderItem(3)
        ___qtablewidgetitem3.setText(QCoreApplication.translate("MainWindow", u"Exposure", None));
#if QT_CONFIG(tooltip)
        ___qtablewidgetitem3.setToolTip(QCoreApplication.translate("MainWindow", u"How long to expose 1 frame", None));
#endif // QT_CONFIG(tooltip)
        ___qtablewidgetitem4 = self.schedule_table.horizontalHeaderItem(4)
        ___qtablewidgetitem4.setText(QCoreApplication.translate("MainWindow", u"Gain", None));
#if QT_CONFIG(tooltip)
        ___qtablewidgetitem4.setToolTip(QCoreApplication.translate("MainWindow", u"The amount of gain to apply to an exposure", None));
#endif // QT_CONFIG(tooltip)
        ___qtablewidgetitem5 = self.schedule_table.horizontalHeaderItem(5)
        ___qtablewidgetitem5.setText(QCoreApplication.translate("MainWindow", u"Integration", None));
#if QT_CONFIG(tooltip)
        ___qtablewidgetitem5.setToolTip(QCoreApplication.translate("MainWindow", u"How long to capture frames per file", None));
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.addrow_button.setToolTip(QCoreApplication.translate("MainWindow", u"Add row", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.removerow_button.setToolTip(QCoreApplication.translate("MainWindow", u"Remove row", None))
#endif // QT_CONFIG(tooltip)
        self.schedule_date_label.setText(QCoreApplication.translate("MainWindow", u"Date", None))
        self.schedule_dateedit.setDisplayFormat(QCoreApplication.translate("MainWindow", u"yyyy-MM-dd", None))
        self.changes_label.setText(QCoreApplication.translate("MainWindow", u"Changes are saved automatically", None))
        self.camera_dockwidget.setWindowTitle(QCoreApplication.translate("MainWindow", u"Camera", None))
        self.camera_preview_label.setText("")
        self.camera_zoom_label.setText(QCoreApplication.translate("MainWindow", u"Zoom", None))
        self.camera_zoom_spinbox.setSuffix(QCoreApplication.translate("MainWindow", u"%", None))
        self.guider_dockwidget.setWindowTitle(QCoreApplication.translate("MainWindow", u"Guider", None))
        self.guider_preview_label.setText("")
        self.guiderzoom_label.setText(QCoreApplication.translate("MainWindow", u"Zoom", None))
        self.guiderzoom_spinbox.setSuffix(QCoreApplication.translate("MainWindow", u"%", None))
#if QT_CONFIG(tooltip)
        self.guidersetref_button.setToolTip(QCoreApplication.translate("MainWindow", u"Replace guide reference", None))
#endif // QT_CONFIG(tooltip)
        self.guidersetref_button.setText("")
        self.filters_dockwidget.setWindowTitle(QCoreApplication.translate("MainWindow", u"Filters", None))
        ___qtablewidgetitem6 = self.filter_table.horizontalHeaderItem(0)
        ___qtablewidgetitem6.setText(QCoreApplication.translate("MainWindow", u"Name", None));
#if QT_CONFIG(tooltip)
        ___qtablewidgetitem6.setToolTip(QCoreApplication.translate("MainWindow", u"The name of the filter", None));
#endif // QT_CONFIG(tooltip)
        ___qtablewidgetitem7 = self.filter_table.horizontalHeaderItem(1)
        ___qtablewidgetitem7.setText(QCoreApplication.translate("MainWindow", u"Brand", None));
        ___qtablewidgetitem8 = self.filter_table.horizontalHeaderItem(2)
        ___qtablewidgetitem8.setText(QCoreApplication.translate("MainWindow", u"Wheel Position", None));
#if QT_CONFIG(tooltip)
        ___qtablewidgetitem8.setToolTip(QCoreApplication.translate("MainWindow", u"The position the filter lies in the filter wheel", None));
#endif // QT_CONFIG(tooltip)
        ___qtablewidgetitem9 = self.filter_table.horizontalHeaderItem(3)
        ___qtablewidgetitem9.setText(QCoreApplication.translate("MainWindow", u"Lower Cutoff", None));
        ___qtablewidgetitem10 = self.filter_table.horizontalHeaderItem(4)
        ___qtablewidgetitem10.setText(QCoreApplication.translate("MainWindow", u"Upper Cutoff", None));
#if QT_CONFIG(tooltip)
        self.addrow_button_2.setToolTip(QCoreApplication.translate("MainWindow", u"Add row", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.removerow_button_2.setToolTip(QCoreApplication.translate("MainWindow", u"Remove row", None))
#endif // QT_CONFIG(tooltip)
        self.changes_label_2.setText(QCoreApplication.translate("MainWindow", u"Changes are saved automatically", None))
        self.settings_dockwidget.setWindowTitle(QCoreApplication.translate("MainWindow", u"Settings", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("MainWindow", u"Equipment", None))
        self.focuser_checkbox.setText(QCoreApplication.translate("MainWindow", u"Focuser", None))
        self.filter_wheel_checkbox.setText(QCoreApplication.translate("MainWindow", u"Filter Wheel", None))
        self.camera_checkbox.setText(QCoreApplication.translate("MainWindow", u"Camera", None))
        self.guider_checkbox.setText(QCoreApplication.translate("MainWindow", u"Guider", None))
        self.telescope_checkbox.setText(QCoreApplication.translate("MainWindow", u"Telescope", None))
        self.telescope_name_label.setText(QCoreApplication.translate("MainWindow", u"Not Connected", None))
        self.scope_settings_btn.setText("")
        self.guider_name_label.setText(QCoreApplication.translate("MainWindow", u"Not Connected", None))
        self.guider_settings_btn.setText("")
        self.camera_name_label.setText(QCoreApplication.translate("MainWindow", u"Not Connected", None))
        self.camera_settings_btn.setText("")
        self.wheel_name_label.setText(QCoreApplication.translate("MainWindow", u"Not Connected", None))
        self.wheel_settings_btn.setText("")
        self.focuser_name_label.setText(QCoreApplication.translate("MainWindow", u"Not Connected", None))
        self.focuser_settings_btn.setText("")
        self.groupBox.setTitle(QCoreApplication.translate("MainWindow", u"Location", None))
        self.lat_m_spin.setSuffix(QCoreApplication.translate("MainWindow", u"'", None))
        self.long_s_spin.setSuffix(QCoreApplication.translate("MainWindow", u"\"", None))
        self.long_d_spin.setSuffix(QCoreApplication.translate("MainWindow", u"\u00b0", None))
        self.lat_s_spin.setSuffix(QCoreApplication.translate("MainWindow", u"\"", None))
        self.long_label.setText(QCoreApplication.translate("MainWindow", u"Longitude", None))
        self.long_m_spin.setSuffix(QCoreApplication.translate("MainWindow", u"'", None))
        self.lat_d_spin.setSuffix(QCoreApplication.translate("MainWindow", u"\u00b0", None))
        self.lat_label.setText(QCoreApplication.translate("MainWindow", u"Latitude", None))
    # retranslateUi

