# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'connectcamera.ui',
# licensing of 'connectcamera.ui' applies.
#
# Created: Tue Jan 15 03:04:56 2019
#      by: pyside2-uic  running on PySide2 5.12.0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_ConnectCamera(object):
    def setupUi(self, ConnectCamera):
        ConnectCamera.setObjectName("ConnectCamera")
        ConnectCamera.resize(287, 259)
        ConnectCamera.setStyleSheet("QRadioButton{font: bold;}")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(ConnectCamera)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.stackedWidget = QtWidgets.QStackedWidget(ConnectCamera)
        self.stackedWidget.setObjectName("stackedWidget")
        self.camera_page = QtWidgets.QWidget()
        self.camera_page.setObjectName("camera_page")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.camera_page)
        self.verticalLayout.setObjectName("verticalLayout")
        self.instruct_label = QtWidgets.QLabel(self.camera_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.instruct_label.sizePolicy().hasHeightForWidth())
        self.instruct_label.setSizePolicy(sizePolicy)
        self.instruct_label.setWordWrap(True)
        self.instruct_label.setObjectName("instruct_label")
        self.verticalLayout.addWidget(self.instruct_label)
        self.ascom_commandlink = QtWidgets.QCommandLinkButton(self.camera_page)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/thirdparty/ascom_logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ascom_commandlink.setIcon(icon)
        self.ascom_commandlink.setObjectName("ascom_commandlink")
        self.verticalLayout.addWidget(self.ascom_commandlink)
        self.asi_commandlink = QtWidgets.QCommandLinkButton(self.camera_page)
        self.asi_commandlink.setEnabled(False)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/thirdparty/asi_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.asi_commandlink.setIcon(icon1)
        self.asi_commandlink.setObjectName("asi_commandlink")
        self.verticalLayout.addWidget(self.asi_commandlink)
        self.stackedWidget.addWidget(self.camera_page)
        self.asi_page = QtWidgets.QWidget()
        self.asi_page.setObjectName("asi_page")
        self.gridLayout = QtWidgets.QGridLayout(self.asi_page)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 2)
        self.label = QtWidgets.QLabel(self.asi_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 0, 1, 1)
        self.asi_combobox = QtWidgets.QComboBox(self.asi_page)
        self.asi_combobox.setObjectName("asi_combobox")
        self.gridLayout.addWidget(self.asi_combobox, 2, 1, 1, 1)
        self.asi_label = QtWidgets.QLabel(self.asi_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.asi_label.sizePolicy().hasHeightForWidth())
        self.asi_label.setSizePolicy(sizePolicy)
        self.asi_label.setWordWrap(True)
        self.asi_label.setObjectName("asi_label")
        self.gridLayout.addWidget(self.asi_label, 0, 0, 1, 2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 3, 1, 1, 1)
        self.asi_connect_button = QtWidgets.QPushButton(self.asi_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.asi_connect_button.sizePolicy().hasHeightForWidth())
        self.asi_connect_button.setSizePolicy(sizePolicy)
        self.asi_connect_button.setObjectName("asi_connect_button")
        self.gridLayout.addWidget(self.asi_connect_button, 2, 2, 1, 1)
        self.stackedWidget.addWidget(self.asi_page)
        self.verticalLayout_2.addWidget(self.stackedWidget)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.buttonbox = QtWidgets.QDialogButtonBox(ConnectCamera)
        self.buttonbox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonbox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel)
        self.buttonbox.setObjectName("buttonbox")
        self.verticalLayout_2.addWidget(self.buttonbox)

        self.retranslateUi(ConnectCamera)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonbox, QtCore.SIGNAL("accepted()"), ConnectCamera.accept)
        QtCore.QObject.connect(self.buttonbox, QtCore.SIGNAL("rejected()"), ConnectCamera.reject)
        QtCore.QMetaObject.connectSlotsByName(ConnectCamera)

    def retranslateUi(self, ConnectCamera):
        ConnectCamera.setWindowTitle(QtWidgets.QApplication.translate("ConnectCamera", "Solar System Sequencer - Connect Camera", None, -1))
        self.instruct_label.setText(QtWidgets.QApplication.translate("ConnectCamera", "Select the camera you would like to connect.", None, -1))
        self.ascom_commandlink.setText(QtWidgets.QApplication.translate("ConnectCamera", "ASCOM Camera", None, -1))
        self.ascom_commandlink.setDescription(QtWidgets.QApplication.translate("ConnectCamera", "Connect an ASCOM camera. Data acquisition is currently slow compared to ZWO ASI Cameras", None, -1))
        self.asi_commandlink.setText(QtWidgets.QApplication.translate("ConnectCamera", "ZWO ASI Camera", None, -1))
        self.asi_commandlink.setDescription(QtWidgets.QApplication.translate("ConnectCamera", "Connect a ZWO ASI camera.", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("ConnectCamera", "ZWO ASI Camera", None, -1))
        self.asi_label.setText(QtWidgets.QApplication.translate("ConnectCamera", "Connect a ZWO ASI camera.", None, -1))
        self.asi_connect_button.setText(QtWidgets.QApplication.translate("ConnectCamera", "Connect", None, -1))

import res_rc
