# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'schedulebrain.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ScheduleBrainDialog(object):
    def setupUi(self, ScheduleBrainDialog):
        ScheduleBrainDialog.setObjectName("ScheduleBrainDialog")
        ScheduleBrainDialog.resize(399, 145)
        self.gridLayout = QtWidgets.QGridLayout(ScheduleBrainDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.buttonbox = QtWidgets.QDialogButtonBox(ScheduleBrainDialog)
        self.buttonbox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonbox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonbox.setObjectName("buttonbox")
        self.gridLayout.addWidget(self.buttonbox, 2, 1, 1, 1)
        self.object_groupbox = QtWidgets.QGroupBox(ScheduleBrainDialog)
        self.object_groupbox.setObjectName("object_groupbox")
        self.formLayout_2 = QtWidgets.QFormLayout(self.object_groupbox)
        self.formLayout_2.setObjectName("formLayout_2")
        self.mercury_checkbox = QtWidgets.QCheckBox(self.object_groupbox)
        self.mercury_checkbox.setChecked(True)
        self.mercury_checkbox.setObjectName("mercury_checkbox")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.mercury_checkbox)
        self.saturn_checkbox = QtWidgets.QCheckBox(self.object_groupbox)
        self.saturn_checkbox.setChecked(True)
        self.saturn_checkbox.setObjectName("saturn_checkbox")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.saturn_checkbox)
        self.venus_checkbox = QtWidgets.QCheckBox(self.object_groupbox)
        self.venus_checkbox.setChecked(True)
        self.venus_checkbox.setObjectName("venus_checkbox")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.venus_checkbox)
        self.uranus_checkbox = QtWidgets.QCheckBox(self.object_groupbox)
        self.uranus_checkbox.setChecked(True)
        self.uranus_checkbox.setObjectName("uranus_checkbox")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.uranus_checkbox)
        self.mars_checkbox = QtWidgets.QCheckBox(self.object_groupbox)
        self.mars_checkbox.setChecked(True)
        self.mars_checkbox.setObjectName("mars_checkbox")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.mars_checkbox)
        self.neptune_checkbox = QtWidgets.QCheckBox(self.object_groupbox)
        self.neptune_checkbox.setChecked(True)
        self.neptune_checkbox.setObjectName("neptune_checkbox")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.neptune_checkbox)
        self.jupiter_checkbox = QtWidgets.QCheckBox(self.object_groupbox)
        self.jupiter_checkbox.setChecked(True)
        self.jupiter_checkbox.setObjectName("jupiter_checkbox")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.jupiter_checkbox)
        self.gridLayout.addWidget(self.object_groupbox, 1, 0, 2, 1)
        self.form_layout = QtWidgets.QFormLayout()
        self.form_layout.setObjectName("form_layout")
        self.darkness_label = QtWidgets.QLabel(ScheduleBrainDialog)
        self.darkness_label.setObjectName("darkness_label")
        self.form_layout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.darkness_label)
        self.darkness_combobox = QtWidgets.QComboBox(ScheduleBrainDialog)
        self.darkness_combobox.setObjectName("darkness_combobox")
        self.darkness_combobox.addItem("")
        self.darkness_combobox.addItem("")
        self.darkness_combobox.addItem("")
        self.darkness_combobox.addItem("")
        self.form_layout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.darkness_combobox)
        self.time_label = QtWidgets.QLabel(ScheduleBrainDialog)
        self.time_label.setObjectName("time_label")
        self.form_layout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.time_label)
        self.time_layout = QtWidgets.QHBoxLayout()
        self.time_layout.setObjectName("time_layout")
        self.start_timeedit = QtWidgets.QTimeEdit(ScheduleBrainDialog)
        self.start_timeedit.setMaximumTime(QtCore.QTime(23, 59, 58))
        self.start_timeedit.setTimeSpec(QtCore.Qt.LocalTime)
        self.start_timeedit.setTime(QtCore.QTime(0, 0, 0))
        self.start_timeedit.setObjectName("start_timeedit")
        self.time_layout.addWidget(self.start_timeedit)
        self.to_label = QtWidgets.QLabel(ScheduleBrainDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.to_label.sizePolicy().hasHeightForWidth())
        self.to_label.setSizePolicy(sizePolicy)
        self.to_label.setObjectName("to_label")
        self.time_layout.addWidget(self.to_label)
        self.end_timeedit = QtWidgets.QTimeEdit(ScheduleBrainDialog)
        self.end_timeedit.setDateTime(QtCore.QDateTime(QtCore.QDate(2000, 1, 1), QtCore.QTime(23, 59, 59)))
        self.end_timeedit.setMinimumTime(QtCore.QTime(0, 0, 1))
        self.end_timeedit.setTimeSpec(QtCore.Qt.LocalTime)
        self.end_timeedit.setObjectName("end_timeedit")
        self.time_layout.addWidget(self.end_timeedit)
        self.form_layout.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.time_layout)
        self.label = QtWidgets.QLabel(ScheduleBrainDialog)
        self.label.setObjectName("label")
        self.form_layout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.radioButton = QtWidgets.QRadioButton(ScheduleBrainDialog)
        self.radioButton.setObjectName("radioButton")
        self.horizontalLayout.addWidget(self.radioButton)
        self.radioButton_2 = QtWidgets.QRadioButton(ScheduleBrainDialog)
        self.radioButton_2.setObjectName("radioButton_2")
        self.horizontalLayout.addWidget(self.radioButton_2)
        self.form_layout.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout)
        self.gridLayout.addLayout(self.form_layout, 1, 1, 1, 1)
        self.plot_layout = QtWidgets.QHBoxLayout()
        self.plot_layout.setObjectName("plot_layout")
        self.gridLayout.addLayout(self.plot_layout, 0, 0, 1, 2)

        self.retranslateUi(ScheduleBrainDialog)
        self.buttonbox.accepted.connect(ScheduleBrainDialog.accept)
        self.buttonbox.rejected.connect(ScheduleBrainDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(ScheduleBrainDialog)

    def retranslateUi(self, ScheduleBrainDialog):
        _translate = QtCore.QCoreApplication.translate
        ScheduleBrainDialog.setWindowTitle(_translate("ScheduleBrainDialog", "Schedule Brain"))
        self.object_groupbox.setTitle(_translate("ScheduleBrainDialog", "Objects"))
        self.mercury_checkbox.setText(_translate("ScheduleBrainDialog", "Mercury"))
        self.saturn_checkbox.setText(_translate("ScheduleBrainDialog", "Saturn"))
        self.venus_checkbox.setText(_translate("ScheduleBrainDialog", "Venus"))
        self.uranus_checkbox.setText(_translate("ScheduleBrainDialog", "Uranus"))
        self.mars_checkbox.setText(_translate("ScheduleBrainDialog", "Mars"))
        self.neptune_checkbox.setText(_translate("ScheduleBrainDialog", "Neptune"))
        self.jupiter_checkbox.setText(_translate("ScheduleBrainDialog", "Jupiter"))
        self.darkness_label.setText(_translate("ScheduleBrainDialog", "Darkness"))
        self.darkness_combobox.setToolTip(_translate("ScheduleBrainDialog", "<html><head/><body><p><span style=\" font-weight:600;\">Night<br/></span>Sun &gt;18° below horizon</p><p><span style=\" font-weight:600;\">Astronomical Twilight<br/></span>Sun &gt;12° below horizon</p><p><span style=\" font-weight:600;\">Nautical Twilight<br/></span>Sun &gt;6° below horizon</p><p><span style=\" font-weight:600;\">Civil Twilight<br/></span>Sun &gt;0° below horizon</p></body></html>"))
        self.darkness_combobox.setItemText(0, _translate("ScheduleBrainDialog", "Night"))
        self.darkness_combobox.setItemText(1, _translate("ScheduleBrainDialog", "Astronomical Twilight"))
        self.darkness_combobox.setItemText(2, _translate("ScheduleBrainDialog", "Nautical Twilight"))
        self.darkness_combobox.setItemText(3, _translate("ScheduleBrainDialog", "Civil Twilight"))
        self.time_label.setText(_translate("ScheduleBrainDialog", "Time"))
        self.start_timeedit.setDisplayFormat(_translate("ScheduleBrainDialog", "hh:mm:ss"))
        self.to_label.setText(_translate("ScheduleBrainDialog", "to"))
        self.end_timeedit.setDisplayFormat(_translate("ScheduleBrainDialog", "hh:mm:ss"))
        self.label.setText(_translate("ScheduleBrainDialog", "Preference"))
        self.radioButton.setText(_translate("ScheduleBrainDialog", "East"))
        self.radioButton_2.setText(_translate("ScheduleBrainDialog", "West"))

