# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'schedulebrain.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ScheduleBrainDialog(object):
    def setupUi(self, ScheduleBrainDialog):
        ScheduleBrainDialog.setObjectName("ScheduleBrainDialog")
        ScheduleBrainDialog.resize(308, 244)
        self.gridLayout = QtWidgets.QGridLayout(ScheduleBrainDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.buttonbox = QtWidgets.QDialogButtonBox(ScheduleBrainDialog)
        self.buttonbox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonbox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonbox.setObjectName("buttonbox")
        self.gridLayout.addWidget(self.buttonbox, 2, 1, 1, 1)
        self.targets_groupbox = QtWidgets.QGroupBox(ScheduleBrainDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.targets_groupbox.sizePolicy().hasHeightForWidth())
        self.targets_groupbox.setSizePolicy(sizePolicy)
        self.targets_groupbox.setObjectName("targets_groupbox")
        self.formLayout_2 = QtWidgets.QFormLayout(self.targets_groupbox)
        self.formLayout_2.setObjectName("formLayout_2")
        self.mercury_checkbox = QtWidgets.QCheckBox(self.targets_groupbox)
        self.mercury_checkbox.setChecked(True)
        self.mercury_checkbox.setObjectName("mercury_checkbox")
        self.targets_buttongroup = QtWidgets.QButtonGroup(ScheduleBrainDialog)
        self.targets_buttongroup.setObjectName("targets_buttongroup")
        self.targets_buttongroup.setExclusive(False)
        self.targets_buttongroup.addButton(self.mercury_checkbox)
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.mercury_checkbox)
        self.venus_checkbox = QtWidgets.QCheckBox(self.targets_groupbox)
        self.venus_checkbox.setChecked(True)
        self.venus_checkbox.setObjectName("venus_checkbox")
        self.targets_buttongroup.addButton(self.venus_checkbox)
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.venus_checkbox)
        self.mars_checkbox = QtWidgets.QCheckBox(self.targets_groupbox)
        self.mars_checkbox.setChecked(True)
        self.mars_checkbox.setObjectName("mars_checkbox")
        self.targets_buttongroup.addButton(self.mars_checkbox)
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.mars_checkbox)
        self.jupiter_checkbox = QtWidgets.QCheckBox(self.targets_groupbox)
        self.jupiter_checkbox.setChecked(True)
        self.jupiter_checkbox.setObjectName("jupiter_checkbox")
        self.targets_buttongroup.addButton(self.jupiter_checkbox)
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.jupiter_checkbox)
        self.saturn_checkbox = QtWidgets.QCheckBox(self.targets_groupbox)
        self.saturn_checkbox.setChecked(True)
        self.saturn_checkbox.setObjectName("saturn_checkbox")
        self.targets_buttongroup.addButton(self.saturn_checkbox)
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.saturn_checkbox)
        self.uranus_checkbox = QtWidgets.QCheckBox(self.targets_groupbox)
        self.uranus_checkbox.setChecked(True)
        self.uranus_checkbox.setObjectName("uranus_checkbox")
        self.targets_buttongroup.addButton(self.uranus_checkbox)
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.uranus_checkbox)
        self.neptune_checkbox = QtWidgets.QCheckBox(self.targets_groupbox)
        self.neptune_checkbox.setChecked(True)
        self.neptune_checkbox.setObjectName("neptune_checkbox")
        self.targets_buttongroup.addButton(self.neptune_checkbox)
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.neptune_checkbox)
        self.gridLayout.addWidget(self.targets_groupbox, 1, 0, 2, 1, QtCore.Qt.AlignTop)
        self.form_layout = QtWidgets.QFormLayout()
        self.form_layout.setObjectName("form_layout")
        self.direction_label = QtWidgets.QLabel(ScheduleBrainDialog)
        self.direction_label.setObjectName("direction_label")
        self.form_layout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.direction_label)
        self.directional_combobox = QtWidgets.QComboBox(ScheduleBrainDialog)
        self.directional_combobox.setObjectName("directional_combobox")
        self.directional_combobox.addItem("")
        self.directional_combobox.addItem("")
        self.directional_combobox.addItem("")
        self.form_layout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.directional_combobox)
        self.targetpreference_label = QtWidgets.QLabel(ScheduleBrainDialog)
        self.targetpreference_label.setObjectName("targetpreference_label")
        self.form_layout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.targetpreference_label)
        self.time_layout = QtWidgets.QHBoxLayout()
        self.time_layout.setObjectName("time_layout")
        self.start_timeedit = QtWidgets.QTimeEdit(ScheduleBrainDialog)
        self.start_timeedit.setMaximumDateTime(QtCore.QDateTime(QtCore.QDate(2000, 1, 1), QtCore.QTime(23, 59, 0)))
        self.start_timeedit.setMaximumTime(QtCore.QTime(23, 59, 0))
        self.start_timeedit.setTime(QtCore.QTime(0, 0, 0))
        self.start_timeedit.setObjectName("start_timeedit")
        self.time_layout.addWidget(self.start_timeedit)
        self.time_to_label = QtWidgets.QLabel(ScheduleBrainDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.time_to_label.sizePolicy().hasHeightForWidth())
        self.time_to_label.setSizePolicy(sizePolicy)
        self.time_to_label.setObjectName("time_to_label")
        self.time_layout.addWidget(self.time_to_label)
        self.end_timeedit = QtWidgets.QTimeEdit(ScheduleBrainDialog)
        self.end_timeedit.setDateTime(QtCore.QDateTime(QtCore.QDate(2000, 1, 1), QtCore.QTime(23, 59, 0)))
        self.end_timeedit.setMaximumDateTime(QtCore.QDateTime(QtCore.QDate(2000, 1, 1), QtCore.QTime(23, 59, 0)))
        self.end_timeedit.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(2000, 1, 1), QtCore.QTime(0, 0, 0)))
        self.end_timeedit.setMinimumTime(QtCore.QTime(0, 0, 0))
        self.end_timeedit.setTimeSpec(QtCore.Qt.LocalTime)
        self.end_timeedit.setObjectName("end_timeedit")
        self.time_layout.addWidget(self.end_timeedit)
        self.form_layout.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.time_layout)
        self.elevationrange_layout = QtWidgets.QHBoxLayout()
        self.elevationrange_layout.setObjectName("elevationrange_layout")
        self.minelevation_spinbox = QtWidgets.QSpinBox(ScheduleBrainDialog)
        self.minelevation_spinbox.setMaximum(89)
        self.minelevation_spinbox.setProperty("value", 12)
        self.minelevation_spinbox.setObjectName("minelevation_spinbox")
        self.elevationrange_layout.addWidget(self.minelevation_spinbox)
        self.elevation_to_label = QtWidgets.QLabel(ScheduleBrainDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.elevation_to_label.sizePolicy().hasHeightForWidth())
        self.elevation_to_label.setSizePolicy(sizePolicy)
        self.elevation_to_label.setObjectName("elevation_to_label")
        self.elevationrange_layout.addWidget(self.elevation_to_label)
        self.maxelevation_spinbox = QtWidgets.QSpinBox(ScheduleBrainDialog)
        self.maxelevation_spinbox.setMinimum(1)
        self.maxelevation_spinbox.setMaximum(90)
        self.maxelevation_spinbox.setProperty("value", 90)
        self.maxelevation_spinbox.setObjectName("maxelevation_spinbox")
        self.elevationrange_layout.addWidget(self.maxelevation_spinbox)
        self.form_layout.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.elevationrange_layout)
        self.sunelevation_spinbox = QtWidgets.QSpinBox(ScheduleBrainDialog)
        self.sunelevation_spinbox.setMinimum(-90)
        self.sunelevation_spinbox.setMaximum(90)
        self.sunelevation_spinbox.setProperty("value", -18)
        self.sunelevation_spinbox.setObjectName("sunelevation_spinbox")
        self.form_layout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.sunelevation_spinbox)
        self.time_label = QtWidgets.QLabel(ScheduleBrainDialog)
        self.time_label.setObjectName("time_label")
        self.form_layout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.time_label)
        self.elevation_label = QtWidgets.QLabel(ScheduleBrainDialog)
        self.elevation_label.setObjectName("elevation_label")
        self.form_layout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.elevation_label)
        self.darkness_label = QtWidgets.QLabel(ScheduleBrainDialog)
        self.darkness_label.setObjectName("darkness_label")
        self.form_layout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.darkness_label)
        self.targetpreference_combobox = QtWidgets.QComboBox(ScheduleBrainDialog)
        self.targetpreference_combobox.setObjectName("targetpreference_combobox")
        self.targetpreference_combobox.addItem("")
        self.targetpreference_combobox.addItem("")
        self.form_layout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.targetpreference_combobox)
        self.notarget_label = QtWidgets.QLabel(ScheduleBrainDialog)
        self.notarget_label.setObjectName("notarget_label")
        self.form_layout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.notarget_label)
        self.notarget_combobox = QtWidgets.QComboBox(ScheduleBrainDialog)
        self.notarget_combobox.setObjectName("notarget_combobox")
        self.notarget_combobox.addItem("")
        self.notarget_combobox.addItem("")
        self.form_layout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.notarget_combobox)
        self.endaction_label = QtWidgets.QLabel(ScheduleBrainDialog)
        self.endaction_label.setObjectName("endaction_label")
        self.form_layout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.endaction_label)
        self.endaction_combobox = QtWidgets.QComboBox(ScheduleBrainDialog)
        self.endaction_combobox.setObjectName("endaction_combobox")
        self.endaction_combobox.addItem("")
        self.endaction_combobox.addItem("")
        self.form_layout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.endaction_combobox)
        self.interval_label = QtWidgets.QLabel(ScheduleBrainDialog)
        self.interval_label.setObjectName("interval_label")
        self.form_layout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.interval_label)
        self.interval_spinbox = QtWidgets.QSpinBox(ScheduleBrainDialog)
        self.interval_spinbox.setMinimum(2)
        self.interval_spinbox.setMaximum(60)
        self.interval_spinbox.setObjectName("interval_spinbox")
        self.form_layout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.interval_spinbox)
        self.gridLayout.addLayout(self.form_layout, 1, 1, 1, 1)
        self.plot_layout = QtWidgets.QHBoxLayout()
        self.plot_layout.setObjectName("plot_layout")
        self.gridLayout.addLayout(self.plot_layout, 0, 0, 1, 2)

        self.retranslateUi(ScheduleBrainDialog)
        self.directional_combobox.setCurrentIndex(1)
        self.endaction_combobox.setCurrentIndex(1)
        self.buttonbox.accepted.connect(ScheduleBrainDialog.accept)
        self.buttonbox.rejected.connect(ScheduleBrainDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(ScheduleBrainDialog)

    def retranslateUi(self, ScheduleBrainDialog):
        _translate = QtCore.QCoreApplication.translate
        ScheduleBrainDialog.setWindowTitle(_translate("ScheduleBrainDialog", "Schedule Brain"))
        self.targets_groupbox.setTitle(_translate("ScheduleBrainDialog", "Targets"))
        self.mercury_checkbox.setText(_translate("ScheduleBrainDialog", "Mercury"))
        self.venus_checkbox.setText(_translate("ScheduleBrainDialog", "Venus"))
        self.mars_checkbox.setText(_translate("ScheduleBrainDialog", "Mars"))
        self.jupiter_checkbox.setText(_translate("ScheduleBrainDialog", "Jupiter"))
        self.saturn_checkbox.setText(_translate("ScheduleBrainDialog", "Saturn"))
        self.uranus_checkbox.setText(_translate("ScheduleBrainDialog", "Uranus"))
        self.neptune_checkbox.setText(_translate("ScheduleBrainDialog", "Neptune"))
        self.direction_label.setText(_translate("ScheduleBrainDialog", "Direction"))
        self.directional_combobox.setItemText(0, _translate("ScheduleBrainDialog", "East"))
        self.directional_combobox.setItemText(1, _translate("ScheduleBrainDialog", "Both"))
        self.directional_combobox.setItemText(2, _translate("ScheduleBrainDialog", "West"))
        self.targetpreference_label.setText(_translate("ScheduleBrainDialog", "Target Preference"))
        self.start_timeedit.setToolTip(_translate("ScheduleBrainDialog", "Start time"))
        self.start_timeedit.setDisplayFormat(_translate("ScheduleBrainDialog", "hh:mm UTC"))
        self.time_to_label.setText(_translate("ScheduleBrainDialog", "to"))
        self.end_timeedit.setToolTip(_translate("ScheduleBrainDialog", "End time"))
        self.end_timeedit.setDisplayFormat(_translate("ScheduleBrainDialog", "hh:mm UTC"))
        self.minelevation_spinbox.setToolTip(_translate("ScheduleBrainDialog", "Minimum elevation of targets"))
        self.minelevation_spinbox.setSuffix(_translate("ScheduleBrainDialog", "°"))
        self.elevation_to_label.setText(_translate("ScheduleBrainDialog", "to"))
        self.maxelevation_spinbox.setToolTip(_translate("ScheduleBrainDialog", "Maximum elevation of targets"))
        self.maxelevation_spinbox.setSuffix(_translate("ScheduleBrainDialog", "°"))
        self.sunelevation_spinbox.setToolTip(_translate("ScheduleBrainDialog", "<html><head/><body><p><span style=\" font-weight:600;\">Night<br/></span>Sun &gt; 18° below horizon</p><p><span style=\" font-weight:600;\">Astronomical Twilight<br/></span>Sun 12°-18° below horizon</p><p><span style=\" font-weight:600;\">Nautical Twilight<br/></span>Sun 6°-12° below horizon</p><p><span style=\" font-weight:600;\">Civil Twilight<br/></span>Sun 0°-6° below horizon</p></body></html>"))
        self.sunelevation_spinbox.setSuffix(_translate("ScheduleBrainDialog", "°"))
        self.time_label.setText(_translate("ScheduleBrainDialog", "Time Range"))
        self.elevation_label.setText(_translate("ScheduleBrainDialog", "Elevation Range"))
        self.darkness_label.setText(_translate("ScheduleBrainDialog", "Max Sun Elevation"))
        self.targetpreference_combobox.setItemText(0, _translate("ScheduleBrainDialog", "Less for longer"))
        self.targetpreference_combobox.setItemText(1, _translate("ScheduleBrainDialog", "Prefer highest"))
        self.notarget_label.setText(_translate("ScheduleBrainDialog", "No Target Action"))
        self.notarget_combobox.setToolTip(_translate("ScheduleBrainDialog", "Action to perform if no targets are available"))
        self.notarget_combobox.setItemText(0, _translate("ScheduleBrainDialog", "Stop"))
        self.notarget_combobox.setItemText(1, _translate("ScheduleBrainDialog", "Home"))
        self.endaction_label.setText(_translate("ScheduleBrainDialog", "End Action"))
        self.endaction_combobox.setToolTip(_translate("ScheduleBrainDialog", "Action to perform if no targets are available"))
        self.endaction_combobox.setItemText(0, _translate("ScheduleBrainDialog", "Stop"))
        self.endaction_combobox.setItemText(1, _translate("ScheduleBrainDialog", "Home"))
        self.interval_label.setText(_translate("ScheduleBrainDialog", "Interval"))
        self.interval_spinbox.setToolTip(_translate("ScheduleBrainDialog", "Time intervals at which to calculate between start and end times"))
        self.interval_spinbox.setSuffix(_translate("ScheduleBrainDialog", " Minutes"))

import res_rc
