# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'mainwindow.ui'
##
## Created by: Qt User Interface Compiler version 6.0.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import *
from PySide6.QtGui import *
from PySide6.QtWidgets import *

import res_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(937, 748)
        icon = QIcon()
        icon.addFile(u":/icons/logo.svg", QSize(), QIcon.Normal, QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setDockNestingEnabled(True)
        MainWindow.setDockOptions(QMainWindow.AllowNestedDocks|QMainWindow.AllowTabbedDocks|QMainWindow.AnimatedDocks)
        MainWindow.setUnifiedTitleAndToolBarOnMac(True)
        self.filters_action = QAction(MainWindow)
        self.filters_action.setObjectName(u"filters_action")
        icon1 = QIcon()
        icon1.addFile(u":/icons/ic_tonality_white_48px.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.filters_action.setIcon(icon1)
        self.location_action = QAction(MainWindow)
        self.location_action.setObjectName(u"location_action")
        icon2 = QIcon()
        icon2.addFile(u":/icons/ic_location_on_white_48px.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.location_action.setIcon(icon2)
        self.targets_action = QAction(MainWindow)
        self.targets_action.setObjectName(u"targets_action")
        icon3 = QIcon()
        icon3.addFile(u":/icons/ic_center_focus_strong_white_48px.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.targets_action.setIcon(icon3)
        self.action_undo = QAction(MainWindow)
        self.action_undo.setObjectName(u"action_undo")
        icon4 = QIcon()
        icon4.addFile(u":/icons/ic_undo_white_48px.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.action_undo.setIcon(icon4)
        self.action_redo = QAction(MainWindow)
        self.action_redo.setObjectName(u"action_redo")
        icon5 = QIcon()
        icon5.addFile(u":/icons/ic_redo_white_48px.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.action_redo.setIcon(icon5)
        self.action_about = QAction(MainWindow)
        self.action_about.setObjectName(u"action_about")
        icon6 = QIcon()
        icon6.addFile(u":/icons/ic_info_white_48px.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.action_about.setIcon(icon6)
        self.telescope_action = QAction(MainWindow)
        self.telescope_action.setObjectName(u"telescope_action")
        self.telescope_action.setCheckable(True)
        self.guider_action = QAction(MainWindow)
        self.guider_action.setObjectName(u"guider_action")
        self.guider_action.setCheckable(True)
        self.camera_action = QAction(MainWindow)
        self.camera_action.setObjectName(u"camera_action")
        self.camera_action.setCheckable(True)
        self.focuser_action = QAction(MainWindow)
        self.focuser_action.setObjectName(u"focuser_action")
        self.focuser_action.setCheckable(True)
        self.wheel_action = QAction(MainWindow)
        self.wheel_action.setObjectName(u"wheel_action")
        self.wheel_action.setCheckable(True)
        self.importschedule_action = QAction(MainWindow)
        self.importschedule_action.setObjectName(u"importschedule_action")
        self.importfilters_action = QAction(MainWindow)
        self.importfilters_action.setObjectName(u"importfilters_action")
        self.savelocation_action = QAction(MainWindow)
        self.savelocation_action.setObjectName(u"savelocation_action")
        icon7 = QIcon()
        icon7.addFile(u":/icons/ic_folder_white_48px.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.savelocation_action.setIcon(icon7)
        self.action_exit = QAction(MainWindow)
        self.action_exit.setObjectName(u"action_exit")
        icon8 = QIcon()
        icon8.addFile(u":/icons/ic_close_white_48px.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.action_exit.setIcon(icon8)
        self.actionFilters = QAction(MainWindow)
        self.actionFilters.setObjectName(u"actionFilters")
        self.actionSchedule = QAction(MainWindow)
        self.actionSchedule.setObjectName(u"actionSchedule")
        self.ascomcamerasettings_action = QAction(MainWindow)
        self.ascomcamerasettings_action.setObjectName(u"ascomcamerasettings_action")
        icon9 = QIcon()
        icon9.addFile(u":/icons/ic_settings_white_48px.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.ascomcamerasettings_action.setIcon(icon9)
        self.ascomguidersettings_action = QAction(MainWindow)
        self.ascomguidersettings_action.setObjectName(u"ascomguidersettings_action")
        self.ascomguidersettings_action.setIcon(icon9)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.horizontalLayout_2 = QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.scrollarea = QScrollArea(self.centralwidget)
        self.scrollarea.setObjectName(u"scrollarea")
        sizePolicy1 = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Expanding)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.scrollarea.sizePolicy().hasHeightForWidth())
        self.scrollarea.setSizePolicy(sizePolicy1)
        self.scrollarea.setFrameShape(QFrame.NoFrame)
        self.scrollarea.setFrameShadow(QFrame.Plain)
        self.scrollarea.setLineWidth(0)
        self.scrollarea.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOn)
        self.scrollarea.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.scrollarea.setSizeAdjustPolicy(QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.scrollarea.setWidgetResizable(True)
        self.scroll_area_widget_contents = QWidget()
        self.scroll_area_widget_contents.setObjectName(u"scroll_area_widget_contents")
        self.scroll_area_widget_contents.setGeometry(QRect(0, -518, 920, 1216))
        self.formLayout_4 = QFormLayout(self.scroll_area_widget_contents)
        self.formLayout_4.setObjectName(u"formLayout_4")
        self.mount_group = QGroupBox(self.scroll_area_widget_contents)
        self.mount_group.setObjectName(u"mount_group")
        sizePolicy2 = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Fixed)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.mount_group.sizePolicy().hasHeightForWidth())
        self.mount_group.setSizePolicy(sizePolicy2)
        self.mount_group.setCheckable(True)
        self.mount_group.setChecked(False)
        self.verticalLayout_3 = QVBoxLayout(self.mount_group)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.horizontallayout_9 = QHBoxLayout()
        self.horizontallayout_9.setObjectName(u"horizontallayout_9")
        self.telescope_name_label = QLabel(self.mount_group)
        self.telescope_name_label.setObjectName(u"telescope_name_label")
        sizePolicy3 = QSizePolicy(QSizePolicy.Ignored, QSizePolicy.Preferred)
        sizePolicy3.setHorizontalStretch(0)
        sizePolicy3.setVerticalStretch(0)
        sizePolicy3.setHeightForWidth(self.telescope_name_label.sizePolicy().hasHeightForWidth())
        self.telescope_name_label.setSizePolicy(sizePolicy3)
        self.telescope_name_label.setWordWrap(True)

        self.horizontallayout_9.addWidget(self.telescope_name_label)

        self.scope_settings_btn = QToolButton(self.mount_group)
        self.scope_settings_btn.setObjectName(u"scope_settings_btn")
        sizePolicy.setHeightForWidth(self.scope_settings_btn.sizePolicy().hasHeightForWidth())
        self.scope_settings_btn.setSizePolicy(sizePolicy)
        self.scope_settings_btn.setIcon(icon9)
        self.scope_settings_btn.setPopupMode(QToolButton.InstantPopup)

        self.horizontallayout_9.addWidget(self.scope_settings_btn)


        self.verticalLayout_3.addLayout(self.horizontallayout_9)

        self.scope_frame = QFrame(self.mount_group)
        self.scope_frame.setObjectName(u"scope_frame")
        self.scope_frame.setFrameShape(QFrame.NoFrame)
        self.scope_frame.setFrameShadow(QFrame.Plain)
        self.scope_frame.setLineWidth(0)
        self.verticalLayout = QVBoxLayout(self.scope_frame)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.line_2 = QFrame(self.scope_frame)
        self.line_2.setObjectName(u"line_2")
        self.line_2.setFrameShape(QFrame.HLine)
        self.line_2.setFrameShadow(QFrame.Sunken)

        self.verticalLayout.addWidget(self.line_2)

        self.gridlayout_10 = QGridLayout()
        self.gridlayout_10.setObjectName(u"gridlayout_10")
        self.slewnorth_button = QPushButton(self.scope_frame)
        self.slewnorth_button.setObjectName(u"slewnorth_button")
        sizePolicy4 = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Fixed)
        sizePolicy4.setHorizontalStretch(0)
        sizePolicy4.setVerticalStretch(0)
        sizePolicy4.setHeightForWidth(self.slewnorth_button.sizePolicy().hasHeightForWidth())
        self.slewnorth_button.setSizePolicy(sizePolicy4)
        icon10 = QIcon()
        icon10.addFile(u":/icons/ic_keyboard_arrow_up_white_48px.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.slewnorth_button.setIcon(icon10)
        self.slewnorth_button.setIconSize(QSize(36, 36))
        self.slewnorth_button.setAutoDefault(True)

        self.gridlayout_10.addWidget(self.slewnorth_button, 0, 1, 1, 1)

        self.slewsouthwest_button = QPushButton(self.scope_frame)
        self.slewsouthwest_button.setObjectName(u"slewsouthwest_button")
        sizePolicy4.setHeightForWidth(self.slewsouthwest_button.sizePolicy().hasHeightForWidth())
        self.slewsouthwest_button.setSizePolicy(sizePolicy4)
        icon11 = QIcon()
        icon11.addFile(u":/icons/ic_keyboard_arrow_downleft_white_48px.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.slewsouthwest_button.setIcon(icon11)
        self.slewsouthwest_button.setIconSize(QSize(36, 36))
        self.slewsouthwest_button.setAutoDefault(True)
        self.slewsouthwest_button.setFlat(False)

        self.gridlayout_10.addWidget(self.slewsouthwest_button, 2, 0, 1, 1)

        self.sleweast_button = QPushButton(self.scope_frame)
        self.sleweast_button.setObjectName(u"sleweast_button")
        sizePolicy4.setHeightForWidth(self.sleweast_button.sizePolicy().hasHeightForWidth())
        self.sleweast_button.setSizePolicy(sizePolicy4)
        icon12 = QIcon()
        icon12.addFile(u":/icons/ic_keyboard_arrow_right_white_48px.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.sleweast_button.setIcon(icon12)
        self.sleweast_button.setIconSize(QSize(36, 36))
        self.sleweast_button.setAutoDefault(True)

        self.gridlayout_10.addWidget(self.sleweast_button, 1, 2, 1, 1)

        self.slewnorthwest_button = QPushButton(self.scope_frame)
        self.slewnorthwest_button.setObjectName(u"slewnorthwest_button")
        sizePolicy4.setHeightForWidth(self.slewnorthwest_button.sizePolicy().hasHeightForWidth())
        self.slewnorthwest_button.setSizePolicy(sizePolicy4)
        icon13 = QIcon()
        icon13.addFile(u":/icons/ic_keyboard_arrow_upleft_white_48px.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.slewnorthwest_button.setIcon(icon13)
        self.slewnorthwest_button.setIconSize(QSize(36, 36))
        self.slewnorthwest_button.setAutoDefault(True)
        self.slewnorthwest_button.setFlat(False)

        self.gridlayout_10.addWidget(self.slewnorthwest_button, 0, 0, 1, 1)

        self.slewsoutheast_button = QPushButton(self.scope_frame)
        self.slewsoutheast_button.setObjectName(u"slewsoutheast_button")
        sizePolicy4.setHeightForWidth(self.slewsoutheast_button.sizePolicy().hasHeightForWidth())
        self.slewsoutheast_button.setSizePolicy(sizePolicy4)
        icon14 = QIcon()
        icon14.addFile(u":/icons/ic_keyboard_arrow_downright_white_48px.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.slewsoutheast_button.setIcon(icon14)
        self.slewsoutheast_button.setIconSize(QSize(36, 36))
        self.slewsoutheast_button.setAutoDefault(True)
        self.slewsoutheast_button.setFlat(False)

        self.gridlayout_10.addWidget(self.slewsoutheast_button, 2, 2, 1, 1)

        self.slewstop_button = QPushButton(self.scope_frame)
        self.slewstop_button.setObjectName(u"slewstop_button")
        sizePolicy4.setHeightForWidth(self.slewstop_button.sizePolicy().hasHeightForWidth())
        self.slewstop_button.setSizePolicy(sizePolicy4)
        icon15 = QIcon()
        icon15.addFile(u":/icons/ic_report_white_48px.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.slewstop_button.setIcon(icon15)
        self.slewstop_button.setIconSize(QSize(36, 36))
        self.slewstop_button.setAutoDefault(True)

        self.gridlayout_10.addWidget(self.slewstop_button, 1, 1, 1, 1)

        self.slewwest_button = QPushButton(self.scope_frame)
        self.slewwest_button.setObjectName(u"slewwest_button")
        sizePolicy4.setHeightForWidth(self.slewwest_button.sizePolicy().hasHeightForWidth())
        self.slewwest_button.setSizePolicy(sizePolicy4)
        icon16 = QIcon()
        icon16.addFile(u":/icons/ic_keyboard_arrow_left_white_48px.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.slewwest_button.setIcon(icon16)
        self.slewwest_button.setIconSize(QSize(36, 36))
        self.slewwest_button.setAutoDefault(True)

        self.gridlayout_10.addWidget(self.slewwest_button, 1, 0, 1, 1)

        self.slewsouth_button = QPushButton(self.scope_frame)
        self.slewsouth_button.setObjectName(u"slewsouth_button")
        sizePolicy4.setHeightForWidth(self.slewsouth_button.sizePolicy().hasHeightForWidth())
        self.slewsouth_button.setSizePolicy(sizePolicy4)
        icon17 = QIcon()
        icon17.addFile(u":/icons/ic_keyboard_arrow_down_white_48px.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.slewsouth_button.setIcon(icon17)
        self.slewsouth_button.setIconSize(QSize(36, 36))
        self.slewsouth_button.setAutoDefault(True)

        self.gridlayout_10.addWidget(self.slewsouth_button, 2, 1, 1, 1)

        self.slewnortheast_button = QPushButton(self.scope_frame)
        self.slewnortheast_button.setObjectName(u"slewnortheast_button")
        sizePolicy4.setHeightForWidth(self.slewnortheast_button.sizePolicy().hasHeightForWidth())
        self.slewnortheast_button.setSizePolicy(sizePolicy4)
        icon18 = QIcon()
        icon18.addFile(u":/icons/ic_keyboard_arrow_upright_white_48px.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.slewnortheast_button.setIcon(icon18)
        self.slewnortheast_button.setIconSize(QSize(36, 36))
        self.slewnortheast_button.setAutoDefault(True)
        self.slewnortheast_button.setFlat(False)

        self.gridlayout_10.addWidget(self.slewnortheast_button, 0, 2, 1, 1)


        self.verticalLayout.addLayout(self.gridlayout_10)

        self.formlayout_2 = QFormLayout()
        self.formlayout_2.setObjectName(u"formlayout_2")
        self.mount_trackrate_label = QLabel(self.scope_frame)
        self.mount_trackrate_label.setObjectName(u"mount_trackrate_label")

        self.formlayout_2.setWidget(0, QFormLayout.LabelRole, self.mount_trackrate_label)

        self.mount_trackrate_spin = QDoubleSpinBox(self.scope_frame)
        self.mount_trackrate_spin.setObjectName(u"mount_trackrate_spin")
        self.mount_trackrate_spin.setFocusPolicy(Qt.StrongFocus)
        self.mount_trackrate_spin.setMinimum(0.010000000000000)
        self.mount_trackrate_spin.setMaximum(1.000000000000000)
        self.mount_trackrate_spin.setSingleStep(0.010000000000000)
        self.mount_trackrate_spin.setValue(0.200000000000000)

        self.formlayout_2.setWidget(0, QFormLayout.FieldRole, self.mount_trackrate_spin)


        self.verticalLayout.addLayout(self.formlayout_2)

        self.horizontallayout_5 = QHBoxLayout()
        self.horizontallayout_5.setObjectName(u"horizontallayout_5")
        self.object_label = QLabel(self.scope_frame)
        self.object_label.setObjectName(u"object_label")
        sizePolicy.setHeightForWidth(self.object_label.sizePolicy().hasHeightForWidth())
        self.object_label.setSizePolicy(sizePolicy)

        self.horizontallayout_5.addWidget(self.object_label)

        self.line = QFrame(self.scope_frame)
        self.line.setObjectName(u"line")
        self.line.setFrameShape(QFrame.HLine)
        self.line.setFrameShadow(QFrame.Sunken)

        self.horizontallayout_5.addWidget(self.line)


        self.verticalLayout.addLayout(self.horizontallayout_5)

        self.horizontallayout_4 = QHBoxLayout()
        self.horizontallayout_4.setObjectName(u"horizontallayout_4")
        self.object_combobox = QComboBox(self.scope_frame)
        self.object_combobox.setObjectName(u"object_combobox")
        sizePolicy5 = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Preferred)
        sizePolicy5.setHorizontalStretch(0)
        sizePolicy5.setVerticalStretch(0)
        sizePolicy5.setHeightForWidth(self.object_combobox.sizePolicy().hasHeightForWidth())
        self.object_combobox.setSizePolicy(sizePolicy5)
        self.object_combobox.setFocusPolicy(Qt.StrongFocus)

        self.horizontallayout_4.addWidget(self.object_combobox)

        self.goto_button = QPushButton(self.scope_frame)
        self.goto_button.setObjectName(u"goto_button")
        sizePolicy.setHeightForWidth(self.goto_button.sizePolicy().hasHeightForWidth())
        self.goto_button.setSizePolicy(sizePolicy)
        icon19 = QIcon()
        icon19.addFile(u":/icons/ic_check_white_48px.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.goto_button.setIcon(icon19)
        self.goto_button.setAutoDefault(True)

        self.horizontallayout_4.addWidget(self.goto_button)


        self.verticalLayout.addLayout(self.horizontallayout_4)


        self.verticalLayout_3.addWidget(self.scope_frame)


        self.formLayout_4.setWidget(0, QFormLayout.SpanningRole, self.mount_group)

        self.guider_group = QGroupBox(self.scroll_area_widget_contents)
        self.guider_group.setObjectName(u"guider_group")
        sizePolicy2.setHeightForWidth(self.guider_group.sizePolicy().hasHeightForWidth())
        self.guider_group.setSizePolicy(sizePolicy2)
        self.guider_group.setCheckable(True)
        self.guider_group.setChecked(False)
        self.verticalLayout_2 = QVBoxLayout(self.guider_group)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.horizontallayout_10 = QHBoxLayout()
        self.horizontallayout_10.setObjectName(u"horizontallayout_10")
        self.guider_name_label = QLabel(self.guider_group)
        self.guider_name_label.setObjectName(u"guider_name_label")
        sizePolicy3.setHeightForWidth(self.guider_name_label.sizePolicy().hasHeightForWidth())
        self.guider_name_label.setSizePolicy(sizePolicy3)
        self.guider_name_label.setWordWrap(True)

        self.horizontallayout_10.addWidget(self.guider_name_label)

        self.guider_settings_btn = QToolButton(self.guider_group)
        self.guider_settings_btn.setObjectName(u"guider_settings_btn")
        sizePolicy.setHeightForWidth(self.guider_settings_btn.sizePolicy().hasHeightForWidth())
        self.guider_settings_btn.setSizePolicy(sizePolicy)
        self.guider_settings_btn.setIcon(icon9)
        self.guider_settings_btn.setPopupMode(QToolButton.InstantPopup)

        self.horizontallayout_10.addWidget(self.guider_settings_btn)


        self.verticalLayout_2.addLayout(self.horizontallayout_10)

        self.guide_frame = QFrame(self.guider_group)
        self.guide_frame.setObjectName(u"guide_frame")
        self.guide_frame.setFrameShape(QFrame.NoFrame)
        self.guide_frame.setFrameShadow(QFrame.Plain)
        self.guide_frame.setLineWidth(0)
        self.formLayout_3 = QFormLayout(self.guide_frame)
        self.formLayout_3.setObjectName(u"formLayout_3")
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.guider_line = QFrame(self.guide_frame)
        self.guider_line.setObjectName(u"guider_line")
        self.guider_line.setFrameShape(QFrame.HLine)
        self.guider_line.setFrameShadow(QFrame.Sunken)

        self.formLayout_3.setWidget(0, QFormLayout.SpanningRole, self.guider_line)

        self.guider_exposure_label = QLabel(self.guide_frame)
        self.guider_exposure_label.setObjectName(u"guider_exposure_label")
        sizePolicy.setHeightForWidth(self.guider_exposure_label.sizePolicy().hasHeightForWidth())
        self.guider_exposure_label.setSizePolicy(sizePolicy)

        self.formLayout_3.setWidget(1, QFormLayout.LabelRole, self.guider_exposure_label)

        self.guider_exposure_spinbox = QSpinBox(self.guide_frame)
        self.guider_exposure_spinbox.setObjectName(u"guider_exposure_spinbox")
        sizePolicy6 = QSizePolicy(QSizePolicy.MinimumExpanding, QSizePolicy.Fixed)
        sizePolicy6.setHorizontalStretch(0)
        sizePolicy6.setVerticalStretch(0)
        sizePolicy6.setHeightForWidth(self.guider_exposure_spinbox.sizePolicy().hasHeightForWidth())
        self.guider_exposure_spinbox.setSizePolicy(sizePolicy6)
        self.guider_exposure_spinbox.setFocusPolicy(Qt.StrongFocus)

        self.formLayout_3.setWidget(1, QFormLayout.FieldRole, self.guider_exposure_spinbox)

        self.guider_exposure_slider = QSlider(self.guide_frame)
        self.guider_exposure_slider.setObjectName(u"guider_exposure_slider")
        sizePolicy4.setHeightForWidth(self.guider_exposure_slider.sizePolicy().hasHeightForWidth())
        self.guider_exposure_slider.setSizePolicy(sizePolicy4)
        self.guider_exposure_slider.setFocusPolicy(Qt.StrongFocus)
        self.guider_exposure_slider.setOrientation(Qt.Horizontal)

        self.formLayout_3.setWidget(2, QFormLayout.SpanningRole, self.guider_exposure_slider)

        self.guider_gain_label = QLabel(self.guide_frame)
        self.guider_gain_label.setObjectName(u"guider_gain_label")
        sizePolicy.setHeightForWidth(self.guider_gain_label.sizePolicy().hasHeightForWidth())
        self.guider_gain_label.setSizePolicy(sizePolicy)

        self.formLayout_3.setWidget(3, QFormLayout.LabelRole, self.guider_gain_label)

        self.guider_gain_spinbox = QSpinBox(self.guide_frame)
        self.guider_gain_spinbox.setObjectName(u"guider_gain_spinbox")
        sizePolicy6.setHeightForWidth(self.guider_gain_spinbox.sizePolicy().hasHeightForWidth())
        self.guider_gain_spinbox.setSizePolicy(sizePolicy6)
        self.guider_gain_spinbox.setFocusPolicy(Qt.StrongFocus)
        self.guider_gain_spinbox.setMaximum(600)

        self.formLayout_3.setWidget(3, QFormLayout.FieldRole, self.guider_gain_spinbox)

        self.guider_gain_slider = QSlider(self.guide_frame)
        self.guider_gain_slider.setObjectName(u"guider_gain_slider")
        sizePolicy4.setHeightForWidth(self.guider_gain_slider.sizePolicy().hasHeightForWidth())
        self.guider_gain_slider.setSizePolicy(sizePolicy4)
        self.guider_gain_slider.setFocusPolicy(Qt.StrongFocus)
        self.guider_gain_slider.setOrientation(Qt.Horizontal)

        self.formLayout_3.setWidget(4, QFormLayout.SpanningRole, self.guider_gain_slider)

        self.horizontallayout_7 = QHBoxLayout()
        self.horizontallayout_7.setObjectName(u"horizontallayout_7")
        self.guider_spacer = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)

        self.horizontallayout_7.addItem(self.guider_spacer)

        self.guider_loop_button = QPushButton(self.guide_frame)
        self.guider_loop_button.setObjectName(u"guider_loop_button")
        sizePolicy7 = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy7.setHorizontalStretch(0)
        sizePolicy7.setVerticalStretch(0)
        sizePolicy7.setHeightForWidth(self.guider_loop_button.sizePolicy().hasHeightForWidth())
        self.guider_loop_button.setSizePolicy(sizePolicy7)
        icon20 = QIcon()
        icon20.addFile(u":/icons/ic_replay_white_48px.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.guider_loop_button.setIcon(icon20)
        self.guider_loop_button.setIconSize(QSize(32, 32))
        self.guider_loop_button.setCheckable(True)
        self.guider_loop_button.setAutoDefault(True)

        self.horizontallayout_7.addWidget(self.guider_loop_button)

        self.guider_start_button = QPushButton(self.guide_frame)
        self.guider_start_button.setObjectName(u"guider_start_button")
        self.guider_start_button.setEnabled(False)
        sizePolicy7.setHeightForWidth(self.guider_start_button.sizePolicy().hasHeightForWidth())
        self.guider_start_button.setSizePolicy(sizePolicy7)
        icon21 = QIcon()
        icon21.addFile(u":/icons/ic_play_arrow_white_48px.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.guider_start_button.setIcon(icon21)
        self.guider_start_button.setIconSize(QSize(32, 32))
        self.guider_start_button.setCheckable(True)
        self.guider_start_button.setAutoDefault(True)

        self.horizontallayout_7.addWidget(self.guider_start_button)


        self.formLayout_3.setLayout(5, QFormLayout.SpanningRole, self.horizontallayout_7)


        self.verticalLayout_2.addWidget(self.guide_frame)


        self.formLayout_4.setWidget(1, QFormLayout.SpanningRole, self.guider_group)

        self.camera_group = QGroupBox(self.scroll_area_widget_contents)
        self.camera_group.setObjectName(u"camera_group")
        sizePolicy2.setHeightForWidth(self.camera_group.sizePolicy().hasHeightForWidth())
        self.camera_group.setSizePolicy(sizePolicy2)
        self.camera_group.setCheckable(True)
        self.camera_group.setChecked(False)
        self.formLayout_8 = QFormLayout(self.camera_group)
        self.formLayout_8.setObjectName(u"formLayout_8")
        self.horizontallayout_11 = QHBoxLayout()
        self.horizontallayout_11.setObjectName(u"horizontallayout_11")
        self.camera_name_label = QLabel(self.camera_group)
        self.camera_name_label.setObjectName(u"camera_name_label")
        sizePolicy3.setHeightForWidth(self.camera_name_label.sizePolicy().hasHeightForWidth())
        self.camera_name_label.setSizePolicy(sizePolicy3)
        self.camera_name_label.setWordWrap(True)

        self.horizontallayout_11.addWidget(self.camera_name_label)

        self.camera_settings_btn = QToolButton(self.camera_group)
        self.camera_settings_btn.setObjectName(u"camera_settings_btn")
        sizePolicy.setHeightForWidth(self.camera_settings_btn.sizePolicy().hasHeightForWidth())
        self.camera_settings_btn.setSizePolicy(sizePolicy)
        self.camera_settings_btn.setIcon(icon9)
        self.camera_settings_btn.setPopupMode(QToolButton.InstantPopup)

        self.horizontallayout_11.addWidget(self.camera_settings_btn)


        self.formLayout_8.setLayout(0, QFormLayout.SpanningRole, self.horizontallayout_11)

        self.camera_frame = QFrame(self.camera_group)
        self.camera_frame.setObjectName(u"camera_frame")
        self.camera_frame.setFrameShape(QFrame.NoFrame)
        self.camera_frame.setFrameShadow(QFrame.Plain)
        self.camera_frame.setLineWidth(0)
        self.gridLayout = QGridLayout(self.camera_frame)
        self.gridLayout.setObjectName(u"gridLayout")
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.line_4 = QFrame(self.camera_frame)
        self.line_4.setObjectName(u"line_4")
        self.line_4.setFrameShape(QFrame.HLine)
        self.line_4.setFrameShadow(QFrame.Sunken)

        self.gridLayout.addWidget(self.line_4, 0, 0, 1, 2)

        self.camera_exposure_spinbox = QSpinBox(self.camera_frame)
        self.camera_exposure_spinbox.setObjectName(u"camera_exposure_spinbox")
        sizePolicy4.setHeightForWidth(self.camera_exposure_spinbox.sizePolicy().hasHeightForWidth())
        self.camera_exposure_spinbox.setSizePolicy(sizePolicy4)
        self.camera_exposure_spinbox.setFocusPolicy(Qt.StrongFocus)

        self.gridLayout.addWidget(self.camera_exposure_spinbox, 1, 1, 1, 1)

        self.camera_gain_slider = QSlider(self.camera_frame)
        self.camera_gain_slider.setObjectName(u"camera_gain_slider")
        sizePolicy4.setHeightForWidth(self.camera_gain_slider.sizePolicy().hasHeightForWidth())
        self.camera_gain_slider.setSizePolicy(sizePolicy4)
        self.camera_gain_slider.setFocusPolicy(Qt.StrongFocus)
        self.camera_gain_slider.setOrientation(Qt.Horizontal)

        self.gridLayout.addWidget(self.camera_gain_slider, 4, 0, 1, 2)

        self.camera_exposure_slider = QSlider(self.camera_frame)
        self.camera_exposure_slider.setObjectName(u"camera_exposure_slider")
        sizePolicy4.setHeightForWidth(self.camera_exposure_slider.sizePolicy().hasHeightForWidth())
        self.camera_exposure_slider.setSizePolicy(sizePolicy4)
        self.camera_exposure_slider.setFocusPolicy(Qt.StrongFocus)
        self.camera_exposure_slider.setOrientation(Qt.Horizontal)

        self.gridLayout.addWidget(self.camera_exposure_slider, 2, 0, 1, 2)

        self.horizontallayout_8 = QHBoxLayout()
        self.horizontallayout_8.setObjectName(u"horizontallayout_8")
        self.horizontalSpacer_2 = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)

        self.horizontallayout_8.addItem(self.horizontalSpacer_2)

        self.camera_loop_button = QPushButton(self.camera_frame)
        self.camera_loop_button.setObjectName(u"camera_loop_button")
        sizePolicy7.setHeightForWidth(self.camera_loop_button.sizePolicy().hasHeightForWidth())
        self.camera_loop_button.setSizePolicy(sizePolicy7)
        self.camera_loop_button.setIcon(icon20)
        self.camera_loop_button.setIconSize(QSize(32, 32))
        self.camera_loop_button.setCheckable(True)
        self.camera_loop_button.setAutoDefault(True)

        self.horizontallayout_8.addWidget(self.camera_loop_button)

        self.camera_capture_button = QPushButton(self.camera_frame)
        self.camera_capture_button.setObjectName(u"camera_capture_button")
        self.camera_capture_button.setEnabled(False)
        sizePolicy7.setHeightForWidth(self.camera_capture_button.sizePolicy().hasHeightForWidth())
        self.camera_capture_button.setSizePolicy(sizePolicy7)
        self.camera_capture_button.setIcon(icon21)
        self.camera_capture_button.setIconSize(QSize(32, 32))
        self.camera_capture_button.setCheckable(True)
        self.camera_capture_button.setAutoDefault(True)

        self.horizontallayout_8.addWidget(self.camera_capture_button)


        self.gridLayout.addLayout(self.horizontallayout_8, 7, 0, 1, 2)

        self.camera_integration_checkbox = QCheckBox(self.camera_frame)
        self.camera_integration_checkbox.setObjectName(u"camera_integration_checkbox")

        self.gridLayout.addWidget(self.camera_integration_checkbox, 5, 0, 1, 1)

        self.camera_gain_label = QLabel(self.camera_frame)
        self.camera_gain_label.setObjectName(u"camera_gain_label")
        sizePolicy.setHeightForWidth(self.camera_gain_label.sizePolicy().hasHeightForWidth())
        self.camera_gain_label.setSizePolicy(sizePolicy)

        self.gridLayout.addWidget(self.camera_gain_label, 3, 0, 1, 1)

        self.camera_filter_combobox = QComboBox(self.camera_frame)
        self.camera_filter_combobox.setObjectName(u"camera_filter_combobox")
        sizePolicy4.setHeightForWidth(self.camera_filter_combobox.sizePolicy().hasHeightForWidth())
        self.camera_filter_combobox.setSizePolicy(sizePolicy4)
        self.camera_filter_combobox.setFocusPolicy(Qt.StrongFocus)

        self.gridLayout.addWidget(self.camera_filter_combobox, 6, 1, 1, 1)

        self.camera_exposure_label = QLabel(self.camera_frame)
        self.camera_exposure_label.setObjectName(u"camera_exposure_label")
        sizePolicy.setHeightForWidth(self.camera_exposure_label.sizePolicy().hasHeightForWidth())
        self.camera_exposure_label.setSizePolicy(sizePolicy)

        self.gridLayout.addWidget(self.camera_exposure_label, 1, 0, 1, 1)

        self.camera_filter_label = QLabel(self.camera_frame)
        self.camera_filter_label.setObjectName(u"camera_filter_label")

        self.gridLayout.addWidget(self.camera_filter_label, 6, 0, 1, 1)

        self.camera_gain_spinbox = QSpinBox(self.camera_frame)
        self.camera_gain_spinbox.setObjectName(u"camera_gain_spinbox")
        self.camera_gain_spinbox.setFocusPolicy(Qt.StrongFocus)

        self.gridLayout.addWidget(self.camera_gain_spinbox, 3, 1, 1, 1)

        self.camera_integration_spinbox = QSpinBox(self.camera_frame)
        self.camera_integration_spinbox.setObjectName(u"camera_integration_spinbox")
        self.camera_integration_spinbox.setEnabled(False)
        self.camera_integration_spinbox.setFocusPolicy(Qt.StrongFocus)

        self.gridLayout.addWidget(self.camera_integration_spinbox, 5, 1, 1, 1)


        self.formLayout_8.setWidget(1, QFormLayout.SpanningRole, self.camera_frame)


        self.formLayout_4.setWidget(2, QFormLayout.SpanningRole, self.camera_group)

        self.wheel_group = QGroupBox(self.scroll_area_widget_contents)
        self.wheel_group.setObjectName(u"wheel_group")
        sizePolicy2.setHeightForWidth(self.wheel_group.sizePolicy().hasHeightForWidth())
        self.wheel_group.setSizePolicy(sizePolicy2)
        self.wheel_group.setCheckable(True)
        self.wheel_group.setChecked(False)
        self.formLayout = QFormLayout(self.wheel_group)
        self.formLayout.setObjectName(u"formLayout")
        self.horizontallayout_13 = QHBoxLayout()
        self.horizontallayout_13.setObjectName(u"horizontallayout_13")
        self.wheel_name_label = QLabel(self.wheel_group)
        self.wheel_name_label.setObjectName(u"wheel_name_label")
        sizePolicy3.setHeightForWidth(self.wheel_name_label.sizePolicy().hasHeightForWidth())
        self.wheel_name_label.setSizePolicy(sizePolicy3)
        self.wheel_name_label.setWordWrap(True)

        self.horizontallayout_13.addWidget(self.wheel_name_label)

        self.wheel_settings_btn = QToolButton(self.wheel_group)
        self.wheel_settings_btn.setObjectName(u"wheel_settings_btn")
        sizePolicy.setHeightForWidth(self.wheel_settings_btn.sizePolicy().hasHeightForWidth())
        self.wheel_settings_btn.setSizePolicy(sizePolicy)
        self.wheel_settings_btn.setIcon(icon9)
        self.wheel_settings_btn.setPopupMode(QToolButton.InstantPopup)

        self.horizontallayout_13.addWidget(self.wheel_settings_btn)


        self.formLayout.setLayout(0, QFormLayout.SpanningRole, self.horizontallayout_13)

        self.wheel_frame = QFrame(self.wheel_group)
        self.wheel_frame.setObjectName(u"wheel_frame")
        self.wheel_frame.setFrameShape(QFrame.NoFrame)
        self.wheel_frame.setFrameShadow(QFrame.Plain)
        self.wheel_frame.setLineWidth(0)
        self.gridLayout_3 = QGridLayout(self.wheel_frame)
        self.gridLayout_3.setObjectName(u"gridLayout_3")
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.position_label = QLabel(self.wheel_frame)
        self.position_label.setObjectName(u"position_label")
        sizePolicy.setHeightForWidth(self.position_label.sizePolicy().hasHeightForWidth())
        self.position_label.setSizePolicy(sizePolicy)

        self.gridLayout_3.addWidget(self.position_label, 1, 0, 1, 1)

        self.position_combobox = QComboBox(self.wheel_frame)
        self.position_combobox.setObjectName(u"position_combobox")
        sizePolicy5.setHeightForWidth(self.position_combobox.sizePolicy().hasHeightForWidth())
        self.position_combobox.setSizePolicy(sizePolicy5)
        self.position_combobox.setFocusPolicy(Qt.StrongFocus)
        self.position_combobox.setEditable(True)
        self.position_combobox.setInsertPolicy(QComboBox.NoInsert)

        self.gridLayout_3.addWidget(self.position_combobox, 1, 1, 1, 1)

        self.line_6 = QFrame(self.wheel_frame)
        self.line_6.setObjectName(u"line_6")
        self.line_6.setFrameShape(QFrame.HLine)
        self.line_6.setFrameShadow(QFrame.Sunken)

        self.gridLayout_3.addWidget(self.line_6, 0, 0, 1, 2)


        self.formLayout.setWidget(1, QFormLayout.SpanningRole, self.wheel_frame)


        self.formLayout_4.setWidget(3, QFormLayout.SpanningRole, self.wheel_group)

        self.focuser_group = QGroupBox(self.scroll_area_widget_contents)
        self.focuser_group.setObjectName(u"focuser_group")
        sizePolicy2.setHeightForWidth(self.focuser_group.sizePolicy().hasHeightForWidth())
        self.focuser_group.setSizePolicy(sizePolicy2)
        self.focuser_group.setCheckable(True)
        self.focuser_group.setChecked(False)
        self.formLayout_9 = QFormLayout(self.focuser_group)
        self.formLayout_9.setObjectName(u"formLayout_9")
        self.horizontallayout_12 = QHBoxLayout()
        self.horizontallayout_12.setObjectName(u"horizontallayout_12")
        self.focuser_name_label = QLabel(self.focuser_group)
        self.focuser_name_label.setObjectName(u"focuser_name_label")
        sizePolicy3.setHeightForWidth(self.focuser_name_label.sizePolicy().hasHeightForWidth())
        self.focuser_name_label.setSizePolicy(sizePolicy3)
        self.focuser_name_label.setWordWrap(True)

        self.horizontallayout_12.addWidget(self.focuser_name_label)

        self.focuser_settings_btn = QToolButton(self.focuser_group)
        self.focuser_settings_btn.setObjectName(u"focuser_settings_btn")
        sizePolicy.setHeightForWidth(self.focuser_settings_btn.sizePolicy().hasHeightForWidth())
        self.focuser_settings_btn.setSizePolicy(sizePolicy)
        self.focuser_settings_btn.setIcon(icon9)
        self.focuser_settings_btn.setPopupMode(QToolButton.InstantPopup)

        self.horizontallayout_12.addWidget(self.focuser_settings_btn)


        self.formLayout_9.setLayout(0, QFormLayout.SpanningRole, self.horizontallayout_12)

        self.focuser_frame = QFrame(self.focuser_group)
        self.focuser_frame.setObjectName(u"focuser_frame")
        self.focuser_frame.setFrameShape(QFrame.NoFrame)
        self.focuser_frame.setFrameShadow(QFrame.Plain)
        self.focuser_frame.setLineWidth(0)
        self.gridLayout_2 = QGridLayout(self.focuser_frame)
        self.gridLayout_2.setObjectName(u"gridLayout_2")
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.focuser_position_spinbox = QSpinBox(self.focuser_frame)
        self.focuser_position_spinbox.setObjectName(u"focuser_position_spinbox")
        self.focuser_position_spinbox.setFocusPolicy(Qt.StrongFocus)

        self.gridLayout_2.addWidget(self.focuser_position_spinbox, 1, 1, 1, 1)

        self.focuser_position_label = QLabel(self.focuser_frame)
        self.focuser_position_label.setObjectName(u"focuser_position_label")
        sizePolicy.setHeightForWidth(self.focuser_position_label.sizePolicy().hasHeightForWidth())
        self.focuser_position_label.setSizePolicy(sizePolicy)

        self.gridLayout_2.addWidget(self.focuser_position_label, 1, 0, 1, 1)

        self.line_5 = QFrame(self.focuser_frame)
        self.line_5.setObjectName(u"line_5")
        self.line_5.setFrameShape(QFrame.HLine)
        self.line_5.setFrameShadow(QFrame.Sunken)

        self.gridLayout_2.addWidget(self.line_5, 0, 0, 1, 2)

        self.temp_checkbox = QCheckBox(self.focuser_frame)
        self.temp_checkbox.setObjectName(u"temp_checkbox")

        self.gridLayout_2.addWidget(self.temp_checkbox, 2, 0, 1, 2)


        self.formLayout_9.setWidget(1, QFormLayout.SpanningRole, self.focuser_frame)


        self.formLayout_4.setWidget(4, QFormLayout.SpanningRole, self.focuser_group)

        self.scrollarea.setWidget(self.scroll_area_widget_contents)

        self.horizontalLayout_2.addWidget(self.scrollarea)

        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 937, 25))
        self.file_menu = QMenu(self.menubar)
        self.file_menu.setObjectName(u"file_menu")
        self.import_menu = QMenu(self.file_menu)
        self.import_menu.setObjectName(u"import_menu")
        self.menuExport = QMenu(self.file_menu)
        self.menuExport.setObjectName(u"menuExport")
        self.menu_edit = QMenu(self.menubar)
        self.menu_edit.setObjectName(u"menu_edit")
        self.menu_equipment = QMenu(self.menu_edit)
        self.menu_equipment.setObjectName(u"menu_equipment")
        self.help_menu = QMenu(self.menubar)
        self.help_menu.setObjectName(u"help_menu")
        MainWindow.setMenuBar(self.menubar)
        QWidget.setTabOrder(self.mount_group, self.scrollarea)
        QWidget.setTabOrder(self.scrollarea, self.scope_settings_btn)
        QWidget.setTabOrder(self.scope_settings_btn, self.slewnorthwest_button)
        QWidget.setTabOrder(self.slewnorthwest_button, self.slewnorth_button)
        QWidget.setTabOrder(self.slewnorth_button, self.slewnortheast_button)
        QWidget.setTabOrder(self.slewnortheast_button, self.slewwest_button)
        QWidget.setTabOrder(self.slewwest_button, self.slewstop_button)
        QWidget.setTabOrder(self.slewstop_button, self.sleweast_button)
        QWidget.setTabOrder(self.sleweast_button, self.slewsouthwest_button)
        QWidget.setTabOrder(self.slewsouthwest_button, self.slewsouth_button)
        QWidget.setTabOrder(self.slewsouth_button, self.slewsoutheast_button)
        QWidget.setTabOrder(self.slewsoutheast_button, self.mount_trackrate_spin)
        QWidget.setTabOrder(self.mount_trackrate_spin, self.object_combobox)
        QWidget.setTabOrder(self.object_combobox, self.goto_button)
        QWidget.setTabOrder(self.goto_button, self.guider_group)
        QWidget.setTabOrder(self.guider_group, self.guider_settings_btn)
        QWidget.setTabOrder(self.guider_settings_btn, self.guider_exposure_spinbox)
        QWidget.setTabOrder(self.guider_exposure_spinbox, self.guider_exposure_slider)
        QWidget.setTabOrder(self.guider_exposure_slider, self.guider_gain_spinbox)
        QWidget.setTabOrder(self.guider_gain_spinbox, self.guider_gain_slider)
        QWidget.setTabOrder(self.guider_gain_slider, self.guider_loop_button)
        QWidget.setTabOrder(self.guider_loop_button, self.guider_start_button)
        QWidget.setTabOrder(self.guider_start_button, self.camera_group)
        QWidget.setTabOrder(self.camera_group, self.camera_settings_btn)
        QWidget.setTabOrder(self.camera_settings_btn, self.camera_exposure_spinbox)
        QWidget.setTabOrder(self.camera_exposure_spinbox, self.camera_exposure_slider)
        QWidget.setTabOrder(self.camera_exposure_slider, self.camera_gain_spinbox)
        QWidget.setTabOrder(self.camera_gain_spinbox, self.camera_gain_slider)
        QWidget.setTabOrder(self.camera_gain_slider, self.camera_integration_spinbox)
        QWidget.setTabOrder(self.camera_integration_spinbox, self.camera_loop_button)
        QWidget.setTabOrder(self.camera_loop_button, self.camera_capture_button)
        QWidget.setTabOrder(self.camera_capture_button, self.focuser_group)
        QWidget.setTabOrder(self.focuser_group, self.focuser_settings_btn)
        QWidget.setTabOrder(self.focuser_settings_btn, self.focuser_position_spinbox)
        QWidget.setTabOrder(self.focuser_position_spinbox, self.temp_checkbox)
        QWidget.setTabOrder(self.temp_checkbox, self.wheel_settings_btn)
        QWidget.setTabOrder(self.wheel_settings_btn, self.position_combobox)

        self.menubar.addAction(self.file_menu.menuAction())
        self.menubar.addAction(self.menu_edit.menuAction())
        self.menubar.addAction(self.help_menu.menuAction())
        self.file_menu.addAction(self.import_menu.menuAction())
        self.file_menu.addAction(self.menuExport.menuAction())
        self.file_menu.addSeparator()
        self.file_menu.addAction(self.action_exit)
        self.import_menu.addAction(self.importfilters_action)
        self.import_menu.addAction(self.importschedule_action)
        self.menuExport.addAction(self.actionFilters)
        self.menuExport.addAction(self.actionSchedule)
        self.menu_edit.addAction(self.menu_equipment.menuAction())
        self.menu_edit.addAction(self.filters_action)
        self.menu_edit.addAction(self.location_action)
        self.menu_equipment.addAction(self.telescope_action)
        self.menu_equipment.addAction(self.guider_action)
        self.menu_equipment.addAction(self.camera_action)
        self.menu_equipment.addAction(self.wheel_action)
        self.menu_equipment.addAction(self.focuser_action)
        self.help_menu.addAction(self.action_about)

        self.retranslateUi(MainWindow)
        self.guider_exposure_slider.valueChanged.connect(self.guider_exposure_spinbox.setValue)
        self.guider_gain_slider.valueChanged.connect(self.guider_gain_spinbox.setValue)
        self.camera_gain_slider.valueChanged.connect(self.camera_gain_spinbox.setValue)
        self.camera_exposure_slider.valueChanged.connect(self.camera_exposure_spinbox.setValue)
        self.guider_exposure_spinbox.valueChanged.connect(self.guider_exposure_slider.setValue)
        self.camera_gain_spinbox.valueChanged.connect(self.camera_gain_slider.setValue)
        self.guider_gain_spinbox.valueChanged.connect(self.guider_gain_slider.setValue)
        self.camera_exposure_spinbox.valueChanged.connect(self.camera_exposure_slider.setValue)
        self.guider_loop_button.toggled.connect(self.guider_start_button.setEnabled)
        self.camera_loop_button.toggled.connect(self.camera_capture_button.setEnabled)
        self.mount_group.toggled.connect(self.telescope_action.setChecked)
        self.guider_group.toggled.connect(self.guider_action.setChecked)
        self.camera_group.toggled.connect(self.camera_action.setChecked)
        self.focuser_group.toggled.connect(self.focuser_action.setChecked)
        self.wheel_group.toggled.connect(self.wheel_action.setChecked)
        self.telescope_action.toggled.connect(self.mount_group.setChecked)
        self.guider_action.toggled.connect(self.guider_group.setChecked)
        self.wheel_action.toggled.connect(self.wheel_group.setChecked)
        self.camera_action.toggled.connect(self.camera_group.setChecked)
        self.focuser_action.toggled.connect(self.focuser_group.setChecked)
        self.guider_loop_button.toggled.connect(self.guider_settings_btn.setDisabled)
        self.camera_loop_button.toggled.connect(self.camera_settings_btn.setDisabled)
        self.action_exit.triggered.connect(MainWindow.close)
        self.camera_capture_button.toggled.connect(self.camera_loop_button.setDisabled)
        self.guider_start_button.toggled.connect(self.guider_loop_button.setDisabled)
        self.camera_capture_button.toggled.connect(self.camera_filter_combobox.setDisabled)
        self.camera_capture_button.toggled.connect(self.camera_filter_label.setDisabled)
        self.wheel_group.toggled.connect(self.camera_filter_label.setHidden)
        self.wheel_group.toggled.connect(self.camera_filter_combobox.setHidden)
        self.camera_integration_checkbox.toggled.connect(self.camera_integration_spinbox.setEnabled)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Ecliptic", None))
        self.filters_action.setText(QCoreApplication.translate("MainWindow", u"Filters", None))
#if QT_CONFIG(shortcut)
        self.filters_action.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+F", None))
#endif // QT_CONFIG(shortcut)
        self.location_action.setText(QCoreApplication.translate("MainWindow", u"Location", None))
#if QT_CONFIG(shortcut)
        self.location_action.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+L", None))
#endif // QT_CONFIG(shortcut)
        self.targets_action.setText(QCoreApplication.translate("MainWindow", u"Targets", None))
#if QT_CONFIG(shortcut)
        self.targets_action.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+T", None))
#endif // QT_CONFIG(shortcut)
        self.action_undo.setText(QCoreApplication.translate("MainWindow", u"Undo", None))
#if QT_CONFIG(shortcut)
        self.action_undo.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Z", None))
#endif // QT_CONFIG(shortcut)
        self.action_redo.setText(QCoreApplication.translate("MainWindow", u"Redo", None))
#if QT_CONFIG(shortcut)
        self.action_redo.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Y", None))
#endif // QT_CONFIG(shortcut)
        self.action_about.setText(QCoreApplication.translate("MainWindow", u"About", None))
        self.telescope_action.setText(QCoreApplication.translate("MainWindow", u"Telescope", None))
        self.guider_action.setText(QCoreApplication.translate("MainWindow", u"Guider", None))
        self.camera_action.setText(QCoreApplication.translate("MainWindow", u"Camera", None))
        self.focuser_action.setText(QCoreApplication.translate("MainWindow", u"Focuser", None))
        self.wheel_action.setText(QCoreApplication.translate("MainWindow", u"Filter Wheel", None))
        self.importschedule_action.setText(QCoreApplication.translate("MainWindow", u"Schedule", None))
        self.importfilters_action.setText(QCoreApplication.translate("MainWindow", u"Filters", None))
        self.savelocation_action.setText(QCoreApplication.translate("MainWindow", u"Save Location", None))
        self.action_exit.setText(QCoreApplication.translate("MainWindow", u"Exit", None))
#if QT_CONFIG(shortcut)
        self.action_exit.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Q", None))
#endif // QT_CONFIG(shortcut)
        self.actionFilters.setText(QCoreApplication.translate("MainWindow", u"Filters", None))
        self.actionSchedule.setText(QCoreApplication.translate("MainWindow", u"Schedule", None))
        self.ascomcamerasettings_action.setText(QCoreApplication.translate("MainWindow", u"ASCOM Settings", None))
        self.ascomguidersettings_action.setText(QCoreApplication.translate("MainWindow", u"ASCOM Settings", None))
        self.mount_group.setTitle(QCoreApplication.translate("MainWindow", u"Telescope", None))
        self.telescope_name_label.setText(QCoreApplication.translate("MainWindow", u"Not Connected", None))
        self.scope_settings_btn.setText("")
#if QT_CONFIG(tooltip)
        self.slewnorth_button.setToolTip(QCoreApplication.translate("MainWindow", u"Slew the mount north", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.slewsouthwest_button.setToolTip(QCoreApplication.translate("MainWindow", u"Slew the mount west", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.sleweast_button.setToolTip(QCoreApplication.translate("MainWindow", u"Slew the mount east", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.slewnorthwest_button.setToolTip(QCoreApplication.translate("MainWindow", u"Slew the mount north", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.slewsoutheast_button.setToolTip(QCoreApplication.translate("MainWindow", u"Slew the mount south", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.slewstop_button.setToolTip(QCoreApplication.translate("MainWindow", u"Slew the mount west", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.slewwest_button.setToolTip(QCoreApplication.translate("MainWindow", u"Slew the mount west", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.slewsouth_button.setToolTip(QCoreApplication.translate("MainWindow", u"Slew the mount south", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.slewnortheast_button.setToolTip(QCoreApplication.translate("MainWindow", u"Slew the mount east", None))
#endif // QT_CONFIG(tooltip)
        self.mount_trackrate_label.setText(QCoreApplication.translate("MainWindow", u"Rate", None))
        self.mount_trackrate_spin.setPrefix(QCoreApplication.translate("MainWindow", u"~", None))
        self.mount_trackrate_spin.setSuffix(QCoreApplication.translate("MainWindow", u"\u00b0/s", None))
        self.object_label.setText(QCoreApplication.translate("MainWindow", u"Target", None))
#if QT_CONFIG(tooltip)
        self.goto_button.setToolTip(QCoreApplication.translate("MainWindow", u"Go to target", None))
#endif // QT_CONFIG(tooltip)
        self.goto_button.setText("")
        self.guider_group.setTitle(QCoreApplication.translate("MainWindow", u"Guider", None))
        self.guider_name_label.setText(QCoreApplication.translate("MainWindow", u"Not Connected", None))
        self.guider_settings_btn.setText("")
        self.guider_exposure_label.setText(QCoreApplication.translate("MainWindow", u"Exposure", None))
        self.guider_exposure_spinbox.setSuffix(QCoreApplication.translate("MainWindow", u"ms", None))
        self.guider_gain_label.setText(QCoreApplication.translate("MainWindow", u"Gain", None))
        self.guider_gain_spinbox.setSuffix(QCoreApplication.translate("MainWindow", u"e/adu", None))
        self.camera_group.setTitle(QCoreApplication.translate("MainWindow", u"Camera", None))
        self.camera_name_label.setText(QCoreApplication.translate("MainWindow", u"Not Connected", None))
        self.camera_settings_btn.setText("")
        self.camera_exposure_spinbox.setSuffix(QCoreApplication.translate("MainWindow", u"ms", None))
        self.camera_integration_checkbox.setText(QCoreApplication.translate("MainWindow", u"Integration", None))
        self.camera_gain_label.setText(QCoreApplication.translate("MainWindow", u"Gain", None))
        self.camera_exposure_label.setText(QCoreApplication.translate("MainWindow", u"Exposure", None))
        self.camera_filter_label.setText(QCoreApplication.translate("MainWindow", u"Filter", None))
        self.camera_gain_spinbox.setSuffix(QCoreApplication.translate("MainWindow", u"e/adu", None))
        self.camera_integration_spinbox.setSuffix(QCoreApplication.translate("MainWindow", u"s", None))
        self.wheel_group.setTitle(QCoreApplication.translate("MainWindow", u"Filter Wheel", None))
        self.wheel_name_label.setText(QCoreApplication.translate("MainWindow", u"Not Connected", None))
        self.wheel_settings_btn.setText("")
        self.position_label.setText(QCoreApplication.translate("MainWindow", u"Position", None))
        self.focuser_group.setTitle(QCoreApplication.translate("MainWindow", u"Focuser", None))
        self.focuser_name_label.setText(QCoreApplication.translate("MainWindow", u"Not Connected", None))
        self.focuser_settings_btn.setText("")
        self.focuser_position_label.setText(QCoreApplication.translate("MainWindow", u"Position", None))
        self.temp_checkbox.setText(QCoreApplication.translate("MainWindow", u"Temp Comp", None))
        self.file_menu.setTitle(QCoreApplication.translate("MainWindow", u"File", None))
        self.import_menu.setTitle(QCoreApplication.translate("MainWindow", u"Import", None))
        self.menuExport.setTitle(QCoreApplication.translate("MainWindow", u"Export", None))
        self.menu_edit.setTitle(QCoreApplication.translate("MainWindow", u"Edit", None))
        self.menu_equipment.setTitle(QCoreApplication.translate("MainWindow", u"Equipment", None))
        self.help_menu.setTitle(QCoreApplication.translate("MainWindow", u"Help", None))
    # retranslateUi

